app/assets/stylesheets/application/themes.scss, app/assets/stylesheets/mozilla-pdf-viewer/cozy-honey-bear-reader.css, app/controllers/e_pubs_controller.rb, app/views/e_pubs/show_pdf.html.erb
=> add/tweak Mozilla PDF download bar

app/controllers/e_pubs_controller.rb, app/presenters/concerns/common_work_presenter.rb, app/presenters/hyrax/file_set_presenter.rb, app/views/e_pubs/show_pdf.html.erb, app/views/hyrax/file_sets/media_display/_image_service.html.erb, app/views/hyrax/file_sets/media_display/_leaflet_image.html.erb, app/views/hyrax/file_sets/media_display_embedded/_leaflet_image.html.erb, app/views/monograph_catalog/_index_gallery_file_set_wrapper.html.erb, app/views/monograph_catalog/_thumbnail_list_file_set.html.erb, app/views/score_catalog/_thumbnail_list_file_set.html.erb
=> reader uses cached PDF file

app/assets/stylesheets/application/heliotrope.scss, app/helpers/facets_helper.rb, app/views/catalog/_search_sidebar.html.erb, app/views/catalog/facet.html.erb, spec/features/monograph_catalog_facets_spec.rb, spec/features/press_catalog_spec.rb
=> Resolve HELIO-3002: NVDA, a change for the better.

lib/tasks/institution_usage_from_counter.rake
There's no ticket for this, but it's just a rake task. Maybe will be useful some day for some reason.
=> insitutional report based on counter data rake task

app/views/hyrax/base/_form_permission.html.erb, app/views/hyrax/file_sets/_permission_form.html.erb
=> hide unused permissions, 'share with' spiel

app/assets/javascripts/application/tabs.js, app/assets/stylesheets/application/semantic-bootstrap-tabs.scss, app/views/catalog/_search_sidebar.html.erb, app/views/hyrax/file_sets/_attributes.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/press_statistics/index.html.erb, app/views/score_catalog/_index_score.html.erb, app/views/score_catalog/_search_results.html.erb
=> a11y: summary-visible tab headings

app/views/hyrax/base/_form_permission.html.erb, app/views/hyrax/base/_form_visibility_component.html.erb, app/views/hyrax/file_sets/_permission_form.html.erb, spec/features/create_monograph_spec.rb, spec/features/edit_file_set_spec.rb, spec/system/create_score_spec.rb
=> more permissions partials cleanup

.travis.yml, Gemfile.lock
=> Update to bundler 2

spec/spec_helper.rb, spec/system/batch_create_monographs_spec.rb, spec/system/create_score_spec.rb, spec/system/dashboard_users_spec.rb, spec/system/epub_share_links_spec.rb, spec/system/monograph_catalog_toc_spec.rb, spec/system/score_file_sets_spec.rb, spec/system/toc_epub_chapter_spec.rb
HELIO-3046: timing adjustments; skip system specs by default (i.e. they won't run on Travis)
=> timing problems; skip system specs by default

app/controllers/ebooks_controller.rb, app/presenters/hyrax/monograph_presenter.rb, spec/presenters/hyrax/monograph_presenter_spec.rb, spec/requests/ebooks_spec.rb
=> watermark uses authors not creator_display

app/assets/javascripts/application/ajax_modal_ex.js, app/views/layouts/boilerplate.html.erb, spec/system/monograph_catalog_features_spec.rb
=> Helio 3162/broken bootstrap modal image

app/helpers/breadcrumbs_helper.rb, config/locales/en.yml, spec/helpers/breadcrumbs_spec.rb
=> Modify Breadcrumbs for Publishers using Aboutware

app/assets/javascripts/application/role_button_click_on_enter.js
=> more focused facet-panel-toggle event

app/views/e_pubs/show.html.erb
HELIO-3189 (became hot fix release 2.53.1)
=> more presses need enhanced resource CSS

app/presenters/hyrax/file_set_presenter.rb, spec/presenters/hyrax/file_set_presenter_spec.rb
=> PDF button says 'View' not 'Download

app/presenters/hyrax/monograph_presenter.rb, app/views/monograph_catalog/_index_monograph.html.erb, spec/presenters/hyrax/monograph_presenter_spec.rb
=> show 'BAR number' on Monograph catalog page

app/views/hyrax/file_sets/_actions.html.erb, spec/views/hyrax/file_sets/_actions.html.erb_spec.rb
=> Disable turbolinks to fix re-versioning route bug

app/helpers/hyrax/citations_behaviors/formatters/apa_formatter.rb, app/helpers/hyrax/citations_behaviors/formatters/chicago_formatter.rb, app/helpers/hyrax/citations_behaviors/formatters/mla_formatter.rb, app/helpers/hyrax/citations_behaviors/name_behavior.rb, spec/helpers/hyrax/citations_behavior_spec.rb, spec/helpers/hyrax/citations_behaviors/name_behavior_spec.rb
=> citations: never reverse names; tidy eBook format

fulcrum/about.html
Update the Fulcrum aboutware - remove Emma from the about page team list, as she is no longer the community manager for Fulcrum.
=> HELIO-3208 - update Fulcrum Team

app/controllers/ebooks_controller.rb, app/services/counter_service.rb, spec/requests/ebooks_spec.rb, spec/services/counter_service_spec.rb
=> Added COUNTER report counts for watermarked downloads

.gitignore, app/services/royalty/calculation_report.rb, app/services/royalty/reportable.rb, app/services/royalty/usage_report.rb, config/box.yml.sample, spec/services/royalty/calculation_report_spec.rb, spec/services/royalty/usage_report_spec.rb
HELIO-2819, HELIO-3155
I'd like to get this merged into master. The reports that this generates are under review by various people, and I'm sure there will be additions/changes/iterations, but I'll make those new tasks/tickets.
This code 1) produces reports that meet the original ticket criteria 2) has decent (92% +) test coverage and 3) is almost totally self contained, so won't conflict with anything, so is safe to merge.
=> Royalty usage and calculation reports

Gemfile, Gemfile.lock
Pulls in the following work during Sprint 97:
CSB-218: https://tools.lib.umich.edu/jira/browse/CSB-218
CSB-245: https://tools.lib.umich.edu/jira/browse/CSB-245
=> Update CSB to pull in work from Sprint 97

app/services/royalty/calculation_report.rb, app/services/royalty/reportable.rb, app/services/royalty/usage_report.rb, spec/services/royalty/calculation_report_spec.rb, spec/services/royalty/usage_report_spec.rb
=> Implemented requested changes to royalty reports

Gemfile, Gemfile.lock, config/initializers/clamav.rb, spec/config/initializers/clamav_spec.rb
=> add clamby instead of clamav for virus scanning

app/jobs/aptrust_deposit_job.rb, spec/jobs/aptrust_deposit_job_spec.rb, spec/models/ability_spec.rb, spec/models/manifest_spec.rb, spec/services/aptrust/service_spec.rb, spec/services/incognito_spec.rb, spec/services/turnsole/service_spec.rb
No code changes just more specs to increase code coverage.
=> More code coverage.

config/locales/en.yml, config/locales/heliotrope.en.yml
=> improved ISBN hint/help text w/formats

app/controllers/handle_deposits_controller.rb, app/models/handle_deposit.rb, app/views/handle_deposits/index.html.erb, spec/services/sighrax_spec.rb
=> Remove sigma from view

lib/tasks/bar_csv_monograph_create_update.rake, lib/tasks/bar_upload_monograph_representatives.rake, lib/tasks/tmm/tmm_upload_monograph_representatives.rake
create/edit Monograph metadata similar to TMM
cover and pdf_ebook FeaturedRepresentative iterate over a...
single directory
=> barpublishing ingest scripts

app/assets/stylesheets/application/themes.scss
=> HELIO-3178 - add custom styles for UNC Press

Gemfile, Gemfile.lock
Update CSB gem to pull in new functionality that supports opening interactive map resources in a modal window
=> CSB-250 - Interactive map support

Gemfile, Gemfile.lock
Update CSB to add jump to page feature and update nav slider styling.
=> CSB-228 - Jump to page feature

app/services/royalty/calculation_report.rb, app/services/royalty/usage_report.rb, spec/services/royalty/calculation_report_spec.rb, spec/services/royalty/usage_report_spec.rb
=> Royalty reports: no longer x25 Chapter hits

app/views/e_pubs/show.html.erb
=> enable enhanced CSS for uncpress

config/locales/heliotrope.en.yml, lib/metadata_fields.rb, spec/lib/export/exporter_spec.rb
=> language is now a universal field

app/assets/stylesheets/application/themes.scss
Styles added for new publisher AHPI
=> HELIO-3169 - add styles for AHPI

config/jekyll.yml
=> DiscoFeed static file should not be deleted by jekyll

README.md, spec/spec_helper.rb
=> improve Travis system spec workaround

README.md, app/views/layouts/boilerplate.html.erb, app/views/shared/_monitoring.html.erb, config/jekyll.yml, spec/spec_helper.rb
=> System Specs - DiscoFeed - Real User Monitor

.rubocop.yml, app/controllers/api_requests_controller.rb, app/controllers/fulcrum_controller.rb, app/views/fulcrum/_jobs.html.erb, app/views/fulcrum/_logs.html.erb, app/views/fulcrum/_reports.html.erb, config/blacklight.yml, config/cable.yml, config/database.yml.sample, config/fedora.yml, config/redis.yml, config/role_map.yml.sample, config/secrets.yml.sample, config/solr.yml
Removed devproque environment since it is no longer needed thanks to something Conor did to fix jobs rails loading.
Cleaned up some views under the fulcrum dashboard.
=> Clean up logs, reports, and jobs pages and remove some dead code.

app/jobs/unpack_job.rb
=>  warnings break PDF chapter file creation

app/controllers/e_pubs_controller.rb, spec/controllers/e_pubs_controller_spec.rb
=> Remove extraneous solr calls from the epubs controller

app/assets/javascripts/application/ga_event_tracking.js, app/views/monograph_catalog/_index_epub_toc.html.erb
Debug code removed from app/assets/javascripts/application/ga_event_tracking.js this time round.
=> HELIO-3214 ToC Download/Read button GA tracking

app/views/e_pubs/show_pdf.html.erb
=> stop doubling prev/next actions

app/views/e_pubs/show_pdf.html.erb
New version without the IE 11 incompatible async Promise stuff.
=> HELIO-3262 [Firefox] PDF EReader Preferences Button Does Not Open

app/views/catalog/_facet_pagination.html.erb
Solution adapted from Blacklight PR:
https://github.com/projectblacklight/blacklight/commit/07f14aec5f7cbdf6d210ae989284901288ffa45f
=> HELIO-3292 Facet 'more' modal shows span tags

app/controllers/e_pubs_controller.rb, app/controllers/ebooks_controller.rb, app/services/watermark/watermarkable.rb
Fixes misplaced watermark due to TrimBox != MediaBox
Fixes cache key not taking chapter title into account
=> HELIO-3296 PDF Watermark Hotfixes for BAR

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss
=> HELIO-3295 - BAR customizations pre-launch

app/views/shared/_brand_press_bar_custom.html.erb
This fixes a bug (and is in production as 2.56.2) but is awkward with a better/more complete refactor planned in HELIO-3311
=> Helio 3309/epubs access for bar bug

app/presenters/concerns/common_work_presenter.rb, spec/presenters/concerns/common_work_presenter_spec.rb
Should reduce solr queries by 88% on that page
HELIO-3305
=> Stop using representative presenters on the press_catalog page

config/robots/robots.production.txt, config/sitemap.rb
=> no CSB links or epub rep show pages in sitemap

config/locales/en.yml
Updates EBC banner for COVID-19 message, extending open period to June 30.
=> Resolves HELIO-3322

app/policies/press_policy.rb, app/views/monograph_catalog/_index_epub_toc.html.erb, spec/policies/press_policy_spec.rb
=> no Read button without Download; clarify logic

spec/system/monograph_catalog_epub_toc_spec.rb, spec/system/monograph_catalog_pdf_ebook_toc_spec.rb
=> system specs fixes for HELIO-3310

app/views/monographs/edit_fields/_open_access.html.erb, config/locales/heliotrope.en.yml, lib/import/row_data.rb, spec/features/create_monograph_spec.rb, spec/lib/import/row_data_spec.rb
=> open_access should only be 'yes'

lib/tasks/handles/fulcrum_published_dois.rake
=> add 'barpublishing' subdomain and subdomain column

app/views/e_pubs/access/_barpublishing.html.erb, app/views/e_pubs/access/_heb.html.erb, app/views/e_pubs/access/_michigan.html.erb
This is in production as 2.57.1
=> restricted_message uses the press_presenter, fixes 500 bug

spec/features/epub_access_spec.rb
=> test default/custom epubs_access pages

db/migrate/20200420214220_increaase_submission_xml_length_in_crossref_submission_logs.rb, db/schema.rb
=> submission_xml to mediumtext length

app/controllers/press_catalog_controller.rb, app/models/press_search_builder.rb, spec/controllers/press_catalog_controller_spec.rb
...including extracted text (`all_text_timv`)
HELIO-3133
=> barpublishing: find monos w/file_set metadata

spec/jobs/destroy_active_fedora_objects_job_spec.rb
Not sure if this fixes anything but it is green.
=> force file set reindexing

app/assets/stylesheets/application/themes.scss
adjust padding on visualize engagement text for HEB publisher.
readership map for HEB has been added to its publisher config on production.
=> HELIO-3092 - Update HEB Visualize Impact/Engagement Page

app/services/royalty/calculation_report.rb, app/services/royalty/reportable.rb, app/services/royalty/usage_report.rb, spec/services/royalty/calculation_report_spec.rb
This is in production as 2.57.3
=> changes to royalty reports, HELIO-3299, HELIO-3330

app/controllers/utilities_controller.rb, config/routes.rb, spec/requests/utilities_spec.rb
=> Resolves HELIO-3339 www.fulcrum.org/whoami

app/views/hyrax/file_sets/media_display/_audio.html.erb, app/views/hyrax/file_sets/media_display_embedded/_audio.html.erb
=> data-transcript-div uses closed_captions now

spec/services/royalty/calculation_report_spec.rb
This is just a new spec, shouldn't be a problem to merge.
=> HELIO-3361 royalty reports respect case sensitivity test

app/controllers/fulcrum_controller.rb, app/views/fulcrum/_jobs.html.erb
So you can manually reindex by noid via the fulcrum jobs page.
=> Add form to job page so you may enter the noid to reindex.

app/presenters/press_presenter.rb, spec/presenters/press_presenter_spec.rb
=> don't use parent's press_statistics GA URLs

lib/tasks/usage_reports/institution_investigations_from_counter.rake, lib/tasks/usage_reports/institution_requests_from_counter.rake
This is just a rake task/report. MVP for HELIO-3337 so safe to merge.
=> HELIO-3337 Summary usage report by Institution (MVP version)

.rubocop_todo.yml, app/assets/stylesheets/application/heliotrope.scss, app/overrides/hydra/derivatives/processors/video/hydra_derivatives_processors_video_processor_overrides.rb, app/overrides/hyrax/file_set_derivatives_service_overrides.rb, spec/hydra-derivatives/processors/video_spec.rb
=> videos derivs: produce posters and better playback

.travis.yml, app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss, app/jobs/unpack_job.rb, lib/pdf_ebook/publication.rb
=> fix issues with nested ToC's

lib/tasks/tmm/tmm_csv_monograph_create_update.rake
=> map TMM subpress names to subdomains

app/views/hyrax/admin/stats/_altmetric.html.erb
=> add link to UMP Altmetric report

app/controllers/press_catalog_controller.rb, app/indexers/monograph_indexer.rb, spec/features/press_catalog_facets_spec.rb
=> michigan's subpresses 'Source' facet

app/assets/javascripts/application/banner.js, app/assets/stylesheets/application/themes.scss, app/helpers/banner_helper.rb, app/views/shared/_eula_press_banner.html.erb, app/views/shared/_header.html.erb, config/locales/en.yml, spec/helpers/banner_helper_spec.rb
Resolves HELIO-3391 - adds a custom banner to BAR Publishing, set cookies and don't display if agreed.
=> HELIO-3391 - BAR EULA Banner

app/views/hyrax/admin/stats/_institution.html.erb
this is in production as 2.59.1
=> HELIO-3402 UI fixes for Institution Usage reports

app/presenters/concerns/embed_code_presenter.rb, spec/presenters/concerns/embed_code_presenter_spec.rb, vendor/assets/javascripts/leaflet-iiif_1.2.1_best_fit.js
=> disallow negative 'best fit' zoom values

app/views/shared/_eula_press_banner.html.erb
=> HELIO-3416 Change "I Agree" to "OK" in BAR EULA banner

app/assets/stylesheets/application/themes.scss
Add a link to the BAR EULA agreement in the footer.
=> HELIO-3392 - BAR Footer

lib/tasks/bar_csv_monograph_create_update.rake
=> BAR backlist import changes

app/services/handle_net.rb, config/initializers/services.rb, config/settings/development.yml, config/settings/test.yml, spec/services/handle_net_spec.rb
ssl_verify false and a bug fix
=> ssl_verify parameter

app/assets/stylesheets/application/heliotrope.scss, app/views/hyrax/file_sets/_media.html.erb, app/views/hyrax/file_sets/_show_actions.html.erb
=> move share button; remove out-of-date TODOs

app/views/hyrax/file_sets/_show_actions.html.erb, spec/features/edit_file_set_spec.rb
=> remove old editor-only 'Back to Monograph' button

app/services/tmm/file_service.rb, lib/tasks/tmm/tmm_upload_monograph_representatives.rake, spec/services/tmm/file_service_spec.rb
=> new eBooks default to not being downloadable

app/models/concerns/heliotrope_mime_types.rb, app/models/file_set.rb, app/models/solr_document.rb, app/presenters/hyrax/file_set_presenter.rb, spec/jobs/create_derivatives_job_spec.rb, spec/models/file_set_spec.rb
=> module for MIME type overrides, add 'video/mpg'

app/jobs/handle_job.rb, app/views/handle_deposits/index.html.erb, spec/jobs/handle_job_spec.rb
Tweak to Solr query in handle_job.rb
FROM: "+has_model_ssim:[* TO *]",
TO: "+(has_model_ssim:Monograph OR has_model_ssim:FileSet)"
Plus changes to app/views/handle_deposits/index.html.erb.
=> Handle Hot Fix

app/views/hyrax/file_sets/media_display/_external_resource.erb, app/views/monograph_catalog/_index_gallery_file_set_wrapper.html.erb, app/views/monograph_catalog/_thumbnail_list_file_set.html.erb, spec/features/create_external_resource_spec.rb, spec/views/hyrax/file_sets/_media.html.erb_spec.rb
[X] Implement changes in heliotrope
=> Resolves HELIO-3420 Modify External Resource Display

lib/tasks/tmm/tmm_csv_monograph_create_update.rake
TMM needs to export UTF-16 for international chars.
We need UTF-8. Convert.
=> UTF-16 to UTF-8 conversion

app/views/e_pubs/show.html.erb, app/views/e_pubs/show_pdf.html.erb
Resolve HELIO-2707
Adds hypothesis for michigan and its sub-presses, excluding gabii.
=> HELIO-2707 - Hypothesis For UMP EBC

fulcrum/preservation.html
=> Remove broken link; add reference to NYU grant; fix typos.

app/models/press.rb, config/locales/en.yml, spec/models/press_spec.rb
=> allow hyphens in subdomains

app/views/e_pubs/show.html.erb
HELIO-3350 - new NOID for scroll-mode list
=> add NOID for another video-containing EPUB

app/controllers/press_catalog_controller.rb, spec/features/press_catalog_spec.rb
=> facets show with 9 visible monographs

app/controllers/application_controller.rb
=> don't cache institutions in session variable

solr/config/solrconfig.xml
This is on staging/testing/preview and all seems fine. We need to merge this and then after release add it to production.
=> HELIO-3542 Native solr lock config

app/services/aptrust/service.rb, spec/services/aptrust/service_spec.rb
=> use APTrust substring endpoint

app/views/e_pubs/show.html.erb
=> add Mezur NOID

app/controllers/monograph_catalog_controller.rb, app/helpers/facets_helper.rb, app/views/monograph_catalog/_case_insensitive_sort_facet.html.erb, spec/features/monograph_catalog_facets_spec.rb
=> make alphabetic facet value sort case-insensitive

lib/tasks/users/delete_users.rake
=> delete users and clean up related metadata

app/models/ability.rb, spec/models/ability_spec.rb
=> press editors should see edit buttons

app/jobs/unpack_job.rb, spec/jobs/unpack_job_spec.rb
=> don't run job in absence of original_file

db/migrate/20200914204534_increase_toc_length_in_ebook_table_of_contents_caches.rb, db/schema.rb
=> bump toc to mediumtext

lib/tasks/metadata_editing/monographs_output_csv_by_press.rake
=> output CSV for all of a press's monographs

app/presenters/hyrax/monograph_presenter.rb, app/views/e_pubs/access.html.erb, spec/presenters/hyrax/monograph_presenter_spec.rb
=> use parent press's access template

app/jobs/recache_counter_robots_job.rb, app/services/counter_service.rb, spec/fixtures/feed/counter_robots.json, spec/jobs/recache_counter_robots_job_spec.rb, spec/services/counter_service_spec.rb
There are a lot of notes in HELIO-3501, but ultimately this doesn't really do anything yet, just lays the groundwork for HELIO-2604
=> HELIO-3501 Eliminate crawlers from COUNTER stats tracking

app/assets/stylesheets/application/heliotrope.scss, app/controllers/monograph_catalog_controller.rb, app/views/catalog/facet.html.erb
=> bump keywords pagination limit to 1000

app/assets/stylesheets/application/themes.scss
=> a11y color contrast on HEB links

app/assets/javascripts/application/banner.js, app/views/shared/_brand_press_banner.html.erb, app/views/shared/_eula_press_banner.html.erb
=> banner fixes: no page reload, unique ids, rm cruft

config/locales/heliotrope.en.yml, lib/export/exporter.rb, lib/metadata_fields.rb, lib/tasks/metadata_editing/monographs_output_csv_by_press.rake, spec/lib/export/exporter_spec.rb
=> optionally export system-level metadata

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/api/opds/v2/feeds_controller.rb, app/controllers/api/opds/v2/v2.rb, app/controllers/api/opds/version.rb, app/controllers/api/v1/monographs_controller.rb, app/models/opds/publication.rb, app/models/sighrax/monograph.rb, config/routes.rb, spec/models/opds/publication_spec.rb, spec/models/sighrax/monograph_spec.rb, spec/rails_helper.rb, spec/requests/api/opds/V2/feeds_spec.rb, spec/requests/api/opds/version_spec.rb, spec/support/json_schema_spec_helper.rb
Resolves HELIO-3483 Create OPDS feed for UMPEBC OA titles in SimplyE
=> OPDS Catalog 2.0

app/controllers/utilities_controller.rb, app/services/status_page_service.rb, config/routes.rb, spec/requests/utilities_spec.rb
=> add app status page

app/controllers/api/opds/v2/feeds_controller.rb, config/routes.rb, spec/requests/api/opds/V2/feeds_spec.rb
All OA titles of product 'ebc_backlist' is equivalent to UMPEBC_OA.mrc.
=> All of the OA titles in EBC

app/services/counter_service.rb, spec/services/counter_service_spec.rb
This is in production as 2.65.1
=> HELIO-3574 Fix Access_Type for OA Monographs in COUNTER reports

app/controllers/e_pubs_controller.rb, app/presenters/concerns/common_work_presenter.rb, app/presenters/hyrax/file_set_presenter.rb, app/views/e_pubs/show_pdf.html.erb, app/views/hyrax/file_sets/media_display/_image_service.html.erb, app/views/hyrax/file_sets/media_display/_leaflet_image.html.erb, app/views/hyrax/file_sets/media_display_embedded/_leaflet_image.html.erb, app/views/monograph_catalog/_index_gallery_file_set_wrapper.html.erb, app/views/monograph_catalog/_thumbnail_list_file_set.html.erb, app/views/score_catalog/_index_gallery_file_set_wrapper.html.erb, app/views/score_catalog/_thumbnail_list_file_set.html.erb, spec/presenters/concerns/common_work_presenter_spec.rb, spec/presenters/hyrax/file_set_presenter_spec.rb
See also HELIO-3308
https://tools.lib.umich.edu/jira/browse/HELIO-3368?focusedCommentId=1022708&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1022708 describes the changes. A lot of the changes are in views which we don't have specs for. This worked fine for me in dev. We may want to put in on preview to test it out though (although deploys are super slow right now).
=> HELIO-3368 consistant iiif client-side cache breaking

app/controllers/catalog_controller.rb, app/controllers/press_catalog_controller.rb, app/views/catalog/_helio_results_sr_only_div.html.erb, app/views/catalog/_search_header.html.erb, app/views/catalog/_search_results.html.erb, spec/controllers/monograph_catalog_controller_spec.rb, spec/features/monograph_catalog_facets_spec.rb, spec/features/monograph_catalog_search_spec.rb, spec/features/press_catalog_search_spec.rb, spec/features/press_catalog_spec.rb
=> sr-only search results div

fulcrum/_posts/2020-04-14-big-collection-launch-updates.markdown, fulcrum/_posts/2020-07-17-publisher-launch-new-series-updates.markdown, fulcrum/_posts/2020-27-10-new-partnership-website-updates-forthcoming-titles.markdown, fulcrum/partner-with-us.html
add new blog posts and update partner with us page
=> HELIO-3598 - fulcrum homepage update

app/controllers/e_pubs_controller.rb, app/presenters/hyrax/monograph_presenter.rb, app/views/e_pubs/show.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, spec/controllers/e_pubs_controller_spec.rb
=> show OA survey on free-to-read books

app/overrides/hydra/derivatives/processors/video/hydra_derivatives_processors_video_processor_overrides.rb, spec/hydra-derivatives/processors/video_spec.rb
=> ensure even video deriv width

app/overrides/active_fedora/aggregation/list_source_overrides.rb
=> FileSet deletion monkey patch

app/views/press_catalog/index.html.erb, spec/features/press_catalog_search_spec.rb, spec/features/press_catalog_spec.rb
=> search results have a distinct page title

app/controllers/press_catalog_controller.rb, app/views/catalog/_facets.html.erb, ruumba/.ruumba.yml, spec/features/press_catalog_facets_spec.rb
Hide open access facet when there are no open access titles.
=> has open access

app/presenters/hyrax/file_set_presenter.rb, spec/presenters/hyrax/file_set_presenter_spec.rb
=> verify image for static_image partial

app/views/e_pubs/show.html.erb
=> add new EPUB NOID; exclude Safari 14

app/controllers/e_pubs_controller.rb, app/presenters/hyrax/monograph_presenter.rb, app/views/monograph_catalog/_index_epub_toc.html.erb, config/settings/development.yml, config/settings/test.yml, spec/presenters/hyrax/monograph_presenter_spec.rb
=> disallow chapter downloads for certain BAR titles

app/assets/javascripts/application/cookie_alert.js.erb, app/views/shared/_brand_press_banner.html.erb, app/views/shared/_cookie_alert.html.erb, app/views/shared/_eula_press_banner.html.erb, app/views/shared/_survey_modal.html.erb, app/views/shared/_survey_nonmodal.erb, config/initializers/session_store.rb
=> set secure flag on cookies

app/assets/stylesheets/embed/embed_styles.scss, app/presenters/concerns/embed_code_presenter.rb, spec/presenters/concerns/embed_code_presenter_spec.rb
=> visual descriptions for embedded videos

app/jobs/email_counter_report_job.rb, spec/jobs/email_counter_report_job_spec.rb, spec/mailers/counter_report_mailer_spec.rb
=> HELIO-3703 Fixes a bug in the admin dashboard counter4_br2 report

.circleci/.force_rebuild, .circleci/config.yml, .travis.yml, Gemfile, Gemfile.lock, app/presenters/hyrax/file_set_presenter.rb, bin/setup_ci, config/database.yml.sample, solr/config/schema.xml, spec/controllers/press_catalog_controller_spec.rb, spec/presenters/hyrax/file_set_presenter_spec.rb, spec/spec_helper.rb
We're going to run circle and travis side-by-side for a while to evaluate them. Once we have done that, HELIO-3693 will be about removing one of them and making sure coveralls is working properly.
=> HELIO-3650 Add circle ci

Gemfile, Gemfile.lock, config.ru, config/application.rb, config/puma.rb, config/routes.rb, config/settings.yml
This is save to merge and deploy as is. After this is merged, monitoring specific changes to the deploy project can be made to start the monitoring process for each deploy.
=> HELIO-3388 Monitoring Puma web server with Prometheus and Grafana

app/controllers/api/v1/individuals_controller.rb, app/controllers/api/v1/institutions_controller.rb, app/views/api/v1/individuals/access.json.jbuilder, app/views/api/v1/institutions/access.json.jbuilder, config/routes.rb, spec/requests/api/v1/individuals_spec.rb, spec/requests/api/v1/institutions_spec.rb
Interface without backing a.k.a. no plumbing.
=> Resolves HELIO-3613 modify auth API

app/models/monograph_search_builder.rb
Tested on staging, this removes the extra queries.
=> HELIO-3707 remove N+1 featured rep queries from monograph_catalog

app/views/layouts/boilerplate.html.erb
=> no monitoring in dev

app/indexers/monograph_indexer.rb, spec/features/press_catalog_facets_spec.rb, spec/indexers/monograph_indexer_spec.rb
=> source facet for mps subpresses

fulcrum/accessibility.html
Resolves HELIO-3673
Update accessibility page with new information, revisions to make the text easier to read, new accessibility issue feedback form link, and changes to collection names (BAR).
=> HELIO-3673/update-accessibility

app/assets/stylesheets/application/heliotrope.scss
Resolves HELIO-3624 (re-opened, resolves recent comment)
Adjusts facet padding across Fulcrum to align collapsible facets with legend.
=> HELIO-3624 - adjust facet padding 

lib/tasks/bar_csv_monograph_create_update.rake, spec/indexers/monograph_indexer_spec.rb, spec/presenters/hyrax/monograph_presenter_spec.rb
=> no space in bar_number identifier

app/jobs/institution_report_job.rb, app/services/institution_report_service.rb, spec/jobs/institution_report_job_spec.rb, spec/services/institution_report_service_spec.rb
This doesn't actually do anything, just moving things around/refactoring for HELIO-3701
=> HELIO-3719 Refactor InstitutionReportJob, add InstitutionReportService

app/services/royalty/usage_report.rb, spec/services/royalty/usage_report_spec.rb
More groundwork for HELIO-3701
=> HELIO-3720 create royalty usage reports by copyright holder

lib/pdf_ebook/publication.rb
=> another 'named destination' workaround

app/controllers/ebooks_controller.rb, app/services/sighrax.rb, spec/requests/ebooks_spec.rb, spec/services/sighrax_spec.rb
=> Remove Sighrax.policy helper method

app/models/sighrax/electronic_book.rb, app/models/sighrax/electronic_publication.rb, app/models/sighrax/portable_document_format.rb, spec/models/sighrax/electronic_book_spec.rb, spec/models/sighrax/electronic_publication_spec.rb, spec/models/sighrax/portable_document_format_spec.rb
Super class for epub, pdf, and mobi
=> Add Sighrax::ElectronicBook class

app/views/catalog/_view_type_group.html.erb, spec/features/monograph_catalog_search_spec.rb, spec/features/press_catalog_spec.rb
=> ARIA tab roles for gallery/list views

app/views/catalog/_facet_pagination.html.erb, spec/features/monograph_catalog_facets_spec.rb
=> Helio 3688/aria more facet modal

spec/factories/counter_reports.rb, spec/services/institution_report_service_spec.rb
Hopefully this time will do it....
=> HELIO-3737 fixing a spec for circleci

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss
Resolves HELIO-3698.
Re-orders MPS sub-presses to fall underneath MPS and adds CSS rules to sub-presses where MPS rules were more explicit.
=> HELIO-3698 - Fix MPS sub-press branding

lib/tasks/handles/fulcrum_dois.rake
* Also, this rake task now returns all books, not just published ones.
=> HELIO-3734 Include Fulcrum Title status in Fulcrum->TMM feed

app/controllers/api/opds/v2/feeds_controller.rb, config/routes.rb, spec/requests/api/opds/V2/feeds_spec.rb
=> HELIO-3738 Add OPDS collection feeds for leverpress, amherst

app/views/e_pubs/show.html.erb
=> add Nornes NOID

app/controllers/e_pubs_controller.rb, app/controllers/hyrax/admin/stats_controller.rb, app/models/monograph_search_builder.rb, app/services/status_page_service.rb, app/services/watermark/watermarkable.rb
Catching everything is usually a bad idea unless you are writing operating systems.
=> rescue StandardError => _e

spec/jobs/destroy_active_fedora_objects_job_spec.rb
Possible fix to ./spec/jobs/destroy_active_fedora_objects_job_spec.rb Ldp::Gone failure/error
=> Another attempt to fix Ldp::Gone Failure/Error

app/models/opds/publication.rb, spec/models/opds/publication_spec.rb
=> opds publication

Dockerfile, docker-compose.yaml
He said he was able to run test.  Sounds like a good place to start.
=> Noah's Docker Files

app/controllers/e_pubs_controller.rb, app/services/watermark/watermarkable.rb, app/views/monograph_catalog/_index_epub_toc.html.erb, spec/controllers/e_pubs_controller_spec.rb, spec/requests/e_pubs_spec.rb
=> use chapter_index in Rails cache keys

app/controllers/e_pubs_controller.rb
=> chapter_index always nil in watermark_pdf for PDFs

app/controllers/fulcrum_controller.rb, app/models/anonymous.rb, app/models/user.rb, app/services/incognito.rb, app/views/fulcrum/_dashboard.html.erb, spec/models/anonymous_spec.rb, spec/models/user_spec.rb, spec/services/incognito_spec.rb
Incognito.developer? method to allow developers to toggle a flag in production to verify behaviors before releasing to the general public.
=> Incognito Developer?

app/controllers/fulcrum_controller.rb, app/models/user.rb, app/policies/e_pub_policy.rb, app/policies/ebook_download_operation.rb, app/policies/ebook_operation.rb, app/policies/ebook_reader_operation.rb, app/policies/entity_policy.rb, app/services/incognito.rb, app/views/fulcrum/_dashboard.html.erb, spec/models/user_spec.rb, spec/policies/e_pub_policy_spec.rb, spec/policies/ebook_download_operation_spec.rb, spec/policies/ebook_operation_spec.rb, spec/policies/ebook_reader_operation_spec.rb, spec/policies/entity_policy_spec.rb, spec/services/incognito_spec.rb
Replace product product intersection with license_for? in EPubPolicy and EnittyPolicy
=> First step to integrating licenses into EPubPolicy and EntityPolicy

app/controllers/api/v1/individuals_controller.rb, app/controllers/api/v1/institutions_controller.rb, app/views/api/v1/individuals/license.json.jbuilder, app/views/api/v1/institutions/license.json.jbuilder, config/routes.rb, spec/requests/api/v1/individuals_spec.rb, spec/requests/api/v1/institutions_spec.rb
To be merged into release_2_72_2 branch. See notes in HELIO-3711.
=> HELIO-3613 Add licenses to auth API

app/controllers/e_pubs_controller.rb, app/controllers/grants_controller.rb, app/controllers/monograph_catalog_controller.rb, app/controllers/press_catalog_controller.rb, app/models/press_search_builder.rb, app/policies/actor_agent_resolver.rb, app/policies/e_pub_policy.rb, app/services/counter_service.rb, app/services/sighrax.rb, app/views/grants/_form.html.erb, app/views/grants/index.html.erb, config/settings/development.yml, config/settings/test.yml, spec/models/anonymous_spec.rb, spec/models/user_spec.rb, spec/policies/actor_agent_resolver_spec.rb, spec/policies/e_pub_policy_spec.rb, spec/presenters/pdf_ebook_presenter_spec.rb, spec/presenters/press_presenter_spec.rb, spec/services/sighrax_spec.rb
Add the world institution to the actor agent resolver to enable "free" to read products behavior by creating a grant that associates a read license with the world institution and the target product.
=> World institution

app/policies/e_pub_policy.rb, app/policies/ebook_interval_download_operation.rb, app/policies/ebook_operation.rb, app/presenters/e_book_download_presenter.rb, app/views/monograph_catalog/_index_epub_toc.html.erb, spec/policies/ebook_interval_download_operation_spec.rb, spec/presenters/e_book_download_presenter_spec.rb
First iteration of ebook download operations with developer? guard clause.
=> Ebook Interval Download Operation Policy

app/policies/ebook_download_operation.rb, app/policies/ebook_interval_download_operation.rb, app/policies/ebook_operation.rb, spec/policies/ebook_download_operation_spec.rb, spec/policies/ebook_interval_download_operation_spec.rb, spec/policies/ebook_operation_spec.rb
Upgrade ebook download operations with more checks: unrestricted?, acessible_online?, and accessible_offline?
=> ebook download operations upgrade

app/policies/ability_helpers.rb, app/policies/ebook_download_operation.rb, app/policies/ebook_interval_download_operation.rb, app/policies/ebook_operation.rb, spec/policies/ability_helpers_spec.rb, spec/policies/ebook_download_operation_spec.rb, spec/policies/ebook_interval_download_operation_spec.rb
Role checks using cancan ability via Sighrax calls.
=> Use Sighrax to check platform_admin and ability_can

app/policies/entity_policy.rb, app/policies/resource_download_operation.rb, spec/policies/entity_policy_spec.rb, spec/policies/resource_download_operation_spec.rb
Refactoring of Entity Policy's download? method.
=> Resource download operation

app/views/e_pubs/show.html.erb
=> add Anderson NOID

app/models/ability.rb, app/policies/ability_helpers.rb, app/policies/e_pub_policy.rb, app/policies/ebook_download_operation.rb, app/policies/ebook_interval_download_operation.rb, app/policies/ebook_reader_operation.rb, app/policies/resource_download_operation.rb, spec/policies/ability_helpers_spec.rb, spec/policies/e_pub_policy_spec.rb, spec/policies/ebook_download_operation_spec.rb, spec/policies/ebook_interval_download_operation_spec.rb, spec/policies/ebook_reader_operation_spec.rb, spec/policies/resource_download_operation_spec.rb
EPubPolicy refactoring and CanCanCan can? :edit to can? :update bug fix.
=> ebook read operation upgrade

config/settings/development.yml, config/settings/test.yml
allow_read_products from dev and test yaml files
=> HELIO-3843 remove bar_disallow_chapter_downloads_list and

app/models/sighrax/score.rb, spec/system/monograph_catalog_epub_toc_spec.rb, spec/system/monograph_catalog_pdf_ebook_toc_spec.rb
=> Fix system specs after HELIO-3613 work

app/controllers/e_pubs_controller.rb, app/jobs/unpack_job.rb, app/views/monograph_catalog/_index_epub_toc.html.erb, spec/controllers/e_pubs_controller_spec.rb, spec/requests/e_pubs_spec.rb
HELIO-3783 follow-up PR
this is already in production as release `2.73.2`
=> Hotfix/helio 3783/epub chapters follow up

app/models/ability_checkpoint.rb, app/policies/ability_helpers.rb, app/policies/resource_download_operation.rb, app/presenters/hyrax/score_presenter.rb, app/services/sighrax.rb, spec/controllers/e_pubs_controller_spec.rb, spec/models/ability_checkpoint_spec.rb, spec/policies/ability_helpers_spec.rb, spec/policies/resource_download_operation_spec.rb, spec/services/sighrax_spec.rb
Replace ability helper CanCanCan with user roles.
=> HELIO-3857 Publisher admin unable to read draft ebook

lib/tasks/quality_control/qc_csv_heb.rake
=> add EPUB FeaturedRepresentative creation date

.gitignore, app/models/monograph_search_builder.rb, app/models/press_search_builder.rb, spec/features/external_resource_icons_spec.rb, spec/features/facets/sections_spec.rb, spec/features/monograph_catalog_facets_spec.rb, spec/models/monograph_search_builder_spec.rb
=> monograph search builder

app/views/e_pubs/show.html.erb
Tested and working on preview.
=> HELIO-3821 Turn hypothes.is on for Amherst Press

.rubocop_todo.yml, app/overrides/combine_pdf/pdf_overrides.rb, app/services/watermark/watermarkable.rb, spec/controllers/e_pubs_controller_spec.rb, spec/requests/e_pubs_spec.rb
=> Helio 3810/pdf metadata watermark

Gemfile, Gemfile.lock
Deployed to testing and is working fine.
=> HELIO-3891 upgrade to puma 5

README.md, app/views/epub_search_logs/index.html.erb, app/views/fulcrum/_reports.html.erb
Also included turning the EpubSearchLog stats into a table for easier reading.
=> HELIO-3912 Simple Blacklight search stats reporting

db/migrate/20210602023727_add_fields_to_institutions.rb, db/schema.rb
=> add fields to institutions table

app/assets/javascripts/application/banner.js, app/helpers/banner_helper.rb, app/views/shared/_acceptable_use_policy_banner.html.erb, app/views/shared/_header.html.erb, config/locales/en.yml, spec/helpers/banner_helper_spec.rb
This is on staging, there are screenshots in the ticket.
=> HELIO-3905 Implement platform-wide Acceptable Use Policy prompt

app/assets/stylesheets/application/themes.scss
Adjust button color and container padded and sizing
=> HELIO-3935 - HEB Aboutware Fixes

app/assets/stylesheets/application/themes.scss
=> HELIO-3761 - Style FIA publisher

app/assets/stylesheets/application/themes.scss
Add a top margin for the acceptable use container on lever and amherst for correcting the dispaly of acceptable use policy banner
=> HELIO-3957 - Acceptable Use Policy Display for Lever and Amherst

fulcrum/feedback.html
Resolve HELIO-3934 - updates the accessibility feedback form to point to the main qualtrics form, which captures all feedback on the platform.
=> HELIO-3934 - update feedback page forms

lib/export/exporter.rb, lib/import/importer.rb
=> importer uses a single manifest CSV file

app/views/shared/_metadata.html.erb, spec/views/shared/_metadata.html.erb_spec.rb
=> HELIO-3951 Add citation_pdf_url meta tag for clients that can

app/jobs/unpack_job.rb
=> parent relationship may not yet exist

app/views/hyrax/file_sets/_media_embedded.html.erb
=> tombstoning should not affect embed views

spec/services/embed_code_service_spec.rb
=> add examples for multiple filenames and basenames

Gemfile, Gemfile.lock
I've run this on preview and the error is gone.
=> HELIO-3972 update sitemap_generator gem

app/controllers/monograph_manifests_controller.rb, lib/export/exporter.rb
This is already in production, just needs to be merged see HELIO-3975
=> Helio 3974/helio 3975/exporter encoding and include errors

app/services/embed_code_service.rb, spec/services/embed_code_service_spec.rb
HELIO-3992 adjust new/old epub embed timeout code
=> HELIO-3061 hold off on new dynamic epub unpack until end of august

app/views/fulcrum/_components.html.erb, app/views/fulcrum/_individuals.html.erb, app/views/fulcrum/_institution_affiliations.html.erb, app/views/fulcrum/_institutions.html.erb, app/views/fulcrum/_licenses.html.erb, app/views/fulcrum/_products.html.erb, app/views/fulcrum/_tokens.html.erb, app/views/fulcrum/_users.html.erb
I made this change manual on production and in the 2_79_1 branch.
=> Replace .filter with .filter_by in fulcrum partial views

app/controllers/fulcrum_controller.rb, app/jobs/license_to_grant_job.rb, app/views/fulcrum/_jobs.html.erb, app/views/fulcrum/_licenses.html.erb, spec/jobs/license_to_grant_job_spec.rb
Make sure each license has a corresponding grant.
=> Find or Create a grant for each license.

app/views/fulcrum/_components.html.erb, app/views/fulcrum/_dashboard.html.erb, app/views/fulcrum/_individuals.html.erb, app/views/fulcrum/_institutions.html.erb, app/views/fulcrum/_products.html.erb, app/views/greensub/components/show.html.erb, app/views/greensub/individuals/show.html.erb, app/views/greensub/institutions/show.html.erb, app/views/greensub/products/show.html.erb
Making it easier to delete greensub objects from the GUI.
=> Add delete button to greensub views

app/models/greensub/institution.rb, app/views/fulcrum/_dashboard.html.erb, spec/controllers/e_pubs_controller_spec.rb, spec/models/greensub/institution_spec.rb, spec/requests/api/v1/institutions_spec.rb, spec/requests/greensub/institutions_spec.rb
Enforce institution identifier to be an integer
=> Validate institution identifier is an integer

app/controllers/api/v1/licenses_controller.rb, app/models/greensub/component.rb, app/models/greensub/license.rb, app/models/greensub/product.rb, app/views/api/v1/licenses/_license.json.jbuilder, app/views/api/v1/licenses/index.json.jbuilder, app/views/api/v1/licenses/show.json.jbuilder, app/views/fulcrum/_dashboard.html.erb, app/views/greensub/licenses/index.html.erb, config/routes.rb, spec/factories/greensub/license_affiliations.rb, spec/models/greensub/component_spec.rb, spec/models/greensub/license_spec.rb, spec/models/greensub/product_spec.rb, spec/requests/api/v1/components_spec.rb, spec/requests/api/v1/licenses_spec.rb, spec/requests/api/v1/products_spec.rb, spec/requests/greensub/licenses_spec.rb
=> HELIO-3929 API Licenses

app/services/embed_code_service.rb, spec/services/embed_code_service_spec.rb
=> restrict EmbedCodeService using hostname

app/policies/ebook_operation.rb, spec/controllers/e_pubs_controller_spec.rb, spec/policies/ebook_operation_spec.rb, spec/presenters/e_book_download_presenter_spec.rb
Remove protective if developer? guard statement around license_for?
=> HELIO-3929 Remove if actor.developer? guard statement

app/assets/stylesheets/application/heliotrope.scss, app/controllers/monograph_catalog_controller.rb, app/views/monograph_catalog/purchase.html.erb, config/routes.rb
Monograph Catalog Purchase View
=> Resolves HELIO-3795 Create purchase partial/view

app/controllers/utilities_controller.rb, app/jobs/fixity_job.rb, app/mailers/fixity_mailer.rb, app/views/fixity_mailer/send_failures.html.erb, app/views/fixity_mailer/send_failures.text.erb, spec/jobs/fixity_job_spec.rb, spec/mailers/fixity_mailer_spec.rb
HELIO-4008 FixityJob reporting
=> HELIO-4011 Fix FixityJob

app/views/e_pubs/_cozy_controls_bottom.html.erb, app/views/e_pubs/_webgl_specific.html.erb, app/views/e_pubs/show.html.erb
Add linking for Tombs from text to WebGL
Reposition 3D Model and Database buttons in EReader -- position them AFTER the TOC button
Allow for 3D Model panel text to reflect the correct title and DOI of the Volume
=> HELIO-3635 - Gabii Vol 2 WebGL Extensions

app/controllers/fulcrum_controller.rb, app/views/fulcrum/_jobs.html.erb
=> LicenseDeleteJob no longer exist, remove fulcrum dashboard reference.

app/services/embed_code_service.rb, spec/services/embed_code_service_spec.rb
=> use iframe embed codes for audio and video

app/jobs/fixity_job.rb, app/mailers/fixity_mailer.rb, app/views/fixity_mailer/send_failures.html.erb, app/views/fixity_mailer/send_failures.text.erb, spec/jobs/fixity_job_spec.rb, spec/mailers/fixity_mailer_spec.rb
This is an improvement to what's currently in production. It's also completely isolated in it's own job and is currently running successfully on preview so is safe to merge. If we need to make more adjustments, we'll make a new ticket.
=> HELIO-4038 More FixityJob improvements

app/overrides/hydra/derivatives/processors/video/hydra_derivatives_processors_video_processor_overrides.rb, app/views/hyrax/file_sets/media_display/_video.html.erb, app/views/hyrax/file_sets/media_display_embedded/_video.html.erb, spec/hydra-derivatives/processors/video_spec.rb
=> increase video derivative bitrate, favor mp4

app/views/monograph_catalog/_index_monograph.html.erb, app/views/press_catalog/_index_gallery.html.erb, app/views/press_catalog/_index_list.html.erb
=> allow markdown in creator_display; fix aria-labels

app/models/featured_representative.rb, app/models/sighrax/audiobook_ebook.rb, app/models/sighrax/monograph.rb, app/presenters/concerns/featured_representatives/file_set_presenter.rb, app/presenters/concerns/featured_representatives/monograph_presenter.rb, app/presenters/e_book_download_presenter.rb, app/services/sighrax.rb, app/services/tmm/file_service.rb, config/locales/heliotrope.en.yml, lib/tasks/tmm/tmm_upload_monograph_representatives.rake, spec/models/featured_representative_spec.rb, spec/models/sighrax/audiobook_ebook_spec.rb, spec/models/sighrax/null_enitty_spec.rb, spec/presenters/e_book_download_presenter_spec.rb
=> add 'audiobook' representative (for download only)

app/views/monograph_catalog/_index_monograph.html.erb, spec/views/monograph_catalog/index.html.erb_spec.rb
=> overall toolbar conditional matches its contents

app/services/counter_service.rb, lib/tasks/temporary/remove_staff_from_counter.rake, spec/services/counter_service_spec.rb
And remove staff from counter_reports
=> HELIO-4090 Filter staff and monitoring from counter_reports

app/assets/javascripts/application/short_monograph_description.js, app/views/monograph_catalog/_index_monograph.html.erb
=> prevent Monograph description 'more' link by NOID

app/models/concerns/heliotrope_mime_types.rb, spec/jobs/create_derivatives_job_spec.rb, spec/models/file_set_spec.rb
=> add support for M4V videos

lib/tasks/temporary/remove_staff_from_counter.rake
=> HELIO-4090 Restrict to only removing rows on or after 2021-07-01

app/controllers/monograph_catalog_controller.rb, spec/features/edit_file_set_spec.rb
=> don't show resources' date_published

app/views/webgls/_tab.html.erb, app/views/webgls/show.html.erb
add paragraph handle for volume 2 and modify language in dialog box based on input from gabii team
=> HELIO-4014 - Paragraph handle for Volume 2

app/views/e_pubs/_cozy_controls_bottom.js.erb, app/views/e_pubs/_webgl_specific.js.erb, app/views/e_pubs/show.html.erb
=> store WebGL "a11y_on" state in local storage

app/assets/stylesheets/application/themes.scss
adjust transcript heading for audio and video captions in EBC
=> HELIO-4123 - Transcript heading not visible for EBC

app/assets/stylesheets/application/heliotrope.scss, app/views/press_catalog/index.html.erb
remove negative top margin on results container and adjust placement of search and browse books in partial
=> HELIO-3474 - fixup display

lib/tasks/file_set_replacement/replace_files.rake
=> ensure the wrong FileSet is not swapped

app/controllers/monograph_catalog_controller.rb, app/controllers/score_catalog_controller.rb, app/overrides/hyrax/file_sets_controller_overrides.rb, app/presenters/hyrax/score_presenter.rb, app/services/stats_graph_service.rb, app/views/hyrax/file_sets/_attribute_rows_orphan_fileset.erb, app/views/hyrax/file_sets/_attributes.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/score_catalog/_index_score.html.erb, spec/features/edit_file_set_spec.rb, spec/services/stats_graph_service_spec.rb, spec/views/hyrax/file_sets/show.html.erb_spec.rb, spec/views/monograph_catalog/index.html.erb_spec.rb
=> deactivate stats tabs while retaining related code

app/models/press_search_builder.rb, spec/models/press_search_builder_spec.rb
=> use date_created as default sort for michigan

app/assets/stylesheets/application/themes.scss, app/views/e_pubs/_webgl_specific.js.erb
=> only enable WebGL close button when EPUB is loaded

config/sitemap.rb
=> Helio 4132/remove covers from sitemaps

yarn.lock
=> upgrade CSB for CSB-253

app/controllers/press_catalog_controller.rb
This is experimental and the feature is switched on only with the developer flag active.
=> HELIO-3479 Display "More >>" items in filters within the filter box

fulcrum/_includes/footer.html
Update copyright year in footer to 2022
=> FULCRUMOPS-86 - update copyright year in fulcrum aboutware

app/services/royalty/calculation_report.rb, app/services/royalty/reportable.rb, app/services/royalty/usage_report.rb
Documentation has also been updated in Confluence.
=> HELIO-4066 No more Box for royalty reports

app/presenters/concerns/common_work_presenter.rb, config/authorities/licenses.yml, config/authorities/rights_statements.yml
=> remove inactive QA values due to Hyrax bug

app/overrides/hyrax/downloads_controller_overrides.rb, app/overrides/hyrax/file_set_derivatives_service_overrides.rb, app/views/hyrax/file_sets/media_display/_audio.html.erb, app/views/hyrax/file_sets/media_display/_video.html.erb, app/views/hyrax/file_sets/media_display_embedded/_audio.html.erb, app/views/hyrax/file_sets/media_display_embedded/_video.html.erb, spec/hydra-derivatives/processors/video_spec.rb
=> no more OGG and WEBM derivatives

lib/e_pub/cfi.rb, lib/e_pub/search.rb
the rest of the results; don't just bail on all of them.
=> HELIO-4085 If one search result fails, just skip it but still return

app/presenters/concerns/embed_code_presenter.rb, app/views/hyrax/file_sets/_media_embedded.html.erb, app/views/hyrax/file_sets/media_display_embedded/_audio.html.erb, spec/presenters/concerns/embed_code_presenter_spec.rb
=> fix logo on embedded audio interactive transcripts

app/jobs/attach_import_files_to_work_job.rb
=> further cleanup to enable re-running of failed job

app/controllers/api/v1/institutions_controller.rb, app/controllers/greensub/institutions_controller.rb, app/views/greensub/institutions/_form.html.erb, app/views/greensub/institutions/show.html.erb, db/migrate/20220125163308_two_logos_per_institution.rb, db/schema.rb, spec/factories/greensub/institutions.rb, spec/models/greensub/institution_spec.rb
=> horizontal and vertical logos for institutions

fulcrum/preservation.html
=> Helio 4137 preservation statement

app/views/hyrax/file_sets/media_display_embedded/_audio.html.erb
=> stop auto-adjusting height of audio embed iframes

lib/tasks/usage_reports/psi_report.rake
This is already in production so is fine to merge.
=> HELIO-4121 a couple of code fixes needed for the psi-report rake task

app/models/auth.rb, app/models/sighrax/monograph.rb, app/views/monograph_catalog/_access_options.html.erb
=> HELIO-4145 "other options" link goes to institution link resolver url

app/views/shared/_ga.html.erb
Fixes HELIO-4091 where we removed GA for preview by accident.
=> HELIO-4091 preview needs google analytcis

app/assets/stylesheets/application/themes.scss, app/views/e_pubs/_webgl_specific.js.erb, app/views/webgls/_tab.html.erb, app/views/webgls/show.html.erb
=> camera rotation bug after iframe mousedown event

app/views/hyrax/file_sets/media_display_embedded/_video.html.erb
=> caption position bug fix

app/views/layouts/boilerplate.html.erb, app/views/layouts/csb_too_viewer.html.erb, app/views/layouts/csb_viewer.html.erb, app/views/layouts/embedded.html.erb, app/views/layouts/mozilla-pdf-viewer.html.erb, app/views/shared/_hotjar.html.erb
This is working in preview and so should on production since it's essentially cut and paste with a different hjid. Will likely be refactored in the future as we get a better idea of how we want hotjar to behave.
=> HELIO-4177 don't load hotjar if cookies are denied

lib/tasks/tmm/tmm_csv_monograph_create_update.rake
=> map 'umasp' in Press column to 'asp' subdomain

app/assets/stylesheets/application/themes.scss, app/views/e_pubs/_webgl_specific.js.erb, package.json
Adds special note to Gabii 3D model panel; adds styles to help with Scroll mode mouse access to scrollbar.
=> HELIO-4169 - Gabii Scroll Default Mode

app/views/catalog/_search_sidebar.html.erb, app/views/shared/_brand_site_search.html.erb
This is paired with https://github.com/mlibrary/cozy-sun-bear/pull/255
=> HELIO-4197 HELIO-4198 changes for hotjar

app/views/shared/_hotjar.html.erb
This is working ok on preview, should be the same for prod.
=> HELIO-4209 do not use hotjar with proxy servers

app/jobs/handle_job.rb
Since it took me several minutes to understand what the HandleJob was doing (and I wrote the code) I thought it best to explicitly state what it is doing and the reasons why it is doing what it is doing.
=> Handle Job Comment

lib/tasks/metadata_editing/change_monographs_press.rake
=> task to change one or more Monographs' press

app/assets/stylesheets/mozilla-pdf-viewer/cozy-honey-bear-reader.css
=> Helio-4234/pdf toc style

spec/controllers/authentications_controller_spec.rb
Fixing a minor spec problem with the authentication controller
=> minor failing spec fix

fulcrum/preservation.html
=> Update link in preservation.html

lib/tasks/file_set_replacement/replace_covers_via_isbn.rake, lib/tasks/file_set_replacement/replace_epubs_via_isbn.rake, lib/tasks/file_set_replacement/replace_pdf_ebooks_via_isbn.rake
=> discard extra non-ISBN digits before lookup

app/controllers/counter_reports_controller.rb, app/views/counter_reports/unauthorized.html.erb, app/views/layouts/hyrax.html.erb
=> make COUNTER unauthorized page less confusing

app/presenters/hyrax/monograph_presenter.rb, app/views/monograph_catalog/_index_monograph.html.erb, config/locales/en.yml, spec/presenters/hyrax/monograph_presenter_spec.rb
=> format award metadata for display

app/models/press_search_builder.rb, spec/features/press_catalog_sort_spec.rb, spec/features/press_catalog_spec.rb, spec/models/press_search_builder_spec.rb
=> monographs use publication date as default sort

app/assets/javascripts/application/tabs.js
=> URL fragment activates associated Bootstrap tab

app/assets/stylesheets/application/heliotrope.scss
=> vertically align chapter download buttons

app/views/monograph_catalog/_index_monograph.html.erb
=> remove references to webgl and database tabs

app/controllers/featured_representatives_controller.rb, app/views/featured_representatives/_form.html.erb, config/routes.rb, spec/controllers/featured_representatives_controller_spec.rb
=> Helio 3210/unpack epub from show page

.circleci/.force_rebuild, app/overrides/hyrax/file_sets_controller_overrides.rb, config/locales/en.yml, spec/controllers/hyrax/file_sets_controller_spec.rb
=> HELIO-4279 fix reversioning with Hyrax 3

config/authorities/licenses.yml
=> add some older CC licenses, required by books

lib/tasks/metadata_editing/monographs_output_csv_by_press.rake
=> fix writable dir check; add file message

app/presenters/concerns/citable_link_presenter.rb, app/presenters/hyrax/monograph_presenter.rb, lib/tasks/handles/handles_publisher.rake, lib/tasks/quality_control/qc_csv_heb.rake, spec/indexers/monograph_indexer_spec.rb, spec/presenters/concerns/citable_link_presenter_spec.rb, spec/presenters/hyrax/monograph_presenter_spec.rb
=> namespace HEB ID and facilitate HEB handle cleanup

app/jobs/crossref_poll_job.rb, app/jobs/fixity_job.rb, app/jobs/open_access_ebook_trust_job.rb, app/jobs/recache_counter_robots_job.rb, lib/tasks/aptrust.rake, lib/tasks/cleanup/clean_cache.rake, lib/tasks/cleanup/remove_reversioned_derivatives.rake, lib/tasks/google_analytics/add_ga_history.rake, lib/tasks/google_analytics/ga_cache.rake, lib/tasks/handle.rake, lib/tasks/handles/fulcrum_dois.rake, lib/tasks/metadata_editing/monographs_output_csv_by_press.rake, lib/tasks/tmm/tmm_csv_monograph_create_update.rake, lib/tasks/tmm/tmm_upload_monograph_representatives.rake
=> add comment to code directly called from crons

app/assets/stylesheets/application/heliotrope.scss, app/presenters/concerns/citable_link_presenter.rb, spec/presenters/concerns/citable_link_presenter_spec.rb
=> full HEB ID in citable link box and citation

lib/tasks/handles/fulcrum_dois.rake
=> take path param and write output to a CSV file

app/controllers/hyrax/admin/stats_controller.rb, app/jobs/open_access_ebook_trust_job.rb, app/mailers/open_access_ebook_trust_mailer.rb, app/services/counter_reporter/report_params.rb, app/views/counter_reports/without_customer_id/master_view/_form.html.erb, config/environments/production.rb, spec/jobs/open_access_ebook_trust_job_spec.rb
HELIO-4281 Book_Segment error fix
HELIO-4297 add default email config
FULCRUMOPS-203 add counter defaults for open access ebook trust
HELIO-4291 don't use tempfile for OpenAccessEbookTrustJob
=> HELIO-4282, HELIO-4283 add counter defaults

app/assets/stylesheets/application/heliotrope.scss, app/views/epub_ebooks/_cozy_controls_bottom.html.erb, app/views/epub_ebooks/_cozy_controls_nomodal.html.erb, app/views/epub_ebooks/_cozy_controls_notes.html.erb, app/views/epub_ebooks/_cozy_controls_tools.html.erb, app/views/epub_ebooks/_cozy_controls_top.html.erb, app/views/epub_ebooks/_cozy_pdec_notes.html.erb, app/views/epub_ebooks/show.html.erb, app/views/layouts/csb_too_viewer.html.erb, config/settings/development.yml, yarn.lock
Build a custom ereader for PdeC with custom features to support the forthcoming Lever Press title. This is a work in progress and does not resolve HELIO-3803 or other sub-tasks that are a part of that epic.
=> HELIO-3803 - PdeC EReader

app/controllers/epub_ebooks_controller.rb, app/views/epub_ebooks/show.html.erb, config/application.rb, config/environments/test.rb, config/routes.rb, config/settings/development.yml, config/settings/test.yml
=> PdC: add map modal, set needed NOIDs automatically

config/sitemap.rb
=> skip tombstoned Monographs; allow for no FileSets

app/controllers/epub_ebooks_controller.rb, app/views/monograph_catalog/_index_monograph.html.erb, config/application.rb, config/environments/test.rb, config/routes.rb, spec/requests/e_pubs_spec.rb, spec/requests/epub_ebooks_spec.rb
=> move PdC NOID stuff out of config/routes

app/views/epub_ebooks/_cozy_controls_notes.html.erb, app/views/epub_ebooks/_cozy_controls_tools.html.erb, app/views/epub_ebooks/show.html.erb
Allow links to map that have a .pdec_location class to open the interactive map panel; typo in version display tools; cleanup and comment show page
=> HELIO-3803 - allow links to map to open the map overlay panel

app/assets/stylesheets/application/heliotrope.scss, app/views/epub_ebooks/_cozy_controls_bottom.html.erb, app/views/epub_ebooks/show.html.erb
Adds hypothes.is to new ereader
=> HELIO-3803 - Add hypothes.is annotation tool

app/jobs/open_access_ebook_trust_job.rb, spec/jobs/open_access_ebook_trust_job_spec.rb
=> HELIO-4291, FULCRUMOPS-203 allow dates to be set for the open access

app/services/heb_handle_service.rb, spec/services/heb_handle_service_spec.rb
=> service to calculate HEB handles

app/jobs/publish_job.rb, spec/jobs/publish_job_spec.rb
=> don't raise an error on missing monograph DOI

app/assets/stylesheets/application/heliotrope.scss
Resolves HELIO-4329
Adds styles for book information.
Turns out most of the changes required were in the EPUB itself, not with the app.
=> HELIO-4329 - Custom book metadata styling

app/views/epub_ebooks/_cozy_controls_notes.html.erb, app/views/epub_ebooks/_cozy_pdec_notes.html.erb
Resolves HELIO-3803
Update notes, definitions, trans notes, historical chara…cters; add functions for handling links to text in notes and trans notes
=> HELIO-3803 - Update Notes panel

package.json, yarn.lock
This is running on preview
CSB-271
HELIO-4015
=> update webpack-dev-server; update csb

lib/tasks/backup_monographs.rake
=> rake task to back up all Monographs to tarballs

app/services/watermark/watermarkable.rb
=> use persisted dir in app tmp for watermarking

yarn.lock
=> update CSB for CSB-275

app/jobs/aptrust_deposit_job.rb, app/services/aptrust/service.rb, spec/services/aptrust/service_spec.rb
Tested with the new credentials and seems to work fine.
=> HELIO-4322 update APtrust API usage to V3

lib/tasks/fedora_download_fixer.rake
=> Fedora download issue 'fix' task for cron

Gemfile, Gemfile.lock
*Updates resque from 2.2.1 to 2.4.0
=> HELIO-4367 Fix redis deprecation warning

app/indexers/file_set_indexer.rb, app/indexers/monograph_indexer.rb, app/presenters/hyrax/monograph_presenter.rb, lib/export/exporter.rb, lib/metadata_fields.rb, lib/tasks/metadata_editing/edit_objects_output_csv.rake, lib/tasks/metadata_editing/edit_objects_via_csv.rake, lib/tasks/tmm/tmm_csv_monograph_create_update.rake, spec/lib/export/exporter_spec.rb, spec/presenters/hyrax/monograph_presenter_spec.rb, spec/services/crossref/file_set_metadata_spec.rb, spec/services/crossref/monograph_metadata_spec.rb
=> export metadata from Fedora not Solr

app/jobs/open_access_ebook_trust_job.rb
I've already run this in production and it's working.
=> HELIO-4388 OpenAccessEbookTrustJob tempfile grabage collection bug

.gitignore, app/jobs/psi_report_job.rb, app/presenters/hyrax/monograph_presenter.rb, config/psi_sftp.yml.sample, lib/tasks/usage_reports/psi_report.rake, spec/jobs/psi_report_job_spec.rb
This will need a cron added after release. The sftp config is staged to be released on the next production deploy.
=> HELIO-4361 changes to the PSI report

lib/tasks/file_set_replacement/heb_fixed_layout_epub_replacer.rake
=> task to replace HEB fixed-layout EPUBs with PDFs

app/jobs/handle_job.rb, app/services/heb_handle_service.rb, spec/jobs/handle_job_spec.rb, spec/services/heb_handle_service_spec.rb
=> automatic HEB handles created nightly

fulcrum/_includes/footer.html
changes copyright year to 2023
=> update copyright year to 2023

app/services/heb_handle_service.rb, spec/services/heb_handle_service_spec.rb
HELIO-4395
already in production as hot fix release `3.9.1`
=> account for tokenization with extra wildcards

app/presenters/hyrax/file_set_presenter.rb, app/views/hyrax/file_sets/_form.html.erb, app/views/hyrax/file_sets/_side_by_side_layout.html.erb, lib/metadata_fields.rb, spec/lib/export/exporter_spec.rb, spec/lib/import/importer_spec.rb, spec/presenters/hyrax/file_set_presenter_spec.rb
=> HELIO-4391 align article_creator usage to creator

app/views/hyrax/file_sets/_form.html.erb, config/locales/en.yml
=> HELIO-4393 fieldset and spiel for journal resources

app/views/monograph_catalog/_index_epub_toc.html.erb
=> HELIO-4245 (follow-up) control location of browser tag fixups

app/views/monograph_catalog/_index_epub_toc.html.erb
=> HELIO-4399 handle nested final interval correctly

lib/tasks/cleanup/clean_cache.rake
=> HELIO-4398 keep RIIIF base images for images extant in Solr

app/views/e_pubs/show.html.erb
HELIO-4405 (reverts HELIO-3350)
=> HELIO-4405 remove Safari 13 scroll-mode hack for video embeds

app/indexers/monograph_indexer.rb, spec/indexers/monograph_indexer_spec.rb
=> HELIO-4397 index missing date_published with date_uploaded

fulcrum/accessibility.html
ABC signatory text was already in the file, I have no idea why it is not showing on master branch currently deployed to preview.
=> remove link to issues; make sure ABC signatory text is on page

app/overrides/hyrax/downloads_controller_overrides.rb, app/overrides/hyrax/file_sets_controller_overrides.rb
=> HELIO-4409 don't hit Fedora for IrusAnalytics parent id

app/models/opds/publication.rb, app/views/shared/_ga4.html.erb, fulcrum/accessibility.html, spec/requests/api/opds/V2/feeds_spec.rb
This is in production as 3.10.1
=> 3.10.1/ga4 bug fix

app/models/concerns/heliotrope_universal_metadata.rb, spec/models/file_set_spec.rb, spec/models/monograph_spec.rb
=> HELIO-4402 automatically set date_published on save

app/controllers/greensub/products_controller.rb, app/models/greensub/product.rb, app/views/greensub/products/_form.html.erb, app/views/greensub/products/_product.json.jbuilder, app/views/greensub/products/index.html.erb, app/views/greensub/products/show.html.erb, db/migrate/20230203203704_add_needs_kbart_and_group_key_to_product.rb, db/schema.rb
Should probably have @jgmorse verify that adding these fields won't cause any problems for greensub
=> HELIO-4407 add needs_kbart and group_key to product

app/assets/stylesheets/application/themes.scss
Resolves FULCRUMOPS-272
Adds custom styles for ICMC
=> FULCRUMOPS-272 - add styles for ICMC

app/assets/stylesheets/application/heliotrope.scss, app/forms/hyrax/monograph_form.rb, app/models/concerns/heliotrope_universal_metadata.rb, app/views/monographs/edit_fields/_date_published.html.erb, config/locales/en.yml, spec/features/create_monograph_spec.rb, spec/forms/hyrax/monograph_form_spec.rb, spec/models/file_set_spec.rb, spec/models/monograph_spec.rb
=> HELIO-4403 expose date_published to UI edit form

lib/tasks/backup_monographs.rake
=> HELIO-4396 rename the backup tar files of deleted Monographs

app/models/concerns/heliotrope_universal_metadata.rb, app/models/monograph.rb, lib/metadata_fields.rb, spec/models/monograph_spec.rb
=> HELIO-4413 copyright year: validate but don't pad

lib/import/row_data.rb, lib/metadata_fields.rb, spec/lib/import/row_data_spec.rb
=> remove newlines from titles on import

app/controllers/static_metadata_controller.rb, app/jobs/build_kbart_job.rb, app/views/static_metadata/index.html.erb, config/jekyll.yml, config/routes.rb, spec/jobs/build_kbart_job_spec.rb, spec/requests/static_metadata_spec.rb, spec/spec_helper.rb
Some of the functionality can be observed on https://heliotrope-testing.hydra.lib.umich.edu/products
=> HELIO-4408 KBART files

app/controllers/e_pubs_controller.rb, spec/controllers/e_pubs_controller_spec.rb
=> HELIO-4434 prevent 206 range requests over EZproxy

app/controllers/e_pubs_controller.rb, spec/controllers/e_pubs_controller_spec.rb
...those being 'barpublishing' and 'heliotrope'
HELIO-4434 - part 2
=> HELIO-4434 - part 2 - allow range requests under certain presses

fulcrum/_includes/analytics_ga4.html, fulcrum/_includes/head.html, fulcrum/assets/css/custom.scss, fulcrum/index.html
Adds GA4 support for fulcrum jekyll aboutware; 
Minor change for color of text on the homepage hero image;
=> FULCRUMOPS-322 - GA4 Support for Fulcrum Aboutware

Gemfile, Gemfile.lock
This was deployed to staging/newstaging and is fine.
=> HELIO-4445 update the skylight gem

app/assets/stylesheets/application/themes.scss
Resolves issues with header and footer display for ELT as a parent press.
=> FULCRUMOPS-156 - ELT fixes

app/presenters/hyrax/file_set_presenter.rb
=> HELIO-4447 file set presenter skylight instrumentation

lib/import/row_data.rb, lib/metadata_fields.rb, spec/lib/import/row_data_spec.rb
=> HELIO-4440 - allow old/alternate field names for importer

app/jobs/unpack_job.rb
=> HELIO-4451 change UnpackJob queue to :ingest

app/controllers/api/opds/v2/feeds_controller.rb, config/routes.rb, spec/requests/api/opds/V2/feeds_spec.rb
On preview, https://heliotrope-preview.hydra.lib.umich.edu/api/opds/heb
=> FULCRUMOPS-304 Add heb to the OPDS feed

app/jobs/recurring_usage_report_job.rb, app/mailers/recurring_usage_report_mailer.rb, app/views/recurring_usage_report_mailer/send_report.html.erb, app/views/recurring_usage_report_mailer/send_report.text.erb, config/settings/development.yml, config/settings/test.yml, spec/jobs/recurring_usage_report_job_spec.rb
This will require some configuration in production before release
=> HELIO-4416 BAR automated report

.gitignore, .wrap_conf/solr_dev, .wrap_conf/solr_test, README.md
allow git ignored .nvmrc file; 
bump solr stack minimum size; 
add step to heliotrope setup instructrions for webpacker creation of manifest.json file
=> Adjustments for local dev on MacOS M1/M2

app/controllers/press_catalog_controller.rb
Adds a publisher facet for bigten collection
=> HELIO-4469 - Publisher facet for bigten

lib/tasks/tmm/tmm_csv_monograph_create_update.rake
=> TMM CSV now contains non-EBC Monographs

app/controllers/api/opds/v2/feeds_controller.rb, app/models/opds/publication.rb, config/locales/en.yml, lib/tasks/handles/fulcrum_dois.rake, spec/models/opds/publication_spec.rb, spec/requests/api/opds/V2/feeds_spec.rb
HELIO-4481 OPDS 'ebc_backlist' changed to 'ebc_complete' 
HELIO-4480 OPDS typo in schema
FULCRUMOPS-331 Add 'michelt' to heliotrope:fulcrum_dois task
HELIO-4478 Change BAR EULA link
=> OPDS feed, fulcrum_dois rake task and BAR EULA link updates

.gitignore, Gemfile, Gemfile.lock, app/jobs/build_kbart_job.rb, config/fulcrum_sftp.yml.sample, spec/jobs/build_kbart_job_spec.rb
Tested on preview and the sftp config file is in the production deploys
=> HELIO-4435 SFTP generated KABRT files

Gemfile, Gemfile.lock
https://mlit.slack.com/archives/C1CC2MEGL/p1689097908563089
https://github.com/samvera/hyrax/pull/5961
=> HELIO-4486 follow-up: keep redlock < 2.0

lib/tasks/google_analytics/add_ga_history.rake, lib/tasks/google_analytics/ga_cache.rake
=> HELIO-4476 change comment to reflect reality

app/assets/images/exclamation-triangle-fill.svg, app/assets/stylesheets/common/heliotrope-content-warning.css, app/assets/stylesheets/embed/embed_styles.scss, app/views/hyrax/file_sets/_media.html.erb, app/views/hyrax/file_sets/_media_embedded.html.erb, spec/features/show_file_set_spec.rb
=> HELIO-4491 add FileSet media content warning

app/assets/javascripts/application_survey.js, app/views/shared/_survey_nonmodal_bigten.erb, app/views/shared/_survey_nonmodal_gabii.erb
=> HELIO-4495 - bug: non-modal surveys activating each other

lib/import/row_data.rb, spec/lib/import/row_data_spec.rb
=> HELIO-4497 - RowData manipulates CSV::Row objects not hashes

app/assets/images/box-arrow-up-right.svg, app/assets/stylesheets/application/heliotrope.scss, app/views/monograph_catalog/_index_epub_toc.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/monograph_catalog/_read_download_buy.html.erb, app/views/monograph_catalog/_read_download_buy_registration_required.html.erb, config/locales/en.yml, spec/views/monograph_catalog/index.html.erb_spec.rb
=> HELIO-4443 implement 'registration required to read/download'

app/views/monograph_catalog/_read_download_buy_registration_required.html.erb
HELIO-4443 follow-up, add some more mappings
=> add 4 more ISBN-to-Google-Form mappings

app/assets/stylesheets/application/heliotrope.scss
=> replace mistakenly-removed Leaflet image height

app/presenters/hyrax/file_set_presenter.rb, spec/presenters/hyrax/file_set_presenter_spec.rb
=> HELIO-4505 - content warning FileSets use svgicon thumbnails

lib/tasks/tmm/tmm_csv_monograph_create_update.rake
=> HELIO-4472 - don't create or edit Gabii Monographs (ISBN check)

lib/tasks/backup_monographs.rake
=> HELIO-4499 - send email if backup_directory not writable

app/controllers/e_pubs_controller.rb, config/routes.rb, lib/e_pub/chapter.rb, lib/e_pub/marshaller/pdf.rb, lib/e_pub/publication.rb, lib/pdf_ebook/publication.rb, lib/spec/e_pub/chapter_spec.rb, lib/spec/e_pub/marshaller/pdf_spec.rb, lib/spec/e_pub/publication_spec.rb, spec/controllers/e_pubs_controller_spec.rb, spec/requests/e_pubs_spec.rb
=> HELIO-4509 - dead code related to e-book chapter/ToC stuff

.gitignore, Gemfile, Gemfile.lock, config/firebrand_sftp.yml.sample, lib/tasks/tmm/tmm_csv_monograph_create_update.rake
HELIO-4513
deploy project has been updated
=> HELIO-4513 - pull CSV file from FTP

lib/tasks/handles/fulcrum_dois.rake
=> HELIO-4515 - upload DOI CSV to Firebrand's FTP server

Gemfile, Gemfile.lock
HELIO-4513 revision, see comment on issue
=> HELIO-4513 - remove unneeded gems related to net-ssh bug

app/overrides/hyrax/file_sets_controller_overrides.rb, spec/controllers/hyrax/file_sets_controller_spec.rb
=> HELIO-4512 - don't bounce non-editors from Gabii representatives

app/jobs/unpack_job.rb, app/overrides/hyrax/file_sets_controller_overrides.rb, spec/controllers/hyrax/file_sets_controller_spec.rb
=> HELIO-4520 - chmod custom thumbnail for Apache user/X-Sendfile

Gemfile, Gemfile.lock
Updating the irus_analytics gem in the Gemfile.
=> HELIO-4492 irus_analytics will not error on blank user_agents

app/assets/stylesheets/application/heliotrope.scss
=> HELIO-4524 stop video scrolling over fixed brand/nav bar

app/services/watermark/watermarkable.rb
=> HELIO-4530 bump watermarking timeout

app/controllers/e_pubs_controller.rb, app/services/counter_reporter/item_report.rb, app/services/counter_reporter/platform_report.rb, spec/controllers/e_pubs_controller_spec.rb, spec/services/counter_reporter/item_report_spec.rb, spec/services/counter_reporter/platform_report_spec.rb
=> HELIO-4541 turnaway/No_License hits should not be in other

app/jobs/aptrust_deposit_job.rb
=> HELIO-4548 write `bag-info.txt` after writing payload files 

Gemfile.lock
=> HELIO-4546 update bagit gem

app/services/aptrust/service.rb, spec/services/aptrust/service_spec.rb
=> HELIO-4545 sort/pagination for APTrust deposit verification

fulcrum/privacy.html
=> FOPS-445 update privacy policy

app/jobs/psi_report_job.rb, spec/jobs/psi_report_job_spec.rb
This is in production as 3.24.1
=> HELIO-4542 change where we sftp the PSI reports

app/jobs/attach_import_files_to_work_job.rb, spec/jobs/attach_import_files_to_work_job_spec.rb, spec/lib/import/importer_spec.rb, spec/services/tmm/file_service_spec.rb
=> HELIO-4552 - set FileSet group permissions

app/assets/stylesheets/application/themes.scss
fixing some styling with font sizes and colors
=> tweak styles for aperio

app/policies/ebook_download_operation.rb, app/policies/ebook_interval_download_operation.rb, spec/policies/ebook_download_operation_spec.rb, spec/policies/ebook_interval_download_operation_spec.rb
=> HELIO-4264 remove editor override for ebook/chapter downloads

config/locales/en.yml
=> HELIO-4563 - remove 'temporarily' from free title message

app/jobs/publish_job.rb, app/services/crossref/file_set_metadata.rb
=> HELIO-4551 - auto-DOI-creation vs publication race condition

app/policies/ebook_download_operation.rb, app/policies/ebook_interval_download_operation.rb, spec/policies/ebook_download_operation_spec.rb, spec/policies/ebook_interval_download_operation_spec.rb
HELIO-4568
reverses the bug-causing HELIO-4264
=> HELIO-4568 - undo changes from HELIO-4264

app/controllers/monograph_catalog_controller.rb, app/views/monograph_catalog/_read_download_buy.html.erb, spec/controllers/monograph_catalog_controller_spec.rb
=> HELIO-4564 - no Read button ever for draft ebook

app/assets/stylesheets/application/heliotrope.scss
Resolves [HELIO-4580.](https://mlit.atlassian.net/browse/HELIO-4580)
Restores the list and gallery view/display of resources on the monograph catalog.
=> HELIO-4580 - Fix Resource thumbnails and text layout 

spec/views/monograph_catalog/index.html.erb_spec.rb
HELIO-4564 small fix second PR
CircleCI was not running specs so this slipped through
=> HELIO-4564 (2) - fix view spec after HELIO-4564

Gemfile, Gemfile.lock, app/controllers/ebooks_controller.rb, app/presenters/concerns/common_work_presenter.rb, app/presenters/concerns/featured_representatives/monograph_presenter.rb, app/presenters/hyrax/file_set_presenter.rb, app/presenters/hyrax/monograph_presenter.rb, app/presenters/pdf_ebook_presenter.rb, app/presenters/remove_me_e_pub_interval_presenter.rb, app/services/watermark/watermarkable.rb, config/application.rb, config/initializers/riiif_initializer.rb, lib/e_pub/search.rb, lib/e_pub/snippet.rb, lib/pdf_ebook/publication.rb
HELIO-4582
Mystery problem with Hyrax 4.0.0 (Rails 6?) and Skylight breaks Monograph creation, and probably other things as well.
=> HELIO-4582 - temporarily disable skylight stuff

app/views/monograph_catalog/_index_monograph.html.erb, app/views/monograph_catalog/_read_download_buy.html.erb
See comments in [HELIO-4581](https://mlit.atlassian.net/browse/HELIO-4581)
=> HELIO-4581 fix monograph tombstone layout hyrax 4

app/assets/stylesheets/application/heliotrope.scss
=> HELIO-4583 - alert banner centering

app/views/monograph_catalog/_case_insensitive_sort_facet.html.erb, app/views/monograph_catalog/_custom_section_facet.html.erb, spec/features/monograph_catalog_facets_spec.rb
=> HELIO-4584 - remaining facet modal weirdness

app/assets/javascripts/mozilla-pdf-viewer.js
=> HELIO-4595 - hyrax 4 csb social links

app/assets/stylesheets/application/dashboard.scss, app/assets/stylesheets/application/heliotrope.scss, app/views/_masthead.html.erb, app/views/fulcrum/_sidebar.html.erb, app/views/fulcrum/index.html.erb, app/views/fulcrum/show.html.erb, app/views/shared/_brand_bar.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_my_actions.html.erb
Resolves HELIO-4592.
Fixes hyrax and fulcrum dashboards and associated navigation tools.
=> HELIO-4592 - Style Fulcrum Dashboard banner

app/controllers/presses_controller.rb, app/presenters/press_presenter.rb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/presses/_form.html.erb, db/migrate/20240215200557_add_show_irus_stats_to_press.rb, db/schema.rb, spec/presenters/press_presenter_spec.rb
=> HELIO-4605 - add press option to show/hide IRUS stats

app/views/monograph_catalog/_index_monograph.html.erb
=> HELIO-4602 - no Turbolinks caching of IRUS stats tab

app/assets/stylesheets/application/themes.scss
Resolves HELIO-4608
Tweak CSS to adjust buttons and svg icons for various presses still experiencing issues with button display.
=> HELIO-4608 - Minor CSS issues for rekihaku, NYU, UNCpress, um-pccn, seas with hyrax 4

app/views/hyrax/base/_guts4form.html.erb, app/views/hyrax/file_sets/_permission_form.html.erb, app/views/hyrax/file_sets/edit.html.erb
* minor cosmetic adjustment to permissions tab of file_set edit page
=> HELIO-4607 Fix tabs on edit pages

app/assets/stylesheets/application/themes.scss
Adds more specific CSS selectors for MPS presses.
=> HELIO-4608 - Fixup for CSS selectors

Gemfile, Gemfile.lock, app/controllers/ebooks_controller.rb, app/presenters/concerns/common_work_presenter.rb, app/presenters/concerns/featured_representatives/monograph_presenter.rb, app/presenters/hyrax/file_set_presenter.rb, app/presenters/hyrax/monograph_presenter.rb, app/presenters/pdf_ebook_presenter.rb, app/presenters/remove_me_e_pub_interval_presenter.rb, app/services/hyrax/default_middleware_stack.rb, app/services/watermark/watermarkable.rb, config/application.rb, config/initializers/riiif_initializer.rb, lib/e_pub/search.rb, lib/e_pub/snippet.rb, lib/pdf_ebook/publication.rb, spec/services/hyrax/default_middleware_stack_spec.rb
This is on testing, https://heliotrope-testing.hydra.lib.umich.edu/heliotrope where monographs were created, updated. FileSets created, update, deleted. Actors seem ok. Skylight "testing" seems ok too, https://oss.skylight.io/app/applications/oqG7ugxMn2dL/recent/6h/endpoints
=> HELIO-4589 skylight in hyrax 4

app/assets/stylesheets/application/themes.scss
=> HELIO-4622 re-hide access legend under bigten

app/assets/stylesheets/application/hyrax.scss, app/views/hyrax/uploads/_js_templates.html.erb
=> HELIO-4591 fix missing file upload progress bars

app/assets/javascripts/hyrax/save_work/uploaded_files.es6
=> HELIO-4585 fix file upload diabling Monograph save

app/assets/javascripts/application_survey.js, app/views/e_pubs/show.html.erb, app/views/monograph_catalog/_read_download_buy.html.erb, app/views/monograph_catalog/index.html.erb, app/views/shared/_survey_modal_aberdeenunipress.html.erb, app/views/shared/_survey_nonmodal_aberdeenunipress.erb
HELIO-4625: Adds AUP's Open Access Survey
=> HELIO-4625 - add aup specific survey pages; modify js to display aup survey

app/views/monograph_catalog/_index_epub_toc.html.erb, spec/views/monograph_catalog/index.html.erb_spec.rb
=> HELIO-4619 toc entries should only link when authed

app/views/monograph_catalog/_index_monograph.html.erb, spec/views/monograph_catalog/index.html.erb_spec.rb
=> HELIO-4575 press analysts get a read link on draft Monographs

.circleci/config.yml, config/application.rb
=> HELIO-4624 - Node 17+ SSL workaround; Node 20 for CircleCI

app/views/e_pubs/show_pdf.html.erb
Resolves the PDF reader display of oa survey reader for AUP.
=> HELIO-4625 - add aup survey to pdf reader

app/views/e_pubs/_survey_oa.html.erb, app/views/e_pubs/show.html.erb, app/views/e_pubs/show_pdf.html.erb
=> HELIO-4637 - partial for OA survey logic

yarn.lock
=> CSB-277 - no continuous scroll for Mittell (9781643150611)

app/controllers/press_catalog_controller.rb, app/views/press_catalog/index.html.erb
=> HELIO-4642 simplify results-count-based facets switch

app/controllers/application_controller.rb, app/controllers/monograph_catalog_controller.rb, app/controllers/press_catalog_controller.rb, app/models/auth.rb, app/models/sighrax/publisher.rb, app/overrides/hyrax/file_sets_controller_overrides.rb
* auth_for only gets press noids once on press catalog
* catalog#facet does not use auth_for
=> HELIO-4636 speed up catalog pages

app/controllers/application_controller.rb, app/controllers/e_pubs_controller.rb, app/controllers/monograph_catalog_controller.rb, app/controllers/press_catalog_controller.rb, app/helpers/facets_helper.rb, app/models/auth.rb, app/models/sighrax/publisher.rb, app/overrides/hyrax/file_sets_controller_overrides.rb, app/services/dlps_institution.rb, app/services/dlps_institution_affiliation.rb, app/views/catalog/_facets.html.erb, app/views/monograph_catalog/_index_gallery_file_set.html.erb, app/views/monograph_catalog/_index_list_file_set.html.erb, app/views/monograph_catalog/_thumbnail_list_file_set.html.erb, app/views/press_catalog/_index_gallery_monograph.html.erb, app/views/press_catalog/_index_list_monograph.html.erb, app/views/press_catalog/index.html.erb, config/initializers/heliotrope_authority.rb, lib/devise/strategies/keycard_authenticatable.rb
This is in production as release 4.1.1
=> 4.1.1 branch

app/views/monographs/edit_fields/_buy_url.html.erb, spec/features/create_monograph_spec.rb
=> HELIO-4536 buy_url should use single-valued widget

app/models/auth.rb
=> HELIO-4644 memoize Auth.actor_authorized?

spec/requests/api/opds/V2/feeds_spec.rb
so we should not have tests for that.
=> HELIO-4653 OPDS feeds with no publications no longer validate

app/views/hyrax/base/_form.html.erb, spec/features/create_monograph_spec.rb
=> HELIO-4649 hide relationships tab

app/assets/stylesheets/application/heliotrope.scss, app/models/greensub/institution.rb, app/views/shared/_brand_press_auth.html.erb, spec/models/greensub/institution_spec.rb
=> HELIO-4213 - show institution logos

app/views/authentications/show.html.erb
=> HELIO-4661 - beware quotes in institution name

app/models/auth.rb
(the expensive part) once per book not once for each ToC entry.
=> HELIO-4644 Auth.actor_authorized? should only check authorization

app/views/hyrax/file_sets/media_display/_interactive_application.html.erb, app/views/hyrax/file_sets/media_display_embedded/_interactive_application.html.erb
HELIO-3806 2nd PR (bug fix), this is in production already as release [4.3.1](https://github.com/mlibrary/heliotrope/releases/tag/4.3.1).
=> HELIO-3806 - do not set auto margin on JS apps

app/models/greensub/licensee.rb, app/views/greensub/components/index.html.erb, app/views/greensub/institutions/index.html.erb, app/views/greensub/products/index.html.erb
Fixes up some of the fulrum/greensub backend UIs
=> HELIO-4657 use distinct for Product ActiveRecord, not uniq

app/services/crossref/file_set_metadata.rb, spec/services/crossref/file_set_metadata_spec.rb
=> HELIO-4298 - point FileSet DOIs directly to show page

app/overrides/hyrax/file_sets_controller_overrides.rb, spec/controllers/hyrax/file_sets_controller_spec.rb
=> HELIO-4673 - FileSet show redirects to download with param

.gitignore, config/scholarlyiq.yml.sample, lib/tasks/scholarlyiq/scholarlyiq_upload_institutions.rake
=> HELIO-4669 - ScholarlyIQ institutions upload task

lib/tasks/scholarlyiq/scholarlyiq_upload_institutions.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_presses.rake
Fixed the occasional misspelling
=> HELIO-4668 presses for scholarlyiq

app/indexers/file_set_indexer.rb, app/indexers/monograph_indexer.rb, lib/tasks/scholarlyiq/scholarlyiq_upload_items.rake, spec/indexers/file_set_indexer_spec.rb, spec/indexers/monograph_indexer_spec.rb
=> HELIO-4627 - ScholarlyiQ items upload task and indexing

app/indexers/file_set_indexer.rb, app/indexers/monograph_indexer.rb, app/models/concerns/solr_document_extensions/monograph.rb, app/presenters/concerns/social_share_widget_presenter.rb, app/presenters/hyrax/file_set_presenter.rb, app/presenters/hyrax/monograph_presenter.rb, app/renderers/hyrax/renderers/multiline_attribute_renderer.rb, lib/export/exporter.rb, lib/import/row_data.rb, spec/lib/import/row_data_spec.rb, spec/presenters/concerns/social_share_widget_presenter_spec.rb
=> HELIO-4685 - improve/align newline removal regex

lib/tasks/scholarlyiq/scholarlyiq_upload_counter_reports.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_institutions.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_items.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_presses.rake
HELIO-4674
This has been running in production on a cron for a week already.
=> HELIO-4674 - Scholarly iQ tasks: add COUNTER, remove local file

lib/tasks/handles/doi_checker.rake
=> HELIO-4683 - a task to follow DOIs and output results

app/assets/stylesheets/application/heliotrope.scss, app/views/e_pubs/_cozy_controls_bottom.js.erb, app/views/e_pubs/show_pdf.html.erb
=> HELIO-2890 - add rotate clockwise button for PDFs

app/assets/stylesheets/mozilla-pdf-viewer/cozy-honey-bear-reader.css, app/views/e_pubs/show.html.erb, app/views/e_pubs/show_pdf.html.erb
=> HELIO-4690 - Add Altmetric badge to PDF reader

app/services/crossref/file_set_metadata.rb, spec/services/crossref/file_set_metadata_spec.rb
=> HELIO-4689 - add milliseconds to resource DOI timestamps

app/views/monograph_catalog/_read_download_buy.html.erb, spec/features/monograph_catalog_pdf_download_warning_spec.rb
=> HELIO-4687 - Watermarked PDF download warning for editors

lib/tasks/scholarlyiq/scholarlyiq_upload_counter_reports.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_institutions.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_items.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_presses.rake
=> HELIO-4695 - quote all fields in Scholarly iQ TSV files

Gemfile, Gemfile.lock, app/controllers/utilities_controller.rb, config/application.rb, config/environment.rb, config/environments/development.rb, config/environments/production.rb, config/initializers/riiif_initializer.rb, spec/features/press_catalog_facets_spec.rb
This is set up and deployed on staging and preview currently. In order to put it into production a couple of lines of code need to be added to the production deploy project's puma.rb
=> HELIO-4700 Add Semantic Logger

lib/tasks/scholarlyiq/scholarlyiq_upload_counter_reports.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_institutions.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_items.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_presses.rake
HELIO-4698
This also undoes the minor change from HELIO-4695, i.e. [this PR](https://github.com/mlibrary/heliotrope/pull/3668).
=> HELIO-4698 - squish (rm newlines) where apt; no force_quotes

config/sitemap.rb
It's maybe 2x faster now which is ok.
=> HELIO-4704 Attempt to speed up sitemap generation

app/controllers/monograph_catalog_controller.rb, app/models/concerns/actorable.rb, app/models/monograph_search_builder.rb, config/environments/development.rb, lib/tasks/usage_reports/high_traffic_report.rake
* also added some skylight instrumentation
=> HELIO-4710 rake task to show high traffic and allocation requests

app/presenters/concerns/common_work_presenter.rb, app/presenters/hyrax/monograph_presenter.rb
some performance issues with the FileSetController#show page in a later sprint.
=> HELIO-4728 Add skylight instrumentation in preperation for fixing

app/models/monograph_search_builder.rb, spec/models/monograph_search_builder_spec.rb
This filters out covers, representatives like epubs, tombstones and file sets with expired permissions just as it did before but without having to fetch every single fileset in a monograph.
=> HELIO-4710 Speed up monograph search builder (no ordered_members)

lib/tasks/scholarlyiq/scholarlyiq_upload_items.rake
=> HELIO-4747 - add isbn to SiQ items TSV

lib/tasks/tmm/tmm_csv_monograph_create_update.rake
=> HELIO-4743 - ignore TMM dupe 'array' values (in e.g. subjects)

app/controllers/e_pubs_controller.rb, spec/requests/e_pubs_spec.rb
=> HELIO-4716 - remove share link ebook NOID check

app/forms/hyrax/monograph_form.rb, app/views/hyrax/monographs/_attribute_rows.html.erb, config/locales/en.yml, lib/metadata_fields.rb, spec/features/create_monograph_spec.rb, spec/forms/hyrax/monograph_form_spec.rb, spec/lib/export/exporter_spec.rb
=> HELIO-4731 - enable keyword field storage on Monographs

lib/tasks/scholarlyiq/scholarlyiq_upload_items.rake
=> HELIO-4753 - add primary_isbn column

lib/tasks/tmm/tmm_csv_monograph_create_update.rake
=> HELIO-4769 - replace ampersand entity; rm unused include

lib/tasks/tmm/tmm_csv_monograph_create_update.rake
=> HELIO-4772 - align input CSV encoding and comment with reality

fulcrum/accessibility.html
Fulcrum accessibility page updated with timeline activities, 3 principles, and other outdated information.
=> FOPS-674 - update accessibility page

app/forms/heliotrope/file_set_edit_form.rb, app/views/hyrax/file_sets/_form.html.erb, spec/features/edit_file_set_spec.rb
=> HELIO-4782 - add identifier to file_set edit form

app/overrides/hyrax/file_sets_controller_overrides.rb, spec/features/edit_file_set_spec.rb
=> HELIO-1606 - no admin override on FileSet page download button

spec/services/embed_code_service_spec.rb
=> HELIO-4788 - add assertion for unembeddable YouTube videos

app/jobs/marc_ingest_job.rb, app/services/marc/local_file_handler.rb, app/services/marc/sftp.rb, app/services/marc/validator.rb, spec/jobs/marc_ingest_job_spec.rb, spec/services/marc/sftp_spec.rb, spec/services/marc/validator_spec.rb
Tested on preview with live data, seems to be working ok.
=> HELIO-4785 marc records with no match in fulcrum can be retried

app/assets/stylesheets/application/heliotrope.scss, app/overrides/hyrax/file_sets_controller_overrides.rb, app/views/hyrax/file_sets/_thumbnail.html.erb, spec/controllers/hyrax/file_sets_controller_spec.rb
=> HELIO-4639 - rm thumbnail derivative when using Hyrax default

fulcrum/preservation.html
=> Fulcrumops 588 preservation stmt

app/presenters/hyrax/monograph_presenter.rb
rm method related to long-gone Flot stats graphs
=> rm method related to long-gone Flot stats graphs

app/presenters/hyrax/file_set_presenter.rb, spec/controllers/hyrax/downloads_controller_spec.rb, spec/helpers/breadcrumbs_spec.rb
=> HELIO-4815 - remove unnecessary Solr call for parent doc

app/controllers/featured_representatives_controller.rb, app/indexers/file_set_indexer.rb, app/indexers/monograph_indexer.rb, app/jobs/attach_import_files_to_work_job.rb, app/presenters/hyrax/file_set_presenter.rb, app/presenters/hyrax/monograph_presenter.rb, lib/import/importer.rb, spec/features/show_file_set_spec.rb, spec/presenters/hyrax/monograph_presenter_spec.rb
=> HELIO-4728 - use Solr for prev/next resource links

app/controllers/application_controller.rb, app/controllers/monograph_catalog_controller.rb, app/models/monograph_search_builder.rb, app/overrides/hyrax/file_sets_controller_overrides.rb, app/presenters/hyrax/monograph_presenter.rb, app/views/e_pubs/_cozy_controls_top.js.erb, spec/features/monograph_catalog_visibility_spec.rb
=> HELIO-4814 - rm draft FileSets from results, fix share links

app/renderers/hyrax/renderers/attribute_renderer.rb, app/views/hyrax/file_sets/_attribute_rows_info.html.erb, spec/views/hyrax/file_sets/show.html.erb_spec.rb
=> HELIO-4816 - don't call parent.ordered_section_titles

app/presenters/concerns/embed_code_presenter.rb, spec/presenters/concerns/embed_code_presenter_spec.rb
Also related to HELIO-4196, CSB-273
=> HELIO-4812 lazy load embeds

fulcrum/_includes/footer.html
Resolves FULCRUMOPS-699, updates copyright year to 2025
=> FOPS-699 - update copyright year in fulcrum static pages to 2025

app/assets/stylesheets/application/themes.scss
Fixup on LPP styling of pagination buttons to meet WCAG color contrast requirements
=> FOPS-688 - minor adjustment to LPP pagination buttons

app/services/epub_accessibility_metadata_indexing_service.rb, spec/services/epub_accessibility_metadata_indexing_service_spec.rb
HELIO-4819 PR #2
As of 20240213, this is in production as release [4.15.2](https://github.com/mlibrary/heliotrope/releases/tag/4.15.2).
=> add accessibilityHazard; rm field pluralization

app/assets/stylesheets/mozilla-pdf-viewer/cozy-honey-bear-reader.css
=> HELIO-4832 - remove pdf.js viewer's 9px page border

app/controllers/presses_controller.rb, app/models/press.rb, app/views/presses/_form.html.erb, db/migrate/20250214181049_add_a11y_urls_to_press.rb, db/schema.rb, spec/models/press_spec.rb
=> HELIO-4831 - add two accessibility-related-URLs to presses

app/presenters/concerns/epub_accessibility_metadata_presenter.rb, app/presenters/hyrax/monograph_presenter.rb, spec/presenters/concerns/epub_accessibility_metadata_presenter_spec.rb
=> HELIO-4830 - add EpubAccessibilityMetadataPresenter

app/assets/stylesheets/application/heliotrope.scss
=> HELIO-4825 - wrap links that overflow

lib/tasks/backup_monographs.rake
=> HELIO-4828 - continue backup when .nfs files prevent cleanup

app/assets/stylesheets/application/heliotrope.scss
=> HELIO-4825 - PR #2 - use safer 'break-word' on links

app/views/monograph_catalog/_index_monograph.html.erb, spec/features/create_monograph_spec.rb
=> HELIO-4838 - show language on Monograph catalog page

app/presenters/concerns/epub_accessibility_metadata_presenter.rb, app/views/monograph_catalog/_accessibility_claims.html.erb, app/views/monograph_catalog/_index_epub_toc.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, config/features.rb, spec/presenters/concerns/epub_accessibility_metadata_presenter_spec.rb
=> HELIO-4829 - 'Accessibility Claims' tab for monograph catalog

app/controllers/press_catalog_controller.rb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/monograph_catalog/_read_download_buy_registration_required.html.erb, spec/features/monograph_catalog_press_specific_stuff_spec.rb, spec/features/press_catalog_facets_spec.rb
Hotfix branch for HELIO-484 and HELIO-4856
Already in production as [release 4.16.2](https://github.com/mlibrary/heliotrope/releases/tag/4.16.2)
=> HELIO-484 and HELIO-4856

app/indexers/monograph_indexer.rb, app/presenters/concerns/epub_accessibility_metadata_presenter.rb, spec/indexers/monograph_indexer_spec.rb, spec/presenters/concerns/epub_accessibility_metadata_presenter_spec.rb
=> HELIO-4857 - Ensure 'Accessibility Claims' tab is never empty

app/views/monograph_catalog/_accessibility_claims.html.erb, app/views/monograph_catalog/_index_epub_toc.html.erb
This is already in production as release [4.17.1](https://github.com/mlibrary/heliotrope/releases/tag/4.17.1)
=> HELIO-4863 - fix 'display full/partial ToC' behavior

app/views/hyrax/file_sets/_side_by_side_layout.html.erb, app/views/hyrax/file_sets/_stacked_layout.html.erb
=> HELIO-4865 - replace 'by' with new line in Monograph authorship

app/assets/stylesheets/application/heliotrope.scss, app/presenters/concerns/epub_accessibility_metadata_presenter.rb, app/presenters/press_presenter.rb, app/views/monograph_catalog/_accessibility_claims.html.erb, spec/presenters/concerns/epub_accessibility_metadata_presenter_spec.rb, spec/presenters/press_presenter_spec.rb
=> HELIO-4808 - 'request accessible copy' btn and a11y page link

yarn.lock
=> CSB-281 - use stored reader theme

lib/tasks/cleanup/remove_derivatives_of_deleted_file_sets.rake
=> HELIO-4834 - task to remove derivatives of deleted objects

app/assets/stylesheets/application/themes.scss, app/views/monograph_catalog/_accessibility_claims.html.erb, spec/features/monograph_catalog_accessibility_claims_tab_spec.rb
This is already in production as [hot fix release v4.18.2](https://github.com/mlibrary/heliotrope/releases/tag/4.18.2)
FOPS-736
HELIO-4880
=> FOPS-736,  HELIO-4880 (hot-fix branch)

app/views/layouts/mozilla-pdf-viewer.html.erb
=> HELIO-4843 - add lang attribute to PDF reader

fulcrum/terms.html
Resolves FOPS-784, adds sentence about potentially objectionable materials and links to library policy.
=> FOPS-784 - Update Terms of Service

lib/tasks/handles/fulcrum_dois.rake
=> HELIO-4895 - add livedplaces to fulcrum_dois.rake

app/presenters/concerns/embed_code_presenter.rb, spec/presenters/concerns/embed_code_presenter_spec.rb
=> HELIO-4894 - limit height taken by embedded portrait videos

config/database.yml.sample, db/schema.rb
@conorom there are notes in [HELIO-4851](https://mlit.atlassian.net/browse/HELIO-4851) about updating development to match the collation/charset.
=> HELIO-4851 schema.rb collation and charset changes

yarn.lock
=> CSB-287: add label to text resize slider

app/controllers/press_catalog_controller.rb, app/views/monograph_catalog/_index_monograph.html.erb, lib/tasks/tmm/tmm_csv_monograph_create_update.rake, spec/features/monograph_catalog_press_specific_stuff_spec.rb
=> HELIO-4878 - add bigten collections facet

app/views/monograph_catalog/_index_monograph.html.erb
=> HELIO-4900 - no 'Accessibility Claims' tab for tombstones

app/assets/stylesheets/application/heliotrope.scss, app/views/epub_ebooks/show.html.erb
=> HELIO-4887 - remove Hypothesis from 'La Princesse de Cleves'

app/assets/stylesheets/application/heliotrope.scss, app/controllers/presses_controller.rb, app/presenters/concerns/epub_accessibility_metadata_presenter.rb, app/presenters/press_presenter.rb, app/views/monograph_catalog/_accessibility_claims.html.erb, app/views/presses/_form.html.erb, db/migrate/20250531171419_add_a11y_claims_bools_to_press.rb, db/schema.rb, spec/features/monograph_catalog_accessibility_claims_tab_spec.rb, spec/models/press_spec.rb, spec/presenters/concerns/epub_accessibility_metadata_presenter_spec.rb, spec/presenters/press_presenter_spec.rb
=> HELIO-4892 - add two boolean a11y claims fields to press table

app/controllers/monograph_catalog_controller.rb, app/views/monograph_catalog/_accessibility_claims.html.erb, app/views/monograph_catalog/_index_epub_toc.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/monograph_catalog/_read_download_buy.html.erb, spec/controllers/monograph_catalog_controller_spec.rb, spec/features/monograph_catalog_accessibility_claims_tab_spec.rb, spec/views/monograph_catalog/index.html.erb_spec.rb
HELIO-4913
Resolves HELIO-4909, HELIO-4910, HELIO-4911, HELIO-4912
=> HELIO-4913 - refactor ereader linking and dependent behavior

yarn.lock
=> CSB-283: add accessible font selection

fulcrum/assets/css/fulcrum_enhanced_display.css, yarn.lock
=> CSB-290 - add OpenDyslexic from cdnfonts

lib/tasks/quality_control/ebook_accessibility_remediation_report_by_press.rake
=> HELIO-4902 - output ebook remediation report per press

app/services/crossref/file_set_metadata.rb, spec/services/crossref/file_set_metadata_spec.rb
=> HELIO-4953 - use FileSet NOID in component DOI

fulcrum/accessibility.html
Updates HEB content section by adding link to HEB accessibility page. Please hold merging until I confirm these changes have been approved by HEB staff.
=> update accessibility page with links to HEB

app/controllers/e_pubs_controller.rb, app/services/counter_service.rb, db/migrate/20250825164357_add_book_segment_to_counter_reports.rb, db/schema.rb, spec/controllers/e_pubs_controller_spec.rb, spec/models/counter_report_spec.rb, spec/requests/e_pubs_spec.rb
=> HELIO-4956 - add book_segment to counter_reports

app/services/marc/local_file_handler.rb, spec/services/marc/local_file_handler_spec.rb
=> HELIO-4963 Better Exception handling for marc local_file_handler

lib/tasks/scholarlyiq/scholarlyiq_upload_book_segments.rake, lib/tasks/scholarlyiq/scholarlyiq_upload_counter_reports.rake
HELIO-4850 (ticket does not close)
=> HELIO-4850 - Add book_segments to SiQ TSV

lib/tasks/scholarlyiq/scholarlyiq_upload_items.rake
column, improve COUNTER Data Type mapping and
produce "fake" Book_Segment values for mobi and
audiobooks
=> HELIO-4845 - add counter_data_type column, revert_resource_type

lib/tasks/quality_control/accessibility_remediation/reader_ebook_accessibility_remediation_report_by_press.rake
=> FOPS-907: adjust (reader) ebook remediation report

lib/tasks/quality_control/accessibility_remediation/resource_file_sets_accessibility_remediation_report_by_press.rake
=> FULCRUMOPS-908 - Accessibility remediation report for resources
