app/controllers/catalog_controller.rb, app/forms/curation_concerns/monograph_form.rb, app/models/monograph.rb, app/views/curation_concerns/base/_form_additional_information.html.erb, config/locales/blacklight.en.yml
A first pass at #53. Adds initial Monograph metadata fields to the Monograph controller,
model, and to the catalog view and the create/edit form. Overrides
default labels of initial metadata fields with human readable labels.
=> Implement initial Monograph metadata fields

app/actors/curation_concerns/section_actor.rb, app/forms/curation_concerns/section_form.rb, spec/actors/curation_concerns/section_actor_spec.rb, spec/factories/file_sets.rb, spec/factories/sections.rb, spec/forms/curation_concerns/section_form_spec.rb
Previously the reorder file_sets UI was broken because it was attempting
to do a lookup for a monograph with a nil id.
=> Don't set monograph on a Section unless the id is present

config/curation_concerns.yml.sample
Moves minter-state from system /tmp which gets erased every boot
to project tmp subdirectory so minter-state will persist in development.
Also provides safer defaults for production settings for folks
who deploy directly from the repo without using capistrano.
=> Persist minter-state for development environments

app/actors/curation_concerns/section_actor.rb, app/forms/curation_concerns/section_form.rb, app/views/curation_concerns/sections/_form_supplementary_fields.html.erb, spec/actors/curation_concerns/section_actor_spec.rb, spec/forms/curation_concerns/section_form_spec.rb
Sections should have visibility controls the same ways monographs do. New sections will use this visibility, or if it doesn't have one, will default to the same visibility as it's monograph.
This resolves #81
=> Section access rights 81

app/actors/curation_concerns/section_actor.rb, spec/actors/curation_concerns/section_actor_spec.rb
=> Updating a section doesn't re-add it to monograph.ordered_members, #178

README.md, config/initializers/explain_partials.rb
Set the environement variable EXPLAIN_PARTIALS=true before
starting your rails server in development mode to have additional
comments included in your HTML source that show the file corresponding
to each partial being rendered.
Closes #198
=> Add code to list view partial sources in development mode

Gemfile, Gemfile.lock, config/routes.rb
Addresses the first acceptance criterion of #197. Only platform admins can access the resque-web console at /resque; other users currently get 500 errors. See also #207.
=> mount resque-web for platform admins

config/deploy/staging.rb
When deploying from a UM server to nectar this week, I continually ran into permission issues when cap wanted to read or write to `tmp` and other directories. I found you can set the umask in the cap config file: http://stackoverflow.com/questions/21465706/set-umask-for-remote-commands
It would be good if Seth and Conor could test this first before merging.
=> set umask in umich deploy to staging to allow for group read/write

app/actors/curation_concerns/section_actor.rb, app/forms/curation_concerns/section_form.rb, app/models/section.rb, app/views/curation_concerns/sections/_form_descriptive_fields.erb, spec/actors/curation_concerns/section_actor_spec.rb, spec/features/edit_section_spec.rb, spec/models/section_spec.rb, spec/presenters/curation_concerns/section_presenter_spec.rb
Makes the edit section page's monograph dropdown be set to the section's monograph.
Resolves #187
=> add the monograph's id to its section(s) for #187

app/assets/javascripts/application.js, app/assets/javascripts/file_set_sort_date.js, app/assets/stylesheets/application.css, app/controllers/curation_concerns/file_sets_controller.rb, app/forms/heliotrope/forms/file_set_edit_form.rb, app/models/file_set.rb, app/views/curation_concerns/file_sets/_form.html.erb, spec/models/file_set_spec.rb
Resolves #200 
This enforces a sort_date format of YYYY-MM-DD, so it won't accept YYYY or YYYY-MM. Is that ok with everyone?
=> indexing sort_date for file_sets/assets, #200

app/controllers/downloads_controller.rb, app/presenters/curation_concerns/file_set_presenter.rb, app/views/curation_concerns/file_sets/media_display/_default.html.erb, app/views/curation_concerns/file_sets/media_display/_image.html.erb, app/views/curation_concerns/file_sets/media_display/_office_document.html.erb, app/views/curation_concerns/file_sets/media_display/_pdf.html.erb, app/views/curation_concerns/file_sets/show.html.erb, spec/controllers/downloads_controller_spec.rb, spec/factories/file_sets.rb, spec/presenters/curation_concerns/file_set_presenter_spec.rb, spec/rails_helper.rb
For #287, this works for images, office docs and pdfs but not video or audio.
=> maybe disable downloads based on metadata, #287

app/controllers/catalog_controller.rb, app/forms/curation_concerns/monograph_form.rb, app/models/monograph.rb, app/models/solr_document.rb, app/presenters/curation_concerns/monograph_presenter.rb, app/views/curation_concerns/monographs/_form_additional_information.html.erb, app/views/curation_concerns/monographs/_form_required_information.html.erb, config/locales/blacklight.en.yml, config/locales/en.yml, spec/features/create_file_set_spec.rb, spec/features/create_monograph_spec.rb, spec/forms/curation_concerns/monograph_form_spec.rb
Closes #253 
* Adds multi value ISBN fields to monograph to capture different format ISBNs
* alters labels for primary creator, contributor, press
* removes source and publisher field
=> updates to monograph metadata/edit UI

app/assets/javascripts/application.js, app/assets/javascripts/disable_video_download.js, app/assets/stylesheets/heliotrope.scss, app/views/curation_concerns/file_sets/media_display/_video.html.erb
Disabling `src` attribute on multiple `source` elements resulted in undesirable behavior -- mainly the video not loading for playback. Instead of removing the `src` attribute, I've disabled the right click, which is at least something we can show NW to gauge their level of comfort. 
I would venture to guess that with right-click disabled and no "download" button on the page, we're effectively preventing download for 90-95% of users.
There is also a side fix in here that makes the video player responsive and sizes it to the width of the asset column.
=> Disable right click over video elements

app/services/markdown_service.rb, spec/services/markdown_service_spec.rb
I'm not 100% sure we even need to be removing p tags like this.
Jon's styles seem to handle any mess or extra space with the extra <p> tags right now except in headings.
Would it be better to handle those with styling?
=> Preserve markup newlines 352

app/controllers/catalog_controller.rb, spec/features/monograph_catalog_search_spec.rb
Resolves #358 
Not every single indexed field is added to the default search. This PR addresses primary use cases. We can add more fields to the default search as needed.
=> add default search fields

app/assets/javascripts/application.js, app/assets/javascripts/short_monograph_description.js, app/assets/stylesheets/heliotrope.scss, app/controllers/monograph_catalog_controller.rb, app/views/catalog/_document.html.erb, app/views/monograph_catalog/_document_list.html.erb, app/views/monograph_catalog/_index_file_set.html.erb, app/views/monograph_catalog/_index_header_list_file_set.html.erb, app/views/monograph_catalog/_thumbnail_file_set.html.erb, app/views/monograph_catalog/index.html.erb, config/locales/blacklight.en.yml
Closes #330 
Removes, re-labels, and re-orders facets; removes unneeded metadata fields in document index (we only want description); adds custom styles to control display and re-orders document partials; creates a new js function to limit monograph descriptions greater than 500 characters; removes link to section show page
=> modify monograph catalog ui to look like elderberry wireframes

db/migrate/20160506173307_create_sub_brands.rb, db/migrate/20160805201611_add_parent_to_sub_brands.rb, db/schema.rb
The sub brands table has a self referential foreign key.  The foreign key constraint is a requirement of active record associations belongs_to or has_one.  
Creating the table and the foreign key constraint all in one statement fails, because the target of the foreign key needs to exist first.  So, splitting up the create and adding foreign key constraints into sequential steps solves this problem and allows `db:migrate` to run on MySQL.
I have qualms about modifying an existing migration in place, because that means all the devs need to drop the db and rerun all the migrations.  On the other hand, it was a bad migration to begin with, so deleting it and making two more would also have necessitated dropping the db.  In short, blow away the db and start over after this PR is merged. …
=> Refactor migrations for sub brands table.

app/assets/javascripts/short_monograph_description.js, app/assets/stylesheets/application.css, app/assets/stylesheets/heliotrope.scss, app/assets/stylesheets/themes.scss, app/presenters/curation_concerns/file_set_presenter.rb, app/presenters/curation_concerns/monograph_presenter.rb, app/views/layouts/boilerplate.html.erb, app/views/press_catalog/_press_search.html.erb, app/views/press_catalog/index.html.erb, app/views/shared/_brand_bar.html.erb, app/views/shared/_brand_press_bar.html.erb, app/views/shared/_brand_press_jumbotron.html.erb, app/views/shared/_header.html.erb, app/views/shared/_press_branding.html.erb, app/views/shared/_site_search.html.erb, config/locales/curation_concerns.en.yml, spec/features/press_catalog_spec.rb
Closes #315 
In addition to modifying partials to bring the header, navigation, and press header inline with Elderberry wireframes, this PR:
- Introduces a class based approach to handle "press themes" in Fulcrum. 
- Search is removed from the top-level now and only available at the Press level and below.
- Maintains the parent press navigation at the Monograph and Asset level
=> Custom navbar to match Elderberry wireframes

app/assets/stylesheets/heliotrope.scss, app/presenters/curation_concerns/file_set_presenter.rb, app/presenters/curation_concerns/monograph_presenter.rb, app/views/layouts/curation_concerns.html.erb, app/views/shared/_brand_press_footer.html.erb, app/views/shared/_brand_press_jumbotron.html.erb, app/views/shared/_footer.html.erb, db/migrate/20160811101311_add_press_url_to_presses.rb, db/schema.rb, db/seeds.rb
Resolves #314 
NOTE: adds a new column `press_url` to the `presses` table to capture the presses url (ie http://www.press.umich.edu).  So you will need to run:
`bundle exec rake db:migrate`
then
`bundle exec rake db:seeds`
to populate the updated presses table.
TODO: @sethaj I can't figure out how to get the press logo (`logo_path`) and the press url (`press_url`) into the presenters for the monograph and asset, or what the best way to go about doing this is (probably don't need to be indexed in solr, do they?). The footer design looks for the press logo and url and inserts them in the footer if they exist.
=> add custom footer at the press, monograph, and asset level

solr/config/schema.xml
units -> distanceUnits makes solr 6 happy.
The units parameter name was deprecated in  solr 5.5 and removed in 6.0.
=> Update solr config for solr6 compatibility.

app/assets/stylesheets/themes.scss, app/controllers/press_catalog_controller.rb, app/views/catalog/_press_results.html.erb, app/views/press_catalog/_document_list.html.erb, app/views/press_catalog/_index_header_list_monograph.html.erb, app/views/press_catalog/_thumbnail_monograph.html.erb, app/views/press_catalog/index.html.erb, db/seeds.rb
Closes #384 
Creates a press results set to work with the press catalog page. Modifies the display of the list of monographs on a press catalog page to only include book cover, title, author, a description of the book, and a link to the monograph page. Stubs out a place to later include 4 "featured" assets.
This PR also rewrites db/seeds, enabling it to either create OR update entries in the presses database when running `bundle exec rake db:seed`
=> Press catalog

app/views/curation_concerns/file_sets/show.html.erb
Closes #397 
On asset pages, the parent monograph's title is italicized.
=> add emphasis tags around the monograph title on an asset show page

db/seeds.rb
Resolves #414 
We want the default presses to be different in production and development/test. We'll use seeds.db for this for now, with the possibility of moving to some other process in the future.
=> running db:seed in production should be different than in dev/test #414

lib/tasks/sample_iiif_urls.rake
This relates to #400 (testing riiif to make sure there are no memory problems)
=> rake task to generate urls to stress test riiif and netpbm

app/views/shared/_brand_bar.html.erb, app/views/shared/_brand_press_bar.html.erb, app/views/shared/_brand_press_footer.html.erb, app/views/shared/_footer.html.erb
Closes #405 
if not logged in, a login link is in footer
if logged in, site actions (create monograph, etc.) are in the header and for consistency, a logout link is in the footer.
=> move login link from header to footer 

app/views/curation_concerns/file_sets/_attribute_rows_technical.html.erb
=> 435 Removed file name from view of asset tech info

app/views/layouts/boilerplate.html.erb
Resolves #436 Remove markdown from asset page title.
=> 436 Remove markdown from asset page title

app/assets/stylesheets/heliotrope.scss, app/assets/stylesheets/themes.scss, app/views/curation_concerns/file_sets/_media.html.erb
monograph page: change font for section titles; 
asset page: add white space to metadata tabs, place media in figures with figcaption for more semantic markup, no italics for caption text that is styled italic
=> UI cleanup

app/helpers/press_helper.rb, app/views/layouts/boilerplate.html.erb, app/views/shared/_typekit.html.erb, db/migrate/20160830143512_add_typekit_id_to_presses.rb, db/schema.rb, db/seeds.rb
Resolves #434 
1) typekit loading now comes before other CSS and JS - dramatically reducing the FOUT (flash of unstyled font) time and ensuring the font is loaded completely; 
2) reuses press helpers to remove logic from views; 
3) mirror the pattern Seth created for storing Google Analytics IDs and store Typekit ID for a press in presses database
`bundle exec rake db:migrate` and `bundle exec rake db:seed` will need to be run for this to work.
=> refactor typekit 

app/views/curation_concerns/file_sets/_show_actions.html.erb
temporarily hide share button on asset page during the soft launch to prevent preview-heliotrope URLs from easily being shared.
=> remove share buttons for soft launch

.rubocop_todo.yml, app/controllers/downloads_controller.rb
Resolves #401 
This needs mod_xsendfile installed on Apache as well as some Apache config to work. What this means is iOS and Safari will be able to view video in production, staging, and preview, anywhere that has Apache in front of the app. This will not work for dev and test. iOS and Safari will not be able to view HTML5 video in dev and test.
=> add X-Sendfile header for videos, #401

app/models/monograph_search_builder.rb
Only 10 sections' worth of assets can get through with the default limit, less if some ordered_members are non-representative filesets attached directly to the monograph.
=> Solr's default results row limit is only 10

fulcrum/_includes/head.html, lib/tasks/jekyll.rake
adds special jekyll rake task for production deployment -- when deploying jekyll site to production, tell jekyll it is production using the deploy_production rake task;add google analytics tracking to jekyll pages if it environment is production
=> Jekyll rake task for production deployments

config/jekyll.yml
bug fix!
do not use extensionless permalinks for blog posts so that
https://www.fulcrum.org/blog/2016/06/30/year-one-report
becomes
https://www.fulcrum.org/blog/2016/06/30/year-one-report/
when generating the jekyll site
=> modify permalink structure for jekyll blog posts 

app/assets/stylesheets/heliotrope.scss, app/assets/stylesheets/themes.scss, app/views/curation_concerns/file_sets/_attribute_rows_permissions.html.erb, app/views/curation_concerns/file_sets/_form.html.erb
Closes #488 
By default, display the Holding Contact label on the asset show page
For the NW theme, do not show the Holding Contact label
Change the Holding Contact field in the asset edit form to a text area to allow for complex formatting of the Holding Contact text
=> Modify Holding Contact label on show and form

app/presenters/concerns/title_presenter.rb, app/presenters/curation_concerns/file_set_presenter.rb, app/presenters/curation_concerns/monograph_presenter.rb, app/presenters/curation_concerns/section_presenter.rb, app/services/markdown_service.rb, app/views/curation_concerns/file_sets/_show_actions.html.erb, app/views/curation_concerns/file_sets/show.html.erb, app/views/curation_concerns/monographs/show.html.erb, app/views/curation_concerns/sections/show.html.erb, app/views/layouts/boilerplate.html.erb, app/views/monograph_catalog/index.html.erb, config/application.rb, spec/controllers/monograph_catalog_controller_spec.rb, spec/presenters/concerns/title_presenter_spec.rb, spec/presenters/curation_concerns/file_set_presenter_spec.rb, spec/presenters/curation_concerns/monograph_presenter_spec.rb, spec/presenters/curation_concerns/section_presenter_spec.rb, spec/services/markdown_service_spec.rb
Created TitlePresenter concern and added concern to File_Set, Section,
and Mongraph Presenters.
=> Fixes #526 - Remove markdown in Twitter share link.

app/controllers/curation_concerns/sections_controller.rb, app/jobs/reindex_file_set_job.rb, spec/jobs/reindex_file_set_job_spec.rb
When a Section title is edited, we need to reindex all of it's file_sets since
we use the file_sets indexes section_title_tesim to build the Section facet
on the monograph_catalog page. Added a reindex_file_set_job that gets called
from by section_controller#update when a section's title(s) has changed.
=> Fixes #542. Changing a Section title should not break the Section facet.

app/views/curation_concerns/file_sets/_show_actions.html.erb
Very quick fix to ensure that markdown is removed from all share links that include a title.
=> use @presenter.page_title in all share links that include a title

.gitignore, Gemfile, Gemfile.lock, app/models/pageview.rb, app/presenters/curation_concerns/file_set_presenter.rb, app/services/analytics_service.rb, app/views/curation_concerns/file_sets/_attribute_rows_stats.html.erb, app/views/curation_concerns/file_sets/_attributes.html.erb, bin/setup, config/analytics.yml.sample, spec/models/pageview_spec.rb, spec/presenters/curation_concerns/file_set_presenter_spec.rb, spec/services/analytics_service_spec.rb
Much of this work has been lifted from Sufia, especially services/analytics_service.rb,
model/pageview.rb and their respective specs. But not all of the Sufia functionality
is carried over, there's no statistics.rb model for instance. There's no model for stats,
the service is just called directly from the presenter.
It might be that as demands for more complicated analytics functionality come in
we'll want to refactor and look for ways to manage that complexity. When that happens
it probably makes sense to look to Sufia and try to emulate more of what they've done.
Unless we get a plugin archetecture before that happens and can just include a GA gem(!)
NOTE: current developers should `cp config/analytics.yml.sample config/analytics.yml` to get tests to pass. For new installs this happens …
=> Resolves #256 google analytics pageviews for file_sets

Gemfile, Gemfile.lock, app/presenters/curation_concerns/file_set_presenter.rb, app/presenters/curation_concerns/monograph_presenter.rb, app/views/curation_concerns/file_sets/show.html.erb, spec/presenters/curation_concerns/monograph_presenter_spec.rb
You can now navigate the monograph's assets (file_sets) from the asset page using previous and next navigation buttons in the order they appear in the monograph.
=> Resolves #489: Ability to navigate next and previous from asset page.

.gitignore, .rubocop_todo.yml, app/models/pageview.rb, app/presenters/concerns/analytics_presenter.rb, app/presenters/curation_concerns/file_set_presenter.rb, app/presenters/curation_concerns/monograph_presenter.rb, app/views/monograph_catalog/index.html.erb, spec/features/create_file_set_spec.rb, spec/models/pageview_spec.rb, spec/presenters/concerns/analytics_presenter_spec.rb, spec/presenters/curation_concerns/file_set_presenter_spec.rb
Monograph pageviews include views of the monograph, any of the
monograph's file_sets and any searches of file_sets.
This has been tested in preview with live GA data and looks ok.
=> Resolves #560: Add google analytics pageviews to monographs

app/assets/stylesheets/heliotrope.scss, app/assets/stylesheets/themes.scss, app/helpers/press_helper.rb, app/views/shared/_brand_fulcrum_footer_block.html.erb, app/views/shared/_brand_press_footer.html.erb, app/views/shared/_brand_press_footer_block_a.html.erb, app/views/shared/_brand_press_footer_block_b.html.erb, app/views/shared/_brand_press_footer_block_c.html.erb, db/migrate/20161111093512_add_footer_blocks_to_presses.rb, db/schema.rb, db/seeds.rb
Resolves #594 
adds new fields to the presses database to input customized text (supports markdown) that is rendered in the footer if defined; abstracts out the footer into separate content blocks and renames css styles to reflect that renaming; adds presses database fields to press helper to make accessing these values easier in partials; 
will need to run `bundle exec rake db:migrate` and `bundle exec rake db:seed` to see changes in local and deployed instances.
=> enable a press to have customized text displayed in the footer

app/models/ability.rb, app/presenters/curation_concerns/section_presenter.rb, app/views/curation_concerns/file_sets/_show_actions.html.erb, app/views/curation_concerns/monographs/show.html.erb, app/views/curation_concerns/sections/show.html.erb, app/views/monograph_catalog/index.html.erb, app/views/roles/index.html.erb, spec/features/show_section_spec.rb, spec/models/ability_spec.rb, spec/presenters/curation_concerns/section_presenter_spec.rb
Resolves #322
Monograph edit buttons are available to press/platform admin
Resolves #181
Also made sure edit buttons are available for sections and file_sets.
Right now only press/platform admins can see/use them.
Press Admins can only create or update Monographs (not sections, file_sets).
We'll need to add some more stories about specific Press Admin permissions
for sections and file_sets.
=> Imported monographs are editable by press/platform admins

app/presenters/concerns/analytics_presenter.rb, app/views/monograph_catalog/index.html.erb
Should have seen this coming. We need to come up with a way to cache GA pageview (and other) stats.
This PR checks if we've hit the GA quota (it just catches the exception actually) for monograph_catalog and file_set pageview and creates a log entry if we're over the limit:
`E, [2016-11-17T11:13:07.463486 #6259] ERROR -- : Quota Error: profileId ga:126363248 has exceeded the daily request limit.`
On the monograph_catalog page, no pageview info is shown. On the file_set stats tab pageview shows as 0, although we haven't seen any quota problems with file_sets yet so it might not happen
We need to make a new story or two to come up with a better more sustainable way to show GA stats.
=> We're hitting GA quota limits on monograph_catalog pages.

app/views/monograph_catalog/index.html.erb
Until we figure out what is causing the monograph pageview stat to make so many requests that we're consistently over the GA quota, comment it out. Obviously something is wrong.
=> comment out monograph pageview

spec/actors/curation_concerns/section_actor_spec.rb, spec/features/catalog_search_spec.rb, spec/features/create_file_set_spec.rb, spec/features/create_section_spec.rb, spec/features/edit_section_spec.rb, spec/features/monograph_catalog_facets_spec.rb, spec/features/press_catalog_spec.rb, spec/lib/import/importer_spec.rb, spec/lib/import/monograph_builder_spec.rb, spec/models/file_set_spec.rb, spec/models/monograph_spec.rb, spec/spec_helper.rb
Reverts mlibrary/heliotrope#632
I merged the original PR, then realized it broke my dev environment, reverted, then realized it was really all my fault. Sigh. So, here's an "unrevert" to fix the fix that was never broken...
=> Revert "Revert "clean repo between each spec""

app/assets/stylesheets/heliotrope.scss
When I looked at what I originally wrote I wasn't happy with it -- Ultimately this doesn't change much of anything with the display of a video or image, but follows "best practices" for responsive video by also setting the height on `video` elements and ensures that widths do not get overridden.  I've also applied this technique to audio players and adjusted how the surrounding `figure` container width and displays are set.
=> refactor width for video, images, audio elements

app/views/curation_concerns/file_sets/_attribute_rows_info.html.erb, app/views/curation_concerns/file_sets/_attributes.html.erb, spec/features/create_file_set_spec.rb
Right now this is not an attribute renderer, that seems like overkill. We can change that if we need to in the future. There's javascript on the input field so that when you click it it's copied to your clipboard.
=> Resolves #590: Handle/DOI/Permalink should be (easily) copyable

app/presenters/concerns/analytics_presenter.rb, app/views/monograph_catalog/index.html.erb, lib/tasks/ga_cache.rake, spec/presenters/concerns/analytics_presenter_spec.rb
We're having problems with the google bot crawling the site so frequently
that it uses up our 50,000/day google analytics API quota. So we need to
cache it.
1. A rake task to cache google analytics data to the Rails.cache
2. Refactored the analytics_presenter to use the Rails.cache
When this is merged, add a cron in staging, preview and production to call the rake task to build the ga_cache. Something like:
`0 3 * * * cd /hydra-dev/heliotrope-staging/current; RBENV_ROOT=/l/local/rbenv RBENV_VERSION=2.3.0 RAILS_ENV=production /l/local/rbenv/bin/rbenv exec bundle exec rake heliotrope:ga_cache`
=> Resolves #634

app/assets/javascripts/application.js, app/assets/javascripts/ga_event_tracking.js, app/views/curation_concerns/file_sets/show.html.erb, app/views/monograph_catalog/index.html.erb, spec/features/create_file_set_spec.rb, spec/features/file_set_search_spec.rb, spec/features/monograph_catalog_facets_spec.rb, spec/features/monograph_catalog_search_spec.rb, spec/features/press_catalog_spec.rb
This is all done in javascript, similar to the old blacklight_google_analytics gem:
https://github.com/uohull/blacklight_google_analytics/blob/master/app/assets/javascripts/blacklight_google_analytics.js.erb
=> Resolves #481: add ga event tracking

spec/features/create_file_set_spec.rb, spec/features/monograph_catalog_facets_spec.rb, spec/rails_helper.rb
Don't run background jobs during specs if the specs aren't testing the outcome of the job. Part of story #673
=> Don't run unnecessary background jobs during specs.  Goal is to speed up specs, story #673

app/presenters/concerns/open_url_presenter.rb, spec/presenters/concerns/open_url_presenter_spec.rb
As per notes in #685, refactored this spec to use multi-valued fields instead of singular _or_ multi.
In the future we could change some of the `*_tesim` fields to `*_tesi` (so don't use `:stored_searchable`) to more faithfully match how the fields are stored in fedora, but it's not a big priority I don't think. I just didn't fully understand what was happening.
Resolves #685
=> Refactor this spec to be consistent with the app's solr index.

spec/controllers/monograph_catalog_controller_spec.rb, spec/features/monograph_catalog_sort_spec.rb
I rewrote the spec to create fewer FileSet records in fedora.
Before changes, the spec took 25-27 seconds on my laptop.
After changes, it takes 8-10 seconds.
=> Refactored a spec to speed it up. Story #673.

spec/features/monograph_catalog_facets_spec.rb
* For test setup, create the Monograph, Section, and FileSet records in
let blocks instead of creating them by interacting with the UI in the
body of the spec.  (Avoid extra routing and rendering work to speed up
the spec.)
* For specs that don't need admin-level access, don't log in with any
user.  (This change isn't for performance, but just to remove
unnecessary code.  You shouldn't have to be an admin user to view the
facets.)
On my laptop (without spring running), the specs in this file took about 38 seconds to run.  After these changes, they took about 27 seconds.
=> Story #673 Refactored the test setup on some specs to speed up the specs

fulcrum/index.html
Related to #879 
Modified fulcrum.org homepage to say "Edited by Una Chaudhuri and Holly Hughes"
=> add Edited By language to Chaudhuri title on Fulcrum homepage

app/controllers/e_pub_controller.rb, app/controllers/embed_controller.rb, app/controllers/monograph_catalog_controller.rb, spec/controllers/curation_concerns/file_sets_controller_spec.rb, spec/controllers/curation_concerns/monographs_controller_spec.rb, spec/controllers/e_pub_controller_spec.rb, spec/controllers/embed_controller_spec.rb, spec/controllers/monograph_catalog_controller_spec.rb
Ensures encountering a tombstone behavior is consistent with default CC behavior a.k.a. rescue from Ldp::Gone and raise CanCan::AccessDenied.
=> Resolves #955: Tombstone

db/seeds.rb, fulcrum/index.html
Resolves #958 
Adds penn state to homepage and adjusts `db/seeds.db` so penn state is created in production.
=> Add penn state to fulcrum homepage and production db

fulcrum/beta.html
FWIW, this fixup doesn't need to be deployed until the end of this sprint cycle.
=> change beta date to end in spring 2018

fulcrum/_sass/custom.scss, fulcrum/css/custom.css, fulcrum/index.html
Resolves #966 
Embeds the YT hosted version of the fulcrum video onto the fulcrum homepage; creates a class for responsive video on static pages; modifies language on homepage to reflect phases of project per CW request.
Released to production in 1.4.2.1
=> add fulcrum video and modify language before case studies

app/controllers/e_pub_controller.rb, app/views/press_catalog/_index_header_list_monograph.html.erb
Hyrax is appending "locale=lang" to all urls by default, so building urls using raw strings isn't going to work anymore.
It also turns out that "subdomin" is a reserved term by the rails url helpers, http://api.rubyonrails.org/v5.1/classes/ActionDispatch/Routing/UrlFor.html#method-i-url_for
so we'll use "publisher" as the param name.
=> Fixes #1017 'Read' link for epubs on the press catalog page

app/views/shared/_footer.html.erb
Changes footer to point to samvera.org and Samvera GitHub.
=> Resolves #974 Hydra to Samvera rebranding, redux.

.rubocop.yml, .rubocop_todo.yml, Gemfile, Gemfile.lock, app/jobs/application_job.rb, app/jobs/characterize_job.rb, app/jobs/publish_job.rb, app/models/press.rb, app/models/role.rb, app/models/sub_brand.rb, app/models/user.rb, spec/lib/import/importer_spec.rb
rubocop 0.49.1 has needed fix to rubocop 0.48.1 false positive for FileUtils.touch...
app/services/e_pub_service.rb:10:15: C: Rails/SkipsModelValidations: Avoid using touch because it skips validations.
FileUtils.touch(EPubService.epub_path(epub_id))
=> bundle update rubocop 0.49.1

config/initializers/hydra_config.rb
DEPRECATION WARNING: You must set 'config.user_key_field = Devise.authentication_keys.first' in your config/initializer/hydra_config.rb file. The default value will be removed in hydra-access-controls 12. (called from user_key_field at /usr/local/Cellar/rbenv/1.1.1/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hydra-access-controls-10.5.0/lib/hydra/config.rb:39)
=> config.user_key_field = Devise.authentication_keys.first

.gitignore, .rubocop.yml, Gemfile, Gemfile.lock, app/views/hyrax/file_sets/_attributes.html.erb, app/views/monograph_catalog/_index_header_list_file_set.html.erb, lib/tasks/ci.rake, ruumba/.ruumba.yml
By removing the following lines from the ./ruumba/.rummba.yml file
Style/NegatedIf:
Enabled: false
Style checks for negated if are enabled.
NOTE: Not everything in the .rummba.yml should be re-enabled since rummba strips all html before calling rubocop, hence context is lost and false positives are possible.
=> style negated if enabled

README.md, app/assets/javascripts/application/survey.js, app/assets/stylesheets/application/heliotrope.scss, app/views/hyrax/file_sets/show.html.erb, app/views/monograph_catalog/index.html.erb
Resolves #1092 
- adds survey info block to asset and monograph catalog views
- link to survey passes book or book and asset titles to the survey and is displayed on survey
- survey is hidden by default and shown only if a survey cookie does not exist
- cookie is registered if user closes survey info block or clicks survey button
- cookie length for taking survey is 30 days; cookie length for closing survey is 15 days
- fixed typo in README :)
=> add survey info block to asset and monograph catalog views

app/presenters/hyrax/monograph_presenter.rb, app/views/hyrax/file_sets/media_display/_image.html.erb, app/views/press_catalog/_thumbnail_list_monograph.html.erb
Monograph catalog page only tested via a hack because my dev machine is using placeholders instead of images for cover pages.
=> Addresses #821 cover images alt text.

app/indexers/monograph_indexer.rb, spec/indexers/monograph_indexer_spec.rb
Was using 'existing_fileset_order' which didn't include the recently added fileset.
Now using 'existing_filesets' which includes the recently added fileset.
=> Resolves #941: Monograph EPub indexing bug

app/services/e_pubs_search_service.rb, spec/controllers/e_pubs_controller_spec.rb
the requirements for doing that is CFI ranges which are added here.
This also fixes "more than on hit per DOM element" where before only
the first search term was returned for a DOM element, now all the search
terms/hits are returned.
=> Work towards resolving #1162, highlighting search terms in CSB. One of

README.md, db/seeds.rb
Updated README.md with Rails 5.x syntax.
Removed press.logo_path = entry["logo_path"] from seeds.rb.
=> Resolves #1195 Remove publisher logo stuff from db:seeds

vendor/assets/javascripts/ableplayer_turbolinks.js
It's always been like that. There are a bunch of CR line endings in the internationalization part of Able Player's code. Makes it annoying to edit.
=> fix mixed line endings

app/services/e_pubs_service.rb, spec/services/e_pubs_service_spec.rb
Almost perfect.   The unzip is monitored but it is still possible for readers to try to read a file before it is unzip.  In this instance the reader gets nothing and a file not found in epub is logged.  But much better than the previous state of affairs.
=> Resolves #1241: Unzip EPUB in the foreground

Gemfile, Gemfile.lock, app/views/e_pubs/show.html.erb
I've tested this with a couple of epubs (nyupress and an heb book) and it seems fine, but it can have the problem that CSB ticket 69 (which isn't done yet), https://github.com/mlibrary/cozy-sun-bear/issues/69, should solve.
I guess it doesn't matter if this is merged first, then CSB 69 is done, or the other way around.
=> Resolves #1264 Add EPUB navigation slider

app/controllers/analytics_controller.rb, app/models/pageview.rb, app/presenters/analytics_presenter.rb, app/presenters/concerns/cc_analytics_presenter.rb, app/presenters/hyrax/file_set_presenter.rb, app/presenters/hyrax/monograph_presenter.rb, app/views/analytics/show.html.erb, app/views/shared/_my_actions.html.erb, config/routes.rb, lib/tasks/ga_cache.rake, spec/controllers/analytics_controller_spec.rb, spec/presenters/concerns/cc_analytics_presenter_spec.rb, spec/presenters/hyrax/monograph_presenter_spec.rb, spec/views/analytics/show.html.erb_spec.rb, spec/views/shared/_my_actions.html.erb_spec.rb
This will probably not suffice to close the ticket, since I believe the intent is for press admins to be able to see analytics tailored for them.
Renamed concerns/analytics_presenter.rb to CCAnalyticsPresenter to avoid a naming conflict. That and my AnalyticsPresenter should probably be merged or refactored in some dramatically smarter way.
=> Addresses #1055 adding Analytics page for platform admins.

app/assets/stylesheets/application/heliotrope.scss, app/views/e_pubs/show.html.erb
Resolves #1337 
Adds a widget panel that includes a link to a Google Form. Form opens in a new window. In the future we may want something that does not take the user away from the application.
=> add a feedback panel to collect user feedback

app/assets/stylesheets/application/themes.scss
If I had my druthers I would not be using the !important CSS "feature" but oh well.
=> Addresses #1386 messed-up logged-in Penn State banner.

app/assets/stylesheets/application/heliotrope.scss, app/views/layouts/curation_concerns/catalog.html.erb, app/views/monograph_catalog/_index_epub.html.erb
Resolves #1416 
Renamed `.sidebar` to `.fulcrum_sidebar` to avoid inheriting hyrax dashboard class.
=> change sidebar class to fulcrum_sidebar to avoid hyrax conflicts

app/views/fulcrum/show.html.erb, app/views/layouts/boilerplate.html.erb, app/views/monograph_catalog/_index_epub.html.erb, app/views/shared/_header.html.erb, app/views/shared/_skip_links.html.erb
Resolves part 1 of #1409 
Moves skip link markup out of `app/views/layouts/boilerplate.html.erb` and to its own partial that is called on pages that use the navigation menu header (the idea of the skip link is to give keyboard users an option to skip tabbing through the navigation so this seems to make the most sense to me); 
Discovered EPUB monograph catalog show page was missing `maincontent` anchor -- this is added now;
As a result of moving skip links to their own partial, it is no longer included on the EPUB show page.
=> Remove skip link from EPUB show page

.rubocop_todo.yml, app/controllers/featured_representatives_controller.rb, app/indexers/monograph_indexer.rb, app/models/ability.rb, app/models/concerns/solr_document_extensions/monograph.rb, app/models/featured_representative.rb, app/models/monograph_search_builder.rb, app/presenters/hyrax/file_set_presenter.rb, app/presenters/hyrax/monograph_presenter.rb, app/views/featured_representatives/_form.html.erb, app/views/hyrax/base/_items.html.erb, app/views/hyrax/base/_member.html.erb, config/locales/hyrax.en.yml, config/routes.rb, db/migrate/20180109210107_create_featured_representatives.rb, db/schema.rb, spec/controllers/featured_representatives_controller_spec.rb, spec/factories/featured_representatives.rb, spec/indexers/monograph_indexer_spec.rb, spec/models/featured_representative_spec.rb, spec/models/monograph_search_builder_spec.rb, spec/models/solr_document_spec.rb, spec/presenters/hyrax/monograph_presenter_spec.rb
More work toward completing #1394. This provides some infrastructure but the display of the "database" and the "aboutware" is not included.
=> "featured representatives", tabs for monograph_catalog page

app/assets/stylesheets/application/themes.scss, app/views/e_pubs/show.html.erb
Resolves #1391 
Adds styles for branding Gabii. Assumes Gabii logo is named "gabii.png" and that Typekit ID has been placed in the publisher profile.
=> add style for gabii branding

app/controllers/application_controller.rb
Stole Roger's tweak from FishRappr and it seems to have resolved the issue.
Roger Espinosa [10:08]
Actually. We found (in fishrappr) that the code we took from DBD _was_ stripping too much for anonymous users.
Greg Kostin [10:11]
@roger Did you fix it in fishrappr?  If so, how?
Roger Espinosa [10:13]
I tweaked the `clear_session_user` method we borrowed.
Because it seemed that UMRDR was aggressively assuming you were going to log in.
=> Resolves #1580: Asset Link 422 Error

app/controllers/e_pubs_controller.rb, lib/e_pub/search.rb, lib/spec/e_pub/search_spec.rb, spec/controllers/e_pubs_controller_spec.rb
1) Searches are now cached (30 days expiration)
2) Search terms must be 3 characters or more
3) Regexes aren't allowed in search terms
=> Fixes #1459 (the search part). Addresses search performance issues:

app/models/guest.rb, app/models/user.rb, config/settings/development.yml, lib/devise/strategies/http_header_authenticatable.rb, spec/lib/devise/http_header_authenticatable_spec.rb, spec/models/guest_spec.rb, spec/models/user_spec.rb
Since we have to lock down the interface for friends accounts anyway I changed the header authentication code so it can create a new user that cannot be saved to the users table.
This side steps the issue of having to inform cosign users when they login to cosign they weren't logged in to the application because they are not in the user table.
Now all that is left is locking down the interface for authenticated users that have no role a.k.a. privileges.
=> Resolves #1591: Display pop-up for Co-Sign users

app/helpers/heliotrope/ability_helper.rb, app/views/shared/_add_content.html.erb, app/views/shared/_my_actions.html.erb, spec/views/shared/_add_content.html.erb_spec.rb, spec/views/shared/_my_actions.html.erb_spec.rb
Also removed Embargo and Lease from the menu. In hyrax these are available in the dashboard, not the "my_actions" dropdown menu.
=> Fixes #1572, Non-privileged logged in users should have limited menus

app/services/factory_service.rb, app/views/e_pubs/show.html.erb, lib/e_pub.rb, lib/e_pub/bridge_to_webgl.rb, lib/e_pub/cfi.rb, lib/e_pub/publication.rb, lib/spec/e_pub/bridge_to_webgl_spec.rb
* Create a poi -> cfi mapping on the backend if the monograph has both
a webgl and epub. Store the map as json in the epub cache
* Fetch the map on the frontend after the cozy reader has loaded
=> Work towards #1630, a POI to CFI mapping between webgl and epub

Gemfile, Gemfile.lock, app/assets/stylesheets/application/themes.scss, app/views/e_pubs/show.html.erb
Resolves #1442
Re-instates @conorom's mobile work on EPUB show page.
Adds an Accessibility Mode on/off toggle in preferences pane for EPUBs that have WebGL assets. If "on": closes WebGL panel, marks the .special-panel as hidden, disables 3D model button, and publication links that go to SU panels in WebGL model are replaced with links that go to corresponding SU database records.
(Also, updates cozy-sun-bear)
=> Accessibility mode for EPUBs with WebGL

app/views/e_pubs/show.html.erb
Resolves #1674 
If a webgl project, use a different feedback form on the e-reader so we can collect browser and OS information from users.
=> change the feedback link for webgl

app/assets/stylesheets/application/themes.scss, app/views/e_pubs/show.html.erb, app/views/monograph_catalog/_index_monograph.html.erb
Resolves #1695 
Incorporates feedback from mockups. Adds message on monograph catalog page about free-trial access and a link to purchase (goes to press product page). Adds a dismissible message in the e-reader about free-trial access and a link to purchase (goes to press product page).
Adds some custom styles to control display. 
These messages will be removed after June 2018.
=> Add free trial messaging for gabii/webgl titles

app/assets/stylesheets/application/heliotrope.scss, app/views/e_pubs/show.html.erb
Resolves [CSB#43](https://github.com/mlibrary/cozy-sun-bear/issues/43)
Adds a share widget button that shares title and citable link to social sites.
Clicking the share button activates a (bootstrap) dropdown menu with a list of social sites.
Clicking a social site opens that site in a new window with title and citable link pre-populated.
Is using the same share sites we use for assets.
=> add share widget button to heliotrope e-reader

app/controllers/e_pubs_controller.rb, app/models/featured_representative.rb, app/presenters/concerns/featured_representatives/file_set_presenter.rb, app/presenters/concerns/featured_representatives/monograph_presenter.rb, app/presenters/e_pub_download_presenter.rb, app/views/e_pubs/show.html.erb, spec/models/featured_representative_spec.rb, spec/presenters/e_pub_download_presenter.rb
Display a download widget in cozy sun bear that allows a user to download various ebook formats (epub, mobi, pdf) if 1) they are available and 2) the user has permission to download them.
Includes:
HELIO-1270
=> HELIO-1270 - Csb/download widget

app/controllers/e_pubs_controller.rb, app/controllers/webgls_controller.rb, app/services/factory_service.rb, spec/controllers/e_pubs_controller_spec.rb, spec/controllers/webgls_controller_spec.rb, spec/services/factory_service_spec.rb
There are still some places where we're using Fedora to display when we should be using Solr. But these places are tied into what it means to be "tombstoned" and development for that is scheduled for Summer '18 so we'll deal with those then see #994. This PR does remove some current tombstone code, but all of that will be worked out in #994.
The FactorService specs are pretty slow right now, but that area too is going to be refactored so changes are coming see #1692
=> Resolves #1689, replace fedora calls with solr calls

app/actors/hyrax/actors/monograph_actor.rb
In cases where the actor environment lacks permissions information, extract them from the `curation_concern`.
=> Addresses #1725 file manager changes visibility.

app/controllers/featured_representatives_controller.rb, app/jobs/characterize_job.rb, spec/controllers/featured_representatives_controller_spec.rb
* The UnpackJob should be called when a FileSet's FeaturedRepresentatives is "set" (epub, webgl only)
* The UnpackJob should be called when a FileSet (that's already a FeaturedRepersentative of epub, webgl) is "reversioned"
See #1692 
This is working on heliotrope-testing
=> epub and webgl UnpackJob triggers

app/assets/javascripts/application/tabs.js, app/assets/stylesheets/application/heliotrope.scss, app/views/hyrax/file_sets/_attributes.html.erb, app/views/monograph_catalog/_index_monograph.html.erb
Resolves #1753 
Corrects ARIA semantics to correctly announce tabs and tab panel activation; Toggles ARIA semantics on tab switching; captures keydown events to allow for navigation between tabs; sets focus to tab panel upon selecting a tab; adds headings to tab panels to ensure tab panels are discovered in document outline; Moves inline JS to tab.js to be included in asset pipeline.
=> Accessibility fixes for monograph and asset tabs

app/controllers/manifests_controller.rb, app/controllers/monograph_manifests_controller.rb, app/models/manifest.rb, app/models/monograph_manifest.rb, app/presenters/manifest_presenter.rb, app/presenters/monograph_manifest_presenter.rb, app/uploaders/manifest_uploader.rb, app/views/manifests/_form.html.erb, app/views/manifests/edit.html.erb, app/views/manifests/new.html.erb, app/views/monograph_manifests/preview.html.erb, app/views/monograph_manifests/show.html.erb, config/locales/en.yml, config/routes.rb, lib/import/csv_parser.rb, lib/import/importer.rb, spec/lib/import/importer_spec.rb, spec/models/manifest_spec.rb, spec/models/monograph_manifest_spec.rb, spec/presenters/manifest_presenter_spec.rb, spec/presenters/monograph_manifest_presenter_spec.rb, spec/requests/monograph_manifests_spec.rb
Routes restricted to platform admins.
Append /manifest to monograph url to access
Import of metadata not implemented.
Selecting import is equivalent to selecting delete.
Deploy to testing for your convenience.
=> Part One #1812: Metadata Download/Upload/Update Cycle

app/search_builders/hyrax/my/search_builder.rb, app/views/hyrax/monographs/show.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/monograph_catalog/index.html.erb, config/workflows/heb_mediated_deposit_workflow.json, lib/import/importer.rb, script/import, spec/factories/admin_sets.rb, spec/features/monograph_dashboard_role_visibility_spec.rb, spec/lib/import/importer_spec.rb, spec/views/monograph_catalog/index.html.erb_spec.rb
This is safe to merge as-is. Until we register the new workflow and then associate an admin_set/permissions template, nothing will need to change in staging/testing/preview/production.
After the merge, I'll update, I don't know maybe testing and register the workflow/make an admin set. I'll document the process in confluence and then when we release to production we'll duplicate it.
=> HELIO-1478 Use a role based mediated deposit workflow for heb ingest

app/views/monograph_catalog/_index_epub_toc.html.erb, lib/e_pub/chapter_presenter.rb, lib/spec/e_pub/chapter_presenter_spec.rb
Instead of using the chapter's href to link into CSB, use the
chapter's CFI. This "base" CFI should work for both renditions.
=> HELIO-1861 toc link to CSB is broken for multi rendition epubs

app/controllers/e_pubs_controller.rb, spec/controllers/e_pubs_controller_spec.rb
Limits session[:show_set] to a length of ten.
=> Resolves 1905 Session Cookie Overflow

app/assets/stylesheets/application/heliotrope.scss, app/presenters/hyrax/monograph_presenter.rb, app/presenters/hyrax/presents_attributes.rb, app/renderers/hyrax/renderers/attribute_renderer.rb, app/views/monograph_catalog/_index_epub_toc.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, config/locales/en.yml, spec/features/create_monograph_spec.rb
Resolves [HELIO-1865](https://tools.lib.umich.edu/jira/browse/HELIO-1865)
For the monograph catalog page, this work: 
- Changes metadata display from table to definition list for better use of HTML semantics
- Adds monograph subjects to the metadata list
- Adds publication year
- Modifies display of copyright information and holding contact
- Styles chapter download button
- Fixes discrepancies between placeholder and label search text on monograph and publisher pages.
=> Add subjects, pub date; rework metadata display for monographs

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss, app/controllers/press_catalog_controller.rb, app/indexers/monograph_indexer.rb, app/models/monograph.rb, app/views/catalog/_document.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/press_catalog/_document_gallery.html.erb, app/views/press_catalog/_facets.html.erb, app/views/press_catalog/_index_header_list_monograph.html.erb, app/views/press_catalog/_press_results.html.erb, app/views/press_catalog/_thumbnail_list_monograph.html.erb, app/views/press_catalog/index.html.erb, app/views/shared/_brand_press_jumbotron.html.erb, spec/features/press_catalog_spec.rb
Resolves HELIO-1926
Adds filters to publisher catalog page.
Begins adding sort configs for publisher catalog page.
Fixes accessibility issues on monograph and publisher catalogs detailed in HELIO-1751 and modifies styles to maintain current display.
=> Add filters to publisher catalog page; begin other enhancements to publisher catalog

README.md, app/assets/javascripts/idpselect/idpselect_config.js, app/controllers/sessions_controller.rb, app/controllers/shibboleths_controller.rb, app/models/user.rb, app/views/e_pubs/access.html.erb, config/application.rb, config/routes.rb, config/settings/development.yml, config/settings/test.yml, lib/tasks/roles.rake, ruumba/.ruumba.yml, spec/controllers/sessions_controller_spec.rb, spec/factories/users.rb, spec/features/sign_in_out_spec.rb
Integrated Shibboleth and removed devise :database_authenticatable and added devise :rememberable which explicit leaves only devise :http_header_authenticatable for authentication.  Rememberable should remember if a session has been authenticated.
A request was made to A&E to reconfigure heliotrope-testing to use Shibboleth only (a.k.a. remove CoSign configuration).   As it is now they both exist and CoSign is being used for login authentication.
This branch was deployed to heliotrope-testing and publisher heliotrope has a restricted EPUB.
=> Integrate Shibboleth Authentication

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss, app/controllers/monograph_catalog_controller.rb, app/controllers/press_catalog_controller.rb, app/views/hyrax/file_sets/show.html.erb, app/views/press_catalog/_index_gallery_monograph_wrapper.html.erb, app/views/press_catalog/_index_header_gallery_monograph.html.erb, app/views/press_catalog/index.html.erb, spec/features/monograph_catalog_sort_spec.rb, spec/features/press_catalog_spec.rb
Resolves [HELIO-1934](https://tools.lib.umich.edu/jira/browse/HELIO-1934)
Makes style and markup changes to the publisher filters and gallery views for books; adds a few accessibility fixes that were discovered during VPAT assessment.
This branch is currently deployed to staging if you'd like to take a look:
https://heliotrope-staging.hydra.lib.umich.edu/heb
https://heliotrope-staging.hydra.lib.umich.edu/northwestern
=> Style publisher filters and gallery view

Gemfile, Gemfile.lock, app/controllers/press_catalog_controller.rb, app/presenters/hyrax/monograph_presenter.rb, app/views/press_catalog/index.html.erb, spec/features/press_catalog_spec.rb
HELIO-1954 only show the "publisher" filter for HEB
Also changed the default sort to be different in "search" vs. "browse"
=> HELIO-1953 don't show filters when a publisher has < 15 books

app/jobs/reindex_epub_job.rb, lib/tasks/reindex_epubs.rake, spec/jobs/reindex_epub_job_spec.rb
This has been run on staging and reindexes epubs correctly. However, don't run it in production until HELIO-1966 is done.
=> HELIO-1973 rake task and job to rebuild epub sqlite indexes

.gitignore, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/authentications_controller.rb, app/models/user.rb, app/policies/policy_agent.rb, config/initializers/services.rb, lib/devise/behaviors/http_header_authenticatable_behavior.rb, lib/devise/fake_auth_header.rb, lib/devise/models/keycard_authenticatable.rb, lib/devise/strategies/http_header_authenticatable.rb, lib/devise/strategies/keycard_authenticatable.rb, spec/controllers/application_controller_spec.rb, spec/controllers/e_pubs_controller_spec.rb, spec/features/sign_in_out_spec.rb, spec/lib/devise/fake_auth_header_spec.rb, spec/lib/devise/keycard_authenticatable_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
This PR brings an in an update to Keycard and adjusts the Devise binding to use it rather than resolving the HTTP headers itself. There are detailed comments on the commits.
To switch modes, config/settings/*.yml should have a keycard.access property. The default is direct, which assumes no proxy. See Keycard for more details on the changes from RequestAttributes to the family of classes.
Note that this PR only uses the user_eid, which may or may not be present for all users. However, the user_pid is certainly not fit for display, so heliotrope will need to consider the relationship between id/user_key/email on the model and user_eid/user_pid/mail from Keycard for login, identification, and display purposes.
This PR does not address institutional affiliation by way of Shibboleth login. …
=> Add Shibboleth support via Keycard

app/helpers/hyrax/citations_behaviors/title_behavior.rb, spec/helpers/hyrax/citations_behaviors/title_behavior_spec.rb
Hyrax built-in functionality copied and minimally patched to correct some brain-dead behavior.
=> Addresses HELIO-1991 Citation tool capitalization inconsistencies.

app/assets/javascripts/application.js, app/assets/javascripts/application_message.js, app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss, app/presenters/hyrax/monograph_presenter.rb, app/views/monograph_catalog/index.html.erb
Resolves HELIO-1900
Presents HEB users on the monograph page with a message and links to 1) the book on the legacy platform and 2) the accessibility/usability google form to collect information from users if they are having trouble using the new platform.
Because the links to DLXS are constructed using the HEB ID stored in the multi-value `:identifier` field (which also contains the old HEB handles) there was a little bit of work on the `monograph_presenter` needed in order to find and use the right HEB ID to construct the links.
=> add message for HEB users that provides a link to the book on DLXS

app/views/shared/_metadata.html.erb, spec/views/shared/_metadata.html.erb_spec.rb
Resolves HELIO-2055 and HELIO-2056, adding correct publisher meta tags, listing all ISBNs, and correct publication date.
=> HELIO-2055 and HELIO-2056 - modify monograph meta tags

app/controllers/sessions_controller.rb
- Redirect to the SP, rather than /shib_login in the production fallback
- Move the default entity ID to the sp_login_url to catch all cases
- Skip storing user location for all sessions controller actions
Note that this change should eliminate the need for the `default_login`
action entirely. It should be removed and links updated to use /login.
=> HELIO-2064 - Fix up default login redirect

app/assets/javascripts/application_message.js
Resolve HELIO-2091
By changing the binding to wait for turbolinks to load, the JS function closeMessage() becomes executable when the DOM or window does not actually re-load; this modification appears to fix the issue of being unable to close the message window upon login or logout, or other thinks that utilize turbolinks.
=> HELIO-2091 - change binding to respect turbolinks

app/views/monograph_catalog/_index_epub_toc.html.erb, lib/e_pub/rendition.rb, lib/e_pub/unmarshaller/content.rb, lib/spec/e_pub/rendition_spec.rb, lib/spec/e_pub/unmarshaller/content_spec.rb, spec/controllers/e_pubs_controller_spec.rb
* This can make some quite long TOCs for reflowable epubs, https://heliotrope-staging.hydra.lib.umich.edu/concern/monographs/6m311p36k?locale=en
* Refactoring/deduplication of some of the cfi related code will happen in HELIO-2069
=> HELIO-2052 Fix TOC Anchor tag for EPUBs

spec/jobs/reindex_epub_job_spec.rb, spec/jobs/unpack_job_spec.rb
These specs were in the top 10 slowest:
ReindexEpubJob perform reindexes the epub
5.56 seconds ./spec/jobs/reindex_epub_job_spec.rb:14
UnpackJob perform with a pre-existing epub adding a webgl creates the epub-webgl map
4.1 seconds ./spec/jobs/unpack_job_spec.rb:58
But no longer are
=> Slightly speed up the epub job specs

app/models/counter_report.rb, app/services/counter_reporter_service.rb, spec/factories/counter_reports.rb, spec/models/counter_report_spec.rb, spec/services/counter_reporter_service_spec.rb
This PR creates the PR_P1 COUNTER 5 report, but is not hooked in to the UI or deals with auth in any way. It's a very "shameless green" approach. Refactoring to a more sustainable pattern will happen as we create the different kinds of COUNTER reports and thereby gather better/more information on what kinds of patterns should be used.
=> HELIO-2144 Create COUNTER Platform Usage Report PR_P1

app/assets/stylesheets/application/heliotrope.scss, app/views/press_catalog/_index_gallery_monograph_wrapper.html.erb
To deal with CSS not loading from the file representative and turbolinks interference.
=> HELIO-2201 - move styles from representative file into heliotrope.scss

app/assets/javascripts/application/tabs.js
Change `localStorage` to `sessionStorage` so browser tabs don't clobber each other wrt saved tab selection.
=> Addresses HELIO-2135 monograph page fails to retain asset tab selection.

app/controllers/press_catalog_controller.rb
Just makes it so HEB facets are sorted alphabetically, instead of by count.
=> Addresses HELIO-2286 facet sort options

app/controllers/e_pubs_controller.rb, app/models/share_link_log.rb, app/views/e_pubs/show.html.erb, config/settings/test.yml, db/migrate/20181214194406_create_share_link_logs.rb, db/schema.rb, spec/controllers/e_pubs_controller_spec.rb, spec/factories/share_link_logs.rb, spec/system/epub_share_links_spec.rb
Log share link creation and use (including ip addr and instituion if possible
A user coming to the ereader from a share link:
a) does not see the download button
b) does not see the scholarly sharing link button
=> HELIO-2382 epub share link logic changes

app/views/hyrax/base/_form_progress.html.erb
YAHO (Yet Another Hyrax Override) that redirects back to monograph page on edit cancellation.
=> Addresses HELIO-2443 Edit Monograph should redirect back.

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss, app/views/monograph_catalog/_index_monograph.html.erb, config/locales/en.yml
Resolves HELIO-2447
Styles download button and makes a couple minor tweaks to the display of cc licenses and pub year in monograph metadata.
=> add download button that displays for platform admins only

app/jobs/reindex_job.rb, app/services/restful_fedora.rb, app/services/restful_fedora/service.rb, spec/jobs/reindex_job_spec.rb, spec/services/restful_fedora/service_spec.rb, spec/services/restful_fedora_spec.rb, spec/services/sighrax_spec.rb
When ActiveFedora::Base.reindex_everything times out or overflows the buffer try RestfulFedora.reindex_everything.
=> Resolves HELIO-2476: reindex_everything

app/models/aptrust_upload.rb, db/migrate/20190218193221_create_aptrust_uploads.rb, db/schema.rb, spec/factories/aptrust_uploads.rb, spec/models/aptrust_upload_spec.rb
Adds:
a migration for aptrust_uploads table
a model aptrust_upload.rb
an updated db/schema.rb
a spec/factories/aptrust_uploads.rb
a spec/models/aptrust_upload_spec.rb
rubocop and specs pass
=> 2525_make_aptrust_upload_tracking_table

app/presenters/concerns/featured_representatives/monograph_presenter.rb, app/views/monograph_catalog/_index_epub_toc.html.erb, lib/e_pub/rendition.rb, lib/e_pub/unmarshaller/content.rb, lib/spec/e_pub/unmarshaller/content_spec.rb
* Do not calculate CFIs for TOC members with anchor tags
* Do not re-open the epub every time monograph_presenter.epub_presenter is called
According to skylight and testing this is a vast improvment, but is still not perfect.
=> HELIO-2461 fix render time of _index_epub_toc.html.erb

app/presenters/hyrax/file_set_presenter.rb
I am hoping the Checkpoint cleanup can make the need for this hack go away.
=> HELIO-2562 Download widget displays files when 'Allow Download?'='no'

lib/tasks/bag_updated_monographs.rake
This code first:
- Finds all published solr documents for monographs
- Examines the documents one by one and compares them with the aptrust_uploads tables to determine if they need to new bag or need an updated bag
Then it creates new bags or updates existing ones based the above results (if needed)
=> 2541_bag_updated_monographs

app/controllers/api/v1/individuals_controller.rb, app/controllers/api/v1/institutions_controller.rb, app/helpers/press_helper.rb, app/services/greensub.rb, spec/controllers/e_pubs_controller_spec.rb, spec/controllers/grants_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/helpers/press_helper_spec.rb, spec/models/component_spec.rb, spec/models/individual_spec.rb, spec/models/institution_spec.rb, spec/models/product_spec.rb, spec/models/user_spec.rb, spec/requests/api/v1/individuals_spec.rb, spec/requests/api/v1/institutions_spec.rb, spec/requests/api/v1/products_spec.rb, spec/services/greensub_spec.rb
Primarily added named parameters to the Greensub service methods.  
For example:
Greensub.subscribed?(subscriber, product) --> Greensub.subscribed?(subscriber:, product:)
=> Resolves HELIO-2582: Turnsole Greensub Refactor

Gemfile, Gemfile.lock
Resolves HELIO-2514 in heliotrope
Resolves CSB-206 and CSB-211 in cozy-sun-bear
This version of CSB updates the scrolling manager to handle pre-paginated volumes, and also sets us up to do hypothes.is integration. In particular:
use IntersectionObserver for performance
bundle polyfills for IntersectionObserver
separate preferences between layouts
This should allow us to stop making `.sm.epub`s and passing `useArchive` to CSB for pre-paginated volumes, a practice that was established to deal with performance issues that were experienced in HEB pre paginated EPUBs.
I have tested this on heliotrope preview server with both pre-paginated and reflowable EPUBs and across Firefox, Chrome, Safari, Edge and IE 11.
=> Resolves HELIO-2514, CSB-206 and CSB-211

spec/controllers/monograph_catalog_controller_spec.rb
after do
ActiveFedora::Cleaner.clean! # Sweep away tombstone a.k.a. LDP::Gone
end
=> Resolves HELIO-2568: Fix a flapping spec

config/aptrust.yml.sample
When using the aptrust api to check on the status of ingesting/ingested bag, you can contact the demo or production urls.
Demo: https://demo.aptrust/member-api/v2/
Repo: https://repo.aptrust/member-api/v2/
These have various end points as described here: https://wiki.aptrust.org/Member_API#Object_Resource
=> add demo or repo url to aptrust.yml.sample

Gemfile, Gemfile.lock, lib/tasks/bag_updated_monographs.rake
Changes include:
- Various simplifications as they become clearer.
- Use one array for new and recreated bags.
- Where I passed record and noid before just pass record if possible
- When the published solo record doesn't need a new bag record its APTrust API deposit status in db row for record (note this doesn't work for desktop development because there is not API for A&E s3).
=> 2541_rake_add_apt_check

app/assets/stylesheets/application/heliotrope.scss, app/views/monograph_catalog/_index_epub_toc.html.erb
Removes absolute positioning and inline-block display of download/read buttons, changes them to use flexbox and adds max-widths for title block elements to ensure they don't run over buttons. Small accessibility fix to EBC message so that links in the message are visible.
=> Resolves HELIO-2510

app/controllers/fulcrum_controller.rb
Reduce calls to determine if stats should be recalculate by only checking when publisher partial is being viewed by the user.
=> Recalculate stats only for publishers partial

app/views/aptrust_logs/index.html.erb, config/routes.rb, lib/export/exporter.rb, lib/tasks/bag_updated_monographs.rake
Converted puts comments and errors to logging statements.
Added logging view with filtering.
Added to routes.rb: 'resources :aptrust_logs, only: %i[index]'
Arrg: StandardError was failing when bagIt was creating a dir, so I'm now pre-making the dir for it.
=> Add aptrust log view and start logging

app/controllers/api/v1/monographs_controller.rb, app/jobs/output_monograph_files_job.rb, app/models/null_press.rb, app/models/press.rb, app/models/sighrax/asset.rb, app/models/sighrax/entity.rb, app/models/sighrax/model.rb, app/models/sighrax/monograph.rb, app/presenters/hyrax/presenter.rb, app/services/sighrax.rb, lib/export/exporter.rb, spec/lib/export/exporter_spec.rb, spec/models/press_spec.rb, spec/models/sighrax/asset_spec.rb, spec/models/sighrax/child_parent_spec.rb, spec/models/sighrax/entity_spec.rb, spec/models/sighrax/model_spec.rb, spec/models/sighrax/monograph_spec.rb, spec/presenters/hyrax/presenter_spec.rb, spec/services/sighrax_spec.rb
Refactor Sighrax to seperate Hyrax from Sighrax by making request for a Hyrax presenter an explicit 'factory' call, see Sighrax.hyrax_presenter(entity) class method.
Also added explicit press factory: Sighrax.press(entity).
=> Sighrax Hyrax Presenter Support

Gemfile, Gemfile.lock
Updates to use latest from CSB, which resolves CSB-208 and CSB-210. 
In FF, tall tables with a height greater than the size of the canvas do not reflow onto the next page and become clipped. This fix introduces a feature that detects the clipping in FF, and presents a button for the reader to open the table in modal window. See attached screenshots. Tested on preview.
=> HELIO-2643 - resolves CSB-208 and CSB-210

app/jobs/attach_import_files_to_work_job.rb
ordered_members to a Work one time.
This is now working for all imports as well as 3000+ FileSet Monographs.
=> HELIO-1868 Use alternate Hyrax::Actors::OrderedMembersActor to attach

app/presenters/hyrax/monograph_presenter.rb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/press_catalog/_index_gallery_monograph_wrapper.html.erb, app/views/press_catalog/_thumbnail_list_monograph.html.erb, app/views/press_catalog/_thumbnail_monograph.html.erb, spec/presenters/hyrax/monograph_presenter_spec.rb
The thumbnails for real covers are resized by the image service but the generic work icon for monographs without covers was turning up at very large sizes sometimes. By moving the img tag construction inside the monograph_thumbnail method (which was generating the img src) we are able to add a max-width to the generic icon of whatever width we'd request for the real cover.
Fixes #2617
=> MonographPresenter.monograph_thumbnail generates entire img tag

lib/e_pub/unmarshaller/toc.rb, lib/spec/e_pub/unmarshaller/toc_spec.rb
Change the default nav id attribute to "toc" from 0
I've put this on preview and tested it with a variety of epubs there.
=> HELIO-2649 EPub TOC id attribute default is wrong

.rubocop.yml, Gemfile, config/blacklight.yml, config/cable.yml, config/database.yml.sample, config/environments/devproque.rb, config/fedora.yml, config/redis.yml, config/role_map.yml.sample, config/secrets.yml.sample, config/settings/devproque.yml, config/solr.yml
Allows you to run a production resque worker in your development environment.
QUEUE=* VERBOSE=1 RAILS_ENV=devproque bundle exec rake resque:work
This worker will eager load the rails application once hence the actor stack will be created like the one in production and you'll be able to use the ExtractIngestJob to copy content from fulcrum.org into your development environment.
=> Development Production Resque Worker Environment: devproque

Gemfile, Gemfile.lock
to latest version, featuring hooks for hypothes.is annotation support and continued work for HELIO-2587 (hypothes.is integration in heliotrope).
=> HELIO-2691 - update CSB

lib/export/exporter.rb, lib/tasks/bag_updated_monographs.rake
The length of the following 'internal_sender_description' does not work with the current bagit gem so I shortened it.
=> 2404_aptrust_clean_up6

Gemfile, Gemfile.lock
Use feature added in CSB-219, which allows an external stylesheet to be passed to an EPUB
=> CSB-219 - Update CSB 

app/overrides/hyrax/downloads_controller_overrides.rb, spec/controllers/hyrax/downloads_controller_spec.rb
This works for me with pdf assets in chrome and FF
=> HELIO-1526 Preview PDFs in the View page should download inline

app/controllers/api/v1/crossref_registrations_controller.rb, config/routes.rb, spec/fixtures/fake_crossref_submit.xml, spec/requests/api/v1/crossref_registrations_spec.rb
Using a token and some xml I'm able to use this to post to test.crossref.org using curl.
=> HELIO-2655 Add crossref submission api endpoint

.rubocop_todo.yml, app/controllers/e_pubs_controller.rb, app/helpers/breadcrumbs_helper.rb, app/presenters/concerns/social_share_widget_presenter.rb, app/presenters/concerns/title_presenter.rb, app/presenters/hyrax/monograph_presenter.rb, app/views/e_pubs/show.html.erb, app/views/hyrax/file_sets/_show_actions.html.erb, app/views/monograph_catalog/_index_header_gallery_file_set.html.erb, app/views/monograph_catalog/_index_header_list_file_set.html.erb, app/views/press_catalog/_index_header_gallery_monograph.html.erb, app/views/press_catalog/_index_header_list_monograph.html.erb, spec/controllers/e_pubs_controller_spec.rb, spec/features/create_monograph_spec.rb, spec/features/edit_file_set_spec.rb, spec/presenters/concerns/social_share_widget_presenter_spec.rb, spec/presenters/concerns/title_presenter_spec.rb, spec/views/monograph_catalog/index.html.erb_spec.rb
HELIO-2699, HELIO-2710, HELIO-2712
- CGI escape for URLs, i.e. hashtags
- break huge CSB share link widget template value into methods
- tests for title-based (and other) social media share links
- more title-base links allow Markdown/HTML emphasis, e.g.
breadcrumbs, file_set links on catalog page
- fix regression where Markdown syntax is showing
- remove HTML from page title for EPUB reader
- improve test coverage around breadcrumbs and...
Markdown in titles
=> title handling improvements

lib/tasks/bag_updated_monographs.rake
Cleaning up the bag name by adding fulcrum.org. to beginning of name in the method that checks if the bag is deposited (update_db_aptrust_status(record)).
=> 2404_aptrust_clean_up8

app/assets/stylesheets/application/heliotrope.scss, app/views/e_pubs/show.html.erb
Add listeners for annotation; add custom annotation control; adjust CSS and annotation icon; config hypothes.is e-reader show page; configure panel toggle on and off for annotations; add annotation counts to button; moves altmetric and dimensions widgets to the top menu because we are reaching too many widget buttons in the mid menu.
This branch also include some basic cleanup to the e-reader show page.
=> HELIO-2587 - add hypothes.is annotation widget

app/assets/stylesheets/application/themes.scss
Remove gabii specific rule that overrode positioning of altmetric/dimensions badges.
Change this:
To this:
=> fixup gabii CSS

app/assets/javascripts/application/freeze_dois.js.erb, config/crossref.yml.sample, spec/services/crossref/config_spec.rb
This works in preview for both monographs and file_sets. Examples:
Registered:
https://heliotrope-preview.hydra.lib.umich.edu/concern/monographs/hm50tr93z/edit?locale=en
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/d504rk45z/edit?locale=en
(it can take a few seconds for the ajax call to come back)
Unregistered:
https://heliotrope-preview.hydra.lib.umich.edu/concern/monographs/41687h652/edit?locale=en
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/0v838086x/edit?locale=en
=> HELIO-2740 Minted DOIs cannot be updated in the UI

lib/e_pub/search.rb
Add end-of-string anchor in addition to \W non-word at end. Searching for e.g., "1390" in Gabii now returns results.
=> Addresses HELIO-2450 EPUB Search does not work for numbers.

app/assets/stylesheets/application/blacklight_facets.scss, app/helpers/facet_helper.rb, app/views/monograph_catalog/_facet_pivot.html.erb
Found that (reverting to) use of the facet-count class rather than facet-pivot-count class allows the (e.g.,) format facets to display like the reasonably well-behaved section facets.
=> Addresses HELIO-1988 Fix display of filters when zooming only text.

lib/export/exporter.rb
Two changes:
- Conor noted that the tar data directory contents weren't correct. This was because the bag was been tar'd before the extract was complete because the extract was changed to be a job. He suggested a fix which works well. lib/export/exporter.rb L89.
- The other change was to the production credentials so that it s3 upload to APTrust now works in production.
=> add fix for extract job

app/views/e_pubs/show.html.erb, fulcrum/css/fulcrum_enhanced_display.css
Adds an external stylesheet to the fulcrum public folder that can be referenced by CSB; modifies CSB to inject stylesheet if the EPUB is from Michigan/EBC
=> HELIO-2813 - Implement fulcrum enhanced resources display for EBC

config/routes.rb
302 redirect for Mozilla PDF viewer files
=> 302 redirect for Mozilla PDF viewer files

app/views/e_pubs/show_pdf.html.erb
Stops the reader from going to the wrong page when there's front matter.
=> PDFReader.gotoPage should be setting currentPageNumber

app/views/e_pubs/show_pdf.html.erb
Closes HELIO-2921.
Ports the pdfViewer scaling options (auto/page-fit/etc) to a cozy-sun-bear preference panel and adapts the preview accordingly.
=> Updating scaling preferences to use native pdfViewer scaling

app/models/google_analytics_history.rb, app/presenters/concerns/analytics_presenter.rb, db/migrate/20190916160819_create_google_analytics_history.rb, db/schema.rb, lib/tasks/add_ga_history.rake, lib/tasks/ga_cache.rake, spec/factories/google_analytics_histories.rb, spec/models/google_analytics_history_spec.rb, spec/presenters/concerns/analytics_presenter_spec.rb
this is on preview now. I've run the add_ga_history.rake task and it's matching up with what we have in the cache.
```
irb(main):011:0> Rails.cache.read('ga_pageviews')['3n203z11f'].map{|date, pageviews| pageviews }.sum
=> 180
irb(main):012:0> GoogleAnalyticsHistory.where(noid: '3n203z11f').map(&:pageviews).sum
GoogleAnalyticsHistory Load (0.7ms)  SELECT `google_analytics_histories`.* FROM `google_analytics_histories` WHERE `google_analytics_histories`.`noid` = '3n203z11f'
=> 180
irb(main):013:0> 
```
I've added a nightly cron to add yesterdays stats. Everything seems to be right....
=> HELIO-2949 Save GA data to the database, not cache

app/views/e_pubs/show_pdf.html.erb
- adapt PDFReader to use `epubcfi(page=N)` as the internal "CFI" for PDFs
- notice that the next/previous buttons were actually firing multiple events because the `Reader` _and_ `PDFViewerApplication` were binding to them; rework the controls so only `PDFViewerApplication` handles next/previous
- leverage monkeypatch to handle tracking contents navigation to handle when PDFViewerApplication was about to change the zoom by following a link
=> Investigate browser history

app/controllers/e_pubs_controller.rb, lib/tasks/handles_file_sets_since.rake, lib/tasks/handles_monographs_since.rake, lib/tasks/handles_publisher.rake, lib/tasks/handles_single_monograph.rake
and Social Media Share Links in CSB point to the catalog page, not the
epub/pdf_ebook.
HELIO-2981 No special handles for FeaturedRepresentatives
Tested all the handle rake tasks in dev
Tested the Social Media Share Links to verify that they go to the monograph
#done
=> HELIO-2720 CSB Permalink widget uses parent citation_link, not FileSet

app/helpers/hyrax/citations_behavior.rb, app/helpers/hyrax/citations_behaviors/formatters/apa_formatter.rb, app/helpers/hyrax/citations_behaviors/formatters/chicago_formatter.rb, app/helpers/hyrax/citations_behaviors/formatters/mla_formatter.rb, spec/features/create_monograph_spec.rb, spec/helpers/hyrax/citations_behavior_spec.rb
This is mostly code appropriated from Hyrax and fixed up. Rubocop warns against use of html_safe but I found that omitting it interfered in unpredictable ways with tests in create_monograph_spec.rb. It's nothing that wasn't already happening inside Hyrax.
=> Addresses HELIO-3062 Update citation widget to include citable link.

app/assets/stylesheets/application/heliotrope.scss, app/views/e_pubs/show.html.erb
Resolves HELIO-2727, Revert to Vanilla Hypothesis. This work does the following:
- Remove custom `.special-panel`
- Remove CSS for `.special-panel`.
- Turn on "clean" theme (panel does not show unless activated by toggle button or highlighted text)
Display onload does not show any panel:
Clicking annotation button in menu opens panel:
Clicking highlighted annotation opens panel:
Panel also opens when choosing to annotate something.
- Closing panel can only be accomplished by clicking the panel's "X" button.
=> HELIO-2727 - Revert to Vanilla Hypothesis

app/views/press_statistics/index.html.erb
Adding the PR so it doesn't get lost in the shuffle, whatever is the outcome of the ClamAV fiasco.
=> Addresses HELIO-3093 Readership Map doesn't work in Chrome

Gemfile, Gemfile.lock, app/views/e_pubs/_cozy_controls_top.html.erb, app/views/shared/_altmetric_dimensions.html.erb
Disables tooltips on Dimensions and Altmetrics badges because they violated WCAG 2.1 AA SC 2.1.1.
Also, update to the latest version of CSB.
=> Resolves HELIO-3104

app/assets/stylesheets/application/themes.scss, fulcrum/_includes/footer.html
modify BAR brand color to match the red used in their logo; also, updated copyright date on fulcrum aboutware/jekyll pages to 2020
=> HELIO-3214 - modify bar brand color

Gemfile, Gemfile.lock
Patched version of CSB resolves CSB-242, which now waits for updateLocations event before using locations in search results.
=> CSB-242 - update with the latest version of CSB

app/controllers/presses_controller.rb, app/helpers/press_helper.rb, app/views/presses/_form.html.erb, app/views/shared/_brand_press_bar.html.erb, app/views/shared/_brand_press_jumbotron.html.erb, db/migrate/20200113154152_add_navigation_to_presses.rb, db/schema.rb
If the nav block exists, don't show the jumbotron
HELIO-3102, HELIO-3103
I think I'd like to merge this now so we can put it on preview and iterate on it. If we need to put it into production via a hotfix (which we might not even have to do) we can cherry-pick out the commit.
=> Added customizable Press site navigation block

app/controllers/monograph_catalog_controller.rb, app/models/monograph_search_builder.rb, app/models/score_search_builder.rb, app/presenters/hyrax/file_set_presenter.rb, app/services/sighrax.rb, app/views/press_catalog/_index_gallery_monograph_wrapper.html.erb, app/views/press_catalog/_index_gallery_score_wrapper.html.erb, config/initializers/riiif_initializer.rb, spec/models/monograph_search_builder_spec.rb, spec/services/sighrax_spec.rb
The reason for this branch was from some excessive solr calls for cache key generation for IIIF tiling as talked about in a comment in HELIO-3052 that we there to make sure re-versioned/replaced FileSets were getting new/updated tiles. That works now with md5, not solr. This branch is on staging and I've tested re-versioning image FileSets and IIIF/Leaflet a few times.
Other then that some work was done in "Sighrax" in consultation with Greg before he went on vacation to reduce the number of (redundant) solr calls. And then a few bits of removing other unnecessary solr calls in a few other places.
In the end this branch shouldn't change any functionality but has the potential to greatly reduce the number of solr calls pages make.
=> HELIO-3052 make fewer solr calls

app/services/crossref/file_set_metadata.rb, spec/services/crossref/file_set_metadata_spec.rb
has to be 'application/vnd.ms-excel' for submissions.
HELIO-3163
I've submitted a "fixed" xml file to crossref with the new mime_type and it works fine. Should be fine to just merge this.
=> Crossref mime_types for file_sets that are 'text/csv'

app/jobs/unpack_job.rb, spec/jobs/unpack_job_spec.rb
HELIO-3165
Put this branch on staging, ran the heliotrope:unpack_pdf_ebooks task and the resulting pdfs are linearized. Seems to work ok.
=> pdf_ebooks unpacked onto /derivatives are linearized

app/controllers/api/v1/components_controller.rb, spec/requests/api/v1/components_spec.rb
If identifier and noid are both given then find component by both fields a.k.a. both must match for component to be found.
=> Resolves HELIO-3130 Changes to API to support find component by noid.

app/views/shared/_brand_press_jumbotron.html.erb, app/views/shared/_header.html.erb
press_catalog page and if there's no aboutware.
This is on preview and looks fine.
=> Be explicit about when to render the jumbotron: only on the

config/sitemap.rb
docs = ActiveFedora::SolrService.query("+has_model_ssim:Monograph AND -(press_sim:demo OR press_sim:monitoringservicetarget)", rows: 100_000)
=> Partial resolution to HELIO-3107 monitoring service

app/jobs/characterize_job.rb, spec/jobs/characterize_job_spec.rb
~Browsers should use the new version, not their cached version.~
(not sure if the client caching stuff is working right yet. let's get this obvious fix into production at least)
HELIO-3196
=> pdf_ebooks should be "unpacked" when re-versioned

app/controllers/press_catalog_controller.rb, app/models/user.rb, app/services/sighrax.rb, spec/factories/users.rb, spec/models/ability_spec.rb, spec/models/user_spec.rb, spec/services/sighrax_spec.rb, spec/views/shared/_my_actions.html.erb_spec.rb
Easier to verify in your dev environment by creating users with roles for press admin and press editor and a no role user.
By tweaking this line: 
https://github.com/mlibrary/heliotrope/blob/ad51f5c0ce810ecebeaed36285af7187184b1fb0/app/controllers/press_catalog_controller.rb#L78
You can lower the threshold before the facets are displayed.  Make sure you have some draft works and some published works.
=> Resolves HELIO-3216 Display facets for admin/editor users

app/models/press_search_builder.rb, app/models/search_builder.rb, spec/models/press_search_builder_spec.rb, spec/models/search_builder_spec.rb
Copied and pasted #sort from Blacklight to SearchBuilder.  Modified #sort to call new #default_sort_field method which returns blackligh_config.default_sort_field.  Added new #default_sort_field method to PressSearchBuilder which switches on press.
=> Resolves HELIO-3171 default sort on catalog page.

app/presenters/hyrax/monograph_presenter.rb, spec/presenters/hyrax/monograph_presenter_spec.rb
=> show only `YYYY` or `cYYYY` for citation pub date

README.md, app/assets/javascripts/application/tabs.js, app/views/layouts/boilerplate.html.erb, app/views/shared/_monitoring.html.erb, config/jekyll.yml, spec/spec_helper.rb
Hotfix branch based on v2.55.1 that resolves HELIO-3279 IE11 compatibility issues.
=> Hotfix HELIO-3279

app/controllers/e_pubs_controller.rb, app/controllers/ebooks_controller.rb, app/helpers/hyrax/citations_behavior.rb, app/helpers/hyrax/citations_behaviors/formatters/mla_formatter.rb, app/services/watermark/watermarkable.rb, spec/controllers/e_pubs_controller_spec.rb, spec/requests/e_pubs_spec.rb, spec/requests/ebooks_spec.rb
There is a certain amount of added nastiness in the specs with +"…" unfrozen PDF strings. Prawn is particular about forcing encodings and having PDF content actually be PDF-like.
=> HELIO-3258 Modify download watermark

app/controllers/presses_controller.rb, app/jobs/publisher_stats_job.rb, app/models/sighrax/publisher.rb, app/views/fulcrum/_publishers.html.erb, config/routes.rb, spec/controllers/presses_controller_spec.rb, spec/models/sighrax/publisher_spec.rb
Platform administrators can now delete empty publishers from the fulcrum dashboard publishers page.
=> Resolves HELIO-3207 Delete NCID publisher entry

app/presenters/hyrax/file_set_presenter.rb
Removed the `pdf?` call in `glyphicon_type` in order to characterize PDF (interactive) maps, otherwise they just get a generic icon.
=> HELIO-2915 Add default icon for representing map resource types

Gemfile, Gemfile.lock
Updates ref point in Gemfile for CSB to include feature CSB-227: when there are problems displaying sections of an EPUB in the ereader, reader should emit a message that heliotrope can listen for.
=> Update CSB to include feature CSB-227

app/models/featured_representative.rb, db/migrate/20200330165632_add_indexes_to_featured_representatives.rb, db/schema.rb, spec/models/featured_representative_spec.rb
FYI: Ran the following rake task on production and it came up empty, hence the database migration should succeed when released to production.
desc 'Find non unique kind works'
namespace :heliotrope do
task find_non_unique_kind_works: :environment do
FeaturedRepresentative.distinct.pluck(:work_id).each do |work_id|
kind_count = FeaturedRepresentative.where(work_id: work_id).count
unique_kind_count = FeaturedRepresentative.where(work_id: work_id).distinct.pluck(:kind).count
next if kind_count == unique_kind_count
puts Sighrax.url(Sighrax.from_noid(work_id))
end
end
end
=> Resolves HELIO-3259 FeaturedRepresentative unique index not working

app/jobs/migrate_metadata_job.rb, spec/jobs/migrate_metadata_job_spec.rb
Migrate transcript to closed captions of video file sets only.
=> Quick fix to migrate transcript job to process videos only.

app/views/e_pubs/access/_barpublishing.html.erb
Note the addition of 
> <h3>Collections which include this title</h3>
above the list of Products, since recent library onboarding has revealed the meaning of this list is not clear.
=> PR to resolve HELIO-3342

app/controllers/press_catalog_controller.rb, app/helpers/catalog_helper.rb, spec/helpers/catalog_helper_spec.rb, spec/helpers/hyrax/citations_behaviors/name_behavior_spec.rb, spec/helpers/hyrax/citations_behaviors/title_behavior_spec.rb
```
module CatalogHelper
include Blacklight::CatalogHelperBehavior
##
#
def current_sort_field # rubocop:disable Metrics/CyclomaticComplexity
csf = (blacklight_config.sort_fields.values.find { |f| f.sort == @response.sort } if @response&.sort.present?) || blacklight_config.sort_fields[params[:sort]] || default_sort_field # rubocop:disable Rails/HelperInstanceVariable
return csf unless default_sort_field&.key == 'relevance' # First field in the sort fields list when searching
return blacklight_config.sort_fields[params[:sort]] if blacklight_config.sort_fields[params[:sort]].present?
default_sort_field                                       # NOTE: Not the same thing as blacklight_config.default_sort_field which is used when browsing
end
end
```
=> Resolves HELIO-3356 Sort should be relevance when searching.

app/services/crossref/file_set_metadata.rb, db/migrate/20200603181002_increase_response_xml_length_in_crossref_submission_logs.rb, db/schema.rb, spec/services/crossref/file_set_metadata_spec.rb
* Don't save resource/file_set DOIs if the work DOI is unregistered
* mime_type "audio/x-wave" is sent as "audio/basic"
* CrossrefSubmissionLog submission_xml field is now a :mediumtext
=> HELIO-3378 crossref file_set_metadata service changes

app/views/e_pubs/show.html.erb
HELIO-3350
This hot fix is already in production. It's a band aid that doesn't resolve the problem, which seems to be an issue in Safari 13 itself.
=> conditional scroll mode for Safari 13+

app/presenters/concerns/social_share_widget_presenter.rb, app/views/hyrax/file_sets/_show_actions.html.erb, spec/features/edit_file_set_spec.rb, spec/presenters/concerns/social_share_widget_presenter_spec.rb
Resolves HELIO-3417 - removal of cite u like sharing option from the e-reader and file set show page.
=> HELIO-3417 - remove cite u like sharing option and update specs

app/helpers/url_helper.rb
Override session_tracking_params method in Blacklight URL Helper to remove data-context-href attribute from anchor tag in search results.
Before:
<a data-context-href="/catalog/8w32r7414/track?counter=1&amp;locale=en&amp;search_id=67204814" href="/concern/monographs/8w32r7414?locale=en">
...
</a>
After:
<a href="/concern/monographs/8w32r7414?locale=en">
...
</a>
Verify blacklight search behavior does not change from the user's perspective.
=> Partially resolves HELIO-3449 blacklight search_context.js cause 404 error.

app/overrides/hyrax/file_set_actor_overrides.rb, spec/actors/hyrax/actors/file_set_actor_spec.rb
This is on preview and versioning is working (as well as normal file upload) via the UI. I don't believe this will have any effect on the importer or various import-like rake tasks we have.
=> HELIO-3506 fix versioning UI upload bug

app/views/press_statistics/index.html.erb
Automatic Third-Party Cookie detection isn't trivial so hopefully this passive solution of stating third-party cookies are required
`<p>Third-Party Cookies must be enabled. <a href="https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled" target="_blank">Are Third-Party Cookies enabled?</a></p>
`
and providing a link which opens a new tab to [https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled](https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled) which will test if the user has third-party cookies enabled and has information on where in the browser settings to look will be sufficient.
=> Are Third-Party Cookies enabled?

app/assets/javascripts/mozilla-pdf-viewer.js
Added turbolinks and ga_event_tracking requires to mozilla-pdf-viewer.js
=> turbolinks and ga_event_tracking

app/controllers/hyrax/admin/stats_controller.rb, app/jobs/publish_job.rb, app/models/ability.rb, app/models/role.rb, app/models/user.rb, app/services/group_permission_actor_service.rb, app/views/hyrax/admin/stats/_institution.html.erb, app/views/hyrax/dashboard/sidebar/_activity.html.erb, config/locales/en.yml, lib/tasks/temporary/add_analyst_role.rake, spec/factories/users.rb, spec/helpers/roles_helper_spec.rb, spec/jobs/publish_job_spec.rb, spec/models/ability_spec.rb, spec/models/user_spec.rb, spec/support/shared_examples/group_permission_actor.rb
Reports work fine for analysts, see HELIO-3379. Draft access should "mostly" work ok, but all our roles are having some issues as talked about in HELIO-3630.
=> HELIO-3379 Create Press Analyst role

Gemfile, Gemfile.lock
Resolves CSB-254, adds css to handle display of table heads that overflow the table container in the Fulcrum EReader.
=> CSB-254 - update csb to point to updated master branch

.travis.yml
travis ci builds are failing with libv8 compilation errors.
It might be because bundler 2.2 was released yesterday and we've
been installing bundler on travis with "--pre".
Something seems to be up with bundler 2.2 being smart about fetching
pre-built gems but maybe not working quite right?
https://github.com/rubyjs/libv8/issues/310#issuecomment-742481001
=> HELIO-3668 fix failing travis ci builds

app/views/e_pubs/show.html.erb, app/views/e_pubs/show_pdf.html.erb
Adds the parent press subdomain to #epub container, if a parent press exists, so that subpresses inherit ereader branding of their parent press.
=> HELIO-3307 - Allow subpresses to inherit parent press branding in PDF and EPUB ereaders

app/assets/stylesheets/application/heliotrope.scss, app/views/catalog/_facets.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, spec/features/press_catalog_facets_spec.rb
Resolves HELIO-3624 by adding a class to the div wrapping the access icons on the monograph catalog page, adjusting the CSS for the access icon legend box on publisher page, and lower cases the "All content" radio select text on the publisher page.
=> HELIO-3624 - Fix access icon display, access copy, and access legend box sizing

app/controllers/api/opds/v2/feeds_controller.rb, app/models/opds/publication.rb, app/models/sighrax/monograph.rb, spec/models/opds/publication_spec.rb, spec/models/sighrax/monograph_spec.rb, spec/requests/api/opds/V2/feeds_spec.rb
James English's team at SimplyE compiled this feedback on the work of HELIO-3483.
There are still some outstanding questions, and his answers my expand this ticket. But this much is clear:
[X] Replace relative URL /umpebc_oa with absolute https://www.fulcrum.org/api/opds/umpebc_oa.
Authors of OPDS 1.0/2.0 specs highly recommend to not use relative URLs.
[X] Publication’s metadata must include modified field. This field is required by Circulation Manager to be able to skip already processed items, i.e. it processes only publications which modified time is greater than the time when this publication was last processed. Without modified field is not able to process the feed correctly.
Follow formatting of examples at https://drafts.opds.io/opds-2.0:
"modified": "2015-09-29T17:00:00Z"
[X] …
=> Resolves HELIO-3677 Fix OPDS feed based on James English feedback

Gemfile.lock
The 0.6.0 release of yabeda-puma-plugin aggregates puma metrics properly
when in clustered / multi-worker mode. It requires no config changes in
the app, since we are already set up to use the DirectFileStore.
=> HELIO-3388 - Update yabeda-puma-plugin

spec/services/institution_report_service_spec.rb
Seems like circle ci didn't like something about those doubles maybe. This seems to work now.
=> Fix flapping spec

app/jobs/open_access_ebook_trust_job.rb, app/mailers/open_access_ebook_trust_mailer.rb, app/views/open_access_ebook_trust_mailer/send_report.html.erb, app/views/open_access_ebook_trust_mailer/send_report.text.erb, config/settings/development.yml, config/settings/test.yml, spec/jobs/open_access_ebook_trust_job_spec.rb, spec/mailers/open_access_ebook_trust_mailer_spec.rb, spec/rails_helper.rb
I've run this against production data, example in the ticket. Seems to work ok.
=> HELIO-3701 Send usage report emails to OAeBU Data Trust

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/embed/embed_styles.scss
Resolves HELIO-3656
Adds a background color behind the white play button to ensure it is visible regardless of the color contrast of the first frame of video. This applies to the embed view and the FileSet view.
=> HELIO-3656 - Customize AblePlayer play button

app/controllers/presses_controller.rb, app/models/sighrax/null_publisher.rb, app/models/sighrax/publisher.rb, app/policies/ebook_interval_download_operation.rb, app/views/monograph_catalog/_index_epub_toc.html.erb, app/views/presses/_form.html.erb, db/migrate/20210323134614_add_interval_to_presses.rb, db/schema.rb, spec/models/sighrax/null_publisher_spec.rb, spec/models/sighrax/publisher_spec.rb, spec/policies/ebook_interval_download_operation_spec.rb
Add interval to press table to explicitly support publishers that allow download of intervals (chapters).
=> Ebook Interval Download Operation Policy and Add Interval To Presses

package.json, yarn.lock
An update that addresses the wrong version of epubjs being in csb, https://github.com/mlibrary/cozy-sun-bear/commit/51b7e4e62be0e4b0afb6c43b08fbbc46de312204
Tested on staging with fixed-width, reflowable and pdf, all seem good.
=> update csb and csb-too to latest commits

app/controllers/fulcrum_controller.rb, app/jobs/license_delete_job.rb, app/models/monograph_search_builder.rb, app/views/fulcrum/_jobs.html.erb, spec/jobs/license_delete_job_spec.rb, spec/models/monograph_search_builder_spec.rb
HELIO-3900 Grants to the :none License cause confusion
HELIO-3916 File Representatives show in Resource list
License Delete job was added to the fulcrum/jobs page which will delete all greensub licenses of type 'Greensub::License' or empty string and their corresponding grants.
=> Hotfix 2.75.1 which includes HELIO-3900 and HELIO-3916

lib/tasks/cleanup/license_delete.rake
Rake task to be run daily by cron to cleanup :none licenses.
=> Rake task to cleanup :none licenses

app/controllers/application_controller.rb, app/controllers/fulcrum_controller.rb, app/jobs/seed_institution_affiliations_job.rb, app/models/greensub/institution.rb, app/models/greensub/institution_affiliation.rb, app/services/counter_service.rb, app/views/fulcrum/_institution_affiliations.html.erb, app/views/fulcrum/_institutions.html.erb, app/views/fulcrum/_jobs.html.erb, app/views/greensub/institution_affiliations/_form.html.erb, app/views/greensub/institution_affiliations/edit.html.erb, app/views/greensub/institution_affiliations/index.html.erb, app/views/greensub/institution_affiliations/new.html.erb, app/views/greensub/institution_affiliations/show.html.erb, app/views/greensub/institutions/index.html.erb, app/views/greensub/institutions/show.html.erb, config/settings/test.yml, spec/controllers/application_controller_spec.rb, spec/controllers/e_pubs_controller_spec.rb, spec/controllers/embed_controller_spec.rb, spec/controllers/hyrax/file_sets_controller_spec.rb, spec/jobs/seed_institution_affiliations_job_spec.rb, spec/models/greensub/institution_affiliation_spec.rb, spec/models/greensub/institution_spec.rb, spec/requests/api/v1/institutions_spec.rb, spec/requests/e_pubs_spec.rb, spec/requests/greensub/institutions_spec.rb
Replace all institution lookups by identifier (a.k.a. dlsp_institution_id) with institution lookups by dlsp_institution_id via the institution_affliations table.
Created HELIO-3977 to address current institution identifier usage in creating Counter Report data and logic in selecting the user's primary institution when there is more than one current institutions.
=> HELIO-3958: Institution containing dlps_institution_id

app/views/e_pubs/show.html.erb
Resolves HELIO-3976
Inject embedded resources CSS into all press instances using CSB, so that embedded resources can be used, if desired, in all EPUBs.
=> HELIO-3976 - Allow all presses to embed resources

app/models/greensub/institution.rb, app/views/fulcrum/_dashboard.html.erb, spec/controllers/e_pubs_controller_spec.rb, spec/models/greensub/institution_spec.rb, spec/requests/api/v1/institutions_spec.rb, spec/requests/greensub/institutions_spec.rb
The institution identifier is a dlps_institution_id which is an integer hence the added clause numericality: { only_integer: true } to validates identifier in the model.
=> Validate institution identifier is an integer

app/models/anonymous.rb, app/models/greensub/institution.rb, app/models/greensub/institution_affiliation.rb, app/models/greensub/license.rb, app/models/user.rb, app/policies/ebook_operation.rb, app/services/dlps_institution.rb, app/services/dlps_institution_affiliation.rb, config/initializers/services.rb, spec/models/anonymous_spec.rb, spec/models/user_spec.rb, spec/policies/ebook_operation_spec.rb, spec/services/dlps_institution_affiliation_spec.rb
Created dlps_institution_affiliation service (as inspired by dlps_institution service) to retrieve Greensub::InstitutionAffiliation records for the current user from request attributes.
Added intersection between license affiliations and actor affiliations for the licensed institution any? clause to ebook operations policy.
=> actor institution affiliations

app/policies/ebook_operation.rb, spec/controllers/e_pubs_controller_spec.rb, spec/policies/ebook_operation_spec.rb
Refactored licensed_for?(entitlement) in EbookOperation to handle world institution licenses (Settings.world_institution_identifier) to behave like individual licenses a.k.a. ignore affiliations.
=> licensed_for? world_institution

fulcrum/css/fulcrum_enhanced_display.css
Resolves HELIO-3970; styles open resource button to open on hover/focus of figure element that contains an image. Tested to ensure works with keyboard only use and assistive technology.
=> HELIO-3970 - style resource buttons to appear on hover of image/figure

app/assets/stylesheets/application/themes.scss
Resolves HELIO-3936
Adds height: auto to .navbar-brand for BAR publishing to ensure active and focus borders outline entire container.
=> HELIO-3936 - add auto height to bar brand logo

app/services/embed_code_service.rb, fulcrum/css/fulcrum_enhanced_display.css, spec/services/embed_code_service_spec.rb
HELIO-4048
Meaning only interactive maps use the button/modal embed style as
before. The new/beta troublesome styles for these in `./public`,
i.e. `./fulcrum/css/fulcrum_enhanced_display.css` are therefore no
longer needed.
=> use iframe embed codes for images

app/controllers/counter_reports_controller.rb, app/controllers/e_pubs_controller.rb, app/controllers/ebooks_controller.rb, app/controllers/monograph_catalog_controller.rb, app/controllers/press_catalog_controller.rb, app/overrides/hyrax/file_sets_controller_overrides.rb, spec/requests/wayfless_spec.rb
To verify the fix:
1. Go Incognito and not on VPN or campus.
2. Go to https://heliotrope-preview.hydra.lib.umich.edu/concern/monographs/kk91fm31s?locale=en&entityID=https://registry.shibboleth.ox.ac.uk/idp - It will redirect as expected.
3. Go to https://heliotrope-preview.hydra.lib.umich.edu/concern/monographs/kk91fm31s?locale=en&entityID=https://shibboleth.umich.edu/idp/shibboleth - It will redirect as expected.  
4. Authenticate @ umich.edu
5. Go to https://heliotrope-preview.hydra.lib.umich.edu/concern/monographs/kk91fm31s?locale=en&entityID=https://registry.shibboleth.ox.ac.uk/idp - It will redirect as expected.
=> Resolves HELIO-4101 WAYFless URLs should force authentication

app/assets/javascripts/application/ga_event_tracking.js, app/assets/stylesheets/application/themes.scss, app/views/e_pubs/_webgl_specific.html.erb
Resolves HELIO-4052
Adds fullscreen mode/standalone link to webgl panel; 
Adds GA event tracking for open/close 3d model and 3d model fullscreen mode
=> HELIO-4052 - Add an expand / full screen icon and event tracking to WebGL container

app/assets/stylesheets/application/themes.scss
Resolves HELIO-4106, part of hotfix 2.83.3 needing to be merged into master
=> HELIO-4106 - adjust text color for pagination buttons

app/presenters/hyrax/file_set_presenter.rb, spec/presenters/hyrax/file_set_presenter_spec.rb
=> don't show duration values only in milliseconds

config/jekyll.yml, config/sitemap.rb
See notes in HELIO-4105, we're no longer "saving" sitemaps in shared/sitemaps (public/sitemaps) since they are re-generated on every deploy and have been for some time now. They will now all live directly in /pubic. robots.txt has been updated to reflect this on the production deploy.
=> HELIO-4105 fix sitemap paths

Gemfile, Gemfile.lock
Everything we do with therubyracer is by way of ExecJS, and NodeJS is picked up
automatically. The libv8 that therubyracer depends on is quite old and there
are some compatibility/compilation problems, in addition to performance
implications. We rely on Yarn and webpack, anyway, so NodeJS is not a new
dependency.
=> HELIO-4120 - Remove therubyracer; depend on node being installed

app/assets/stylesheets/application/themes.scss
Resolves HELIO-4142
Adjust CSS rules for EBC, HEB, Lever, and Amherst so website footer rules do not apply to Ereader modal window footers.
=> HELIO-4142 - adjust CSS rules for EBC, HEB, Lever, Amherst

app/assets/stylesheets/embed/embed_styles.scss, app/presenters/concerns/embed_code_presenter.rb, app/views/hyrax/file_sets/media_display_embedded/_video.html.erb, spec/presenters/concerns/embed_code_presenter_spec.rb
HELIO-4167
PR number two for this issue (it had a previous hotfix v.2.87.1)
1) height is 300px for embedded captioned audio
2) always overlay embedded video captions
=> height for A/V embeds with captions/descriptions

config/locales/en.yml
Resolves HELIO-4172 
Add help text for visual descriptions and captions; remove help text for transcripts
=> HELIO-4172 - Update help text for Closed Captions, Visual Descriptions, and Transcripts

fulcrum/mozilla-pdf-viewer/build/pdf.js, fulcrum/mozilla-pdf-viewer/build/pdf.sandbox.js, fulcrum/mozilla-pdf-viewer/build/pdf.worker.js, fulcrum/mozilla-pdf-viewer/web/viewer.js
Small follow-up to pdf.js upgrade, just to stop the browser looking for non-existent map files.
Whether we begin minimizing our pdf.js and associated files is a discussion for another time.
=> remove sourceMappingURL lines

Gemfile, Gemfile.lock, app/services/aptrust/service.rb, app/services/handle_net.rb, app/services/restful_fedora/service.rb, app/services/restful_solr/service.rb, app/services/turnsole/service.rb, lib/e_pub/bridge_to_webgl.rb, spec/controllers/e_pubs_controller_spec.rb, spec/services/handle_net_spec.rb
Upgrade to new Handle_Rest gem and changes to HandleNet module to use new gem and create handles with admin value lines.
Going forward this should create url handles that are modifiable and deletable.  Previously made url handles will still be un-modifiable and un-deletable.
Once verified in production the admin value lines will have to be added to all the previously made url handles.  This would be most easily be done by executing an SQL script against the handle database directly by someone in A&E.
=> HELIO-3620 Handle Permission Bug Fix

app/assets/stylesheets/application/heliotrope.scss, app/views/epub_ebooks/_cozy_controls_notes.html.erb, app/views/epub_ebooks/_cozy_pdec_notes.html.erb
Resolves HELIO-4330, a sub-task of HELIO-3803.
Update historical character names that contain superscript (JS use of `textContent` was dropping formatting); adjust display of names with superscript; correct historical character names based on author input; and adjust definitions legend based on author input
=> HELIO-4330 - Update Notes Panel Content

app/views/hyrax/monographs/_show_actions.html.erb, app/views/hyrax/my/_work_action_menu.html.erb
by developers on the backend, so hide delete buttons in the UI for large monographs.
=> HELIO-4345 monographs with more than 200 file_sets need to be deleted

app/jobs/handle_job.rb, spec/jobs/handle_job_spec.rb
Hotfix relating to HELIO-4327. Currently running in production as [release 3.6.1](https://github.com/mlibrary/heliotrope/releases/tag/3.6.1).
Monograph handles fix was successful using this change.
=> bad has_model_ssim check breaks Monograph handles

app/assets/stylesheets/application/themes.scss
Resolves HELIO-3767
Belin to use same styles as FIA to maintain branding continuity between the two collections, which are part of the Frankel Institute.
=> HELIO-3767 - Style Belin

app/controllers/e_pubs_controller.rb, spec/controllers/e_pubs_controller_spec.rb
HELIO-4448
there will likely be another PR against this ticket at some future point to remove this change, which is purely to assist OCLC in diagnosing EZproxy causing issues with Chrome/Chromium 206 range request caching
=> serve one test pdf_ebook with browser caching

app/assets/javascripts/application_survey.js, app/views/e_pubs/show.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, app/views/monograph_catalog/index.html.erb, app/views/shared/_survey_modal_bigten.html.erb, app/views/shared/_survey_nonmodal_bigten.erb
Add big ten survey for display on monograph download or ereader view; set big ten survey specific cookies to control display of survey message.
=> FULCRUMOPS-360 - Add big ten open books ebook usage survey

app/assets/stylesheets/application/themes.scss
Removes access legend from DOM via CSS so it does not display on Big Ten's publisher catalog page.
=> HELIO-4474 - Suppress Legend on Big Ten Collection

app/presenters/hyrax/monograph_presenter.rb, spec/presenters/hyrax/monograph_presenter_spec.rb
@sethaj I think this stuff is OK to remove. was originally added for #2307 but have could (and later did) use PressHelper instead, which makes this kind of stuff available everywhere in the views.
Only serves to confuse and I almost started using these myself for Press-level content warnings in MonographPresenter.
This would be inefficient seeing PressHelper is available in all views.
=> remove Press cruft from MonographPresenter

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/common/heliotrope-content-warning.css, app/views/hyrax/file_sets/_media.html.erb, app/views/hyrax/file_sets/_media_embedded.html.erb, app/views/monograph_catalog/_index_monograph.html.erb, spec/features/create_monograph_spec.rb
- Adds styling to content warnings on monograph, fileset, and media embeds
- Adjusts monograph content warning display for accessibility issues (links did not provide keyboard focus, did not respond on enter keystroke). Removed inline JS and replaced with Bootstrap 3 collapse functions to resolve.
- Adjust spec to look for populated href attribute
=> HELIO-4496 - Style content warnings

app/controllers/roles_controller.rb, config/locales/en.yml, spec/controllers/roles_controller_spec.rb
HELIO-112
Specifically better flash[:alert] messages when the user_key (email) does not exist in the DB or when it points to a user with a preexisting role in the press.
=> HELIO-112 better flash[:alert] messages when adding roles

Gemfile, Gemfile.lock
Work around bundle install failure due to [this](https://github.com/dryruby/json-canonicalization/issues/2).
=> solve bundle failure due to yanked gem

fulcrum/_includes/footer.html
Resolves FOPS-475
Change copyright year to 2024 in the footer for the Fulcrum website.
=> Update copyright year in fulcrum footer

app/assets/stylesheets/application/heliotrope.scss, app/views/catalog/_constraints.html.erb, app/views/catalog/_constraints_element.html.erb
Resolves [HELIO-4578](https://mlit.atlassian.net/browse/HELIO-4578).
Modifies search results UI: 
- Changes the applied filter icon to use X to remove the filter and removes the dropdown caret
- Restores styling for constraint container and and changes start over button to a link
=> HELIO-4578 - Filtered results: change drop down icon to X 

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss
Resolves HELIO-4588.
Modifies CSS files to match resource facet card display to publisher facet display:
- fix resource facet display 
- update `page_links` selector to `page-links` so page links are styled properly across platform and themes 
- restore resource search button to have no left radius so it sits flush with search input box
=> HELIO-4588 - Match Resource facet display to Publisher facet display

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss, app/views/monograph_catalog/_index_monograph.html.erb, config/locales/blacklight.en.yml
Resolves [HELIO-4579](https://mlit.atlassian.net/browse/HELIO-4579)
Restore display of buttons and layouts for mobile/tablet devices:
- Press catalog: Tablet - Sort button height too tall
- Press catalog: Adjust break point for sort and per page dropdowns
- Press catalog: Tablet/mobile - Left column hides book title
- Lever Press/Amherst: Tablet/Mobile - Search bar positioning, alignment of nav menu, display of nav items
- Display order of Book Cover/Monograph Title on Mobile layout
=> HELIO-4579 - HELIO-4579 Tablet/Mobile fixes for Hyrax 4

app/assets/stylesheets/application/heliotrope.scss
Resolves fixup needed for HELIO-4580.
Makes resource thumbnail images in gallery view fluid/responsive to prevent overflow outside of document container.
=> HELIO-4580 - Fixup for Resource thumbnails in Gallery view

app/assets/stylesheets/application/heliotrope.scss, app/views/catalog/_facet_pagination.html.erb, spec/features/monograph_catalog_facets_spec.rb
Resolves items listed in HELIO-4577:
- Alignment of buttons in Facet More Modal windows
- Padding for breadcrumbs on smaller screens
- Height of share button in EReader
- Prevent Monograph Admin tools overlapping with breadcrumbs
=> HELIO-4577 - Hyrax 4: General Sitewide Issues

app/assets/stylesheets/application/heliotrope.scss, app/assets/stylesheets/application/themes.scss
Resolves items described in HELIO-4571.
Assorted site and press specific UI fixes: 
- Search and Browse books margin-top reduced; 
- Fix oversized external resource svg icons; 
- BAR facet link color restored; 
- Sussex list gallery icons; 
- MichELT header and buttons restored; 
- Add border below nav for various MPS and UMP subpresses; 
- break lines on long press titles in header; 
- make admin menu visible on dark banners
=> HELIO-4571 - Hyrax 4 Press Issues

app/assets/stylesheets/application/heliotrope.scss, app/views/shared/_survey_modal.html.erb, app/views/shared/_survey_modal_bigten.html.erb, app/views/shared/_survey_nonmodal.erb, app/views/shared/_survey_nonmodal_bigten.erb, app/views/shared/_survey_nonmodal_gabii.erb
Resolves HELIO-4601.
- Restore display of OA survey within EReader; 
- modify styles and display of survey for both monograph page and ereader; 
- make same changes to BTAA and Gabii specific versions of OA survey;
=> HELIO-4601 - Fix layout and display of Open Access Survey

app/views/hyrax/file_sets/_media.html.erb
HELIO-4604
The indentation changes kind of obfuscate the fix here, which was simply moving the following pre-existing stuff _above_ `<figure>`. See [comment on ticket](https://mlit.atlassian.net/browse/HELIO-4604?focusedCommentId=360968).
```
<% if @presenter.content_warning.present? %>
<div role="dialog" id="content-warning-media-consent" aria-label="Content Warning Consent Dialog">
<div id="content-warning-icon-text">
<%= image_tag "exclamation-triangle-fill.svg", alt: "Warning Icon", 'aria-hidden': "true" %><%= @presenter.content_warning %>
</div>
<div id="content-warning-buttons">
<input type="button" class="btn btn-primary" value="Go back" aria-label="Go back" onclick="history.back()" tabindex="0">
<input type="button" class="btn btn-primary" value="Display content" aria-label="Show …
```
=> HELIO-4604 put content warning outside figure, improve indent

app/controllers/catalog_controller.rb
=> HELIO-4611 add the www prefix to the oai base url to get

app/components/blacklight/response/view_type_button_component.html.erb, app/components/blacklight/response/view_type_button_component.rb, app/components/blacklight/response/view_type_component.html.erb, app/components/blacklight/response/view_type_component.rb, app/views/catalog/_search_results.html.erb, app/views/catalog/_view_type_group.html.erb, spec/features/monograph_catalog_search_spec.rb, spec/features/press_catalog_spec.rb
* We took on some components/blacklight/response/view_type* because of a couple of a11y changes we need like role and aria-selected
Since we're using new blacklight components for the "view_types" you can see that when a view_type is selected (ie: gallery vs. list) the icon is now greyed out as in this example below. Since gallery is default, the gallery icon reflects that it's selected. This is a change from what it looks like currently.
=> HELIO-4636 fix blacklight deprecation messages, keep a11y work

app/views/layouts/boilerplate.html.erb, app/views/layouts/csb_too_viewer.html.erb, app/views/layouts/csb_viewer.html.erb, app/views/layouts/embedded.html.erb, app/views/layouts/mozilla-pdf-viewer.html.erb
Added tag manager for production and preview (which was incomplete). On preview I've verified that tag manager is present on:
- Press catalog pages
- Monograph catalog pages
- FileSet show pages
- EPUB reader pages
- PDF reader pages
=> HELIO-4628 add google tag manager for production

app/controllers/press_catalog_controller.rb, app/models/auth.rb, app/models/sighrax/monograph.rb, app/policies/e_pub_policy.rb, app/policies/ebook_operation.rb, app/policies/ebook_reader_operation.rb, spec/models/auth_spec.rb, spec/models/sighrax/monograph_spec.rb
HELIO-4644
The purpose of this is to replace a few methods in auth.rb to make them faster. There shouldn't be any changes in functionality.
Previously "publisher_restricted_content?" and "subscribing_institutions" were getting all noids in a press from solr. Those lists of noids can get big and take a while to fetch. Then the list is put into a sql query via IN that can also be very large. This pattern will just get slower as more books are added to a press.
Instead of getting lists of noids, we'll get lists of products. Using the product ids, we can determine the question of "publisher_restricted_content?" and replace "subscribing_institutions(big_list_of_noids)" with "subscribing_institutions_from_product_ids(small_list_of_products)" and still get the same answers. This is possible …
=> HELIO-4644 authorization from products, not noid lists which can be slow

spec/requests/api/opds/V2/feeds_spec.rb
I don't think we need this spec at all.
=> Commenting out a spec that fails due to a missing external url.

app/controllers/counter_reports_controller.rb, app/services/scholarlyiq_redirect_url_service.rb, config/features.rb, config/scholarlyiq.yml.sample, spec/requests/counter_reports_spec.rb, spec/services/scholarlyiq_redirect_url_service_spec.rb
I've got this behind Flipflop with disabled by default. I've put it on preview, enabled and it's working there.
=> HELIO-4726 Forward users from /counter_reports to scholarlyiq

app/assets/stylesheets/application/heliotrope.scss
Resolves HELIO-4754
Adds an underline to links within the `.page-links` container, which hold the Next >> and << Previous links used for paging on the publisher catalog pages. This is applied across the default theme and will impact all publisher pages/themes.
=> HELIO-4754 - Distinguish Next >> Link from surrounding text

app/controllers/embed_controller.rb, spec/controllers/embed_controller_spec.rb
Tested this by adding the Content-Security-Policy in the Cloudflare dashboard and enabling the default security headers and it all works fine. As we predicted, Content-Security-Policy has precedence over X-Frame-Options.
=> HELIO-4792 Add explicit Content-Security-Policy header to response

app/presenters/hyrax/file_set_presenter.rb, spec/features/show_file_set_spec.rb
also check role and share link for visibility clause
HELIO-4278 (follow-up PR)
=> HELIO-4278 - no prev/next to expired permission resources

app/services/epub_accessibility_metadata_indexing_service.rb, spec/services/epub_accessibility_metadata_indexing_service_spec.rb
HELIO-4819
As of this morning, this is in production as release [4.15.1](https://github.com/mlibrary/heliotrope/releases/tag/4.15.1).
=> HELIO-4819 - fixes and updates to a11y metadata indexing

spec/models/opds/publication_spec.rb, spec/requests/api/opds/V2/feeds_spec.rb
This will likely be temporary until the JSON in https://readium.org/webpub-manifest/schema/metadata.schema.json is fixed.
=> HELIO-4823 Temp skip OPDS schema validation specs due to bad schema

spec/features/press_catalog_facets_spec.rb
Adding explicit names  to test objects fixes the problem.
=> HELIO-4855 Circle CI has a problem with this spec, it's ok locally.

.circleci/.force_rebuild, .circleci/config.yml
Merge before the latest round of dependabot PRs. Let's do this next sprint, after the 4.18 release.
=> HELIO-4752 CircleCI should use ruby 3.3.5
