- config/role_map.yml
> adds production section to role_map

- app/models/press.rb
- app/models/role.rb
- db/migrate/20160317214738_create_presses.rb
- db/migrate/20160317220736_create_roles.rb
- db/schema.rb
- lib/tasks/roles.rake
- spec/factories/presses.rb
- spec/factories/roles.rb
- spec/models/press_spec.rb
- spec/models/role_spec.rb
> Generate a press and role model

- config/deploy.rb
- config/initializers/curation_concerns.rb
> shares tmp dir & cc initializer, enables ffmpeg

- db/seeds.rb
* Update subdomain names for PSU & UMich
* Add configuration for Indiana, Northwestern, and Minnesota
> Add press configs for additional presses

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/aws.rb
- config/deploy/staging.rb
Uses mysql and puma for production deployments, allows cap deploy to michigan staging server as well as DCE sandbox.
> Deploy with capistrano and puma

- Vagrantfile
- bootstrap.sh
adds provisioning and fixes 184
> Vagrant changes: reduce default RAM setting; add provisioning script

- .gitignore
ignore OS X Directory Services files, RubyMine project dir
> ignore OS X Directory Services files, RubyMine project dir

- app/models/monograph.rb
- spec/models/monograph_spec.rb
> #76 Deleting a monograph should delete all its sections

- app/views/shared/_my_actions.html.erb
- spec/views/shared/_my_actions.html.erb_spec.rb
> manage users link shown only to certain privledged users

- Gemfile
- Gemfile.lock
- config/authorities/rights.yml
- config/initializers/simple_form.rb
- config/initializers/simple_form_bootstrap.rb
- config/locales/simple_form.en.yml
- db/migrate/20160427155928_create_operations.rb
- db/schema.rb
- lib/tasks/resque.rake
- lib/templates/erb/scaffold/_form.html.erb
> updated to curation concerns 14.0

- app/views/curation_concerns/file_sets/_form.html.erb
> multi-value fields for asset contributors and keywords, #154

- .travis.yml
- Gemfile
- Gemfile.lock
> added clamav to production

- .solr_wrapper
- lib/import.rb
- lib/import/csv_parser.rb
- lib/import/importer.rb
- lib/import/row_data.rb
- script/import
> Importer prevalidation 241

- app/controllers/monograph_catalog_controller.rb
- app/indexers/file_set_indexer.rb
- app/models/file_set.rb
- app/models/monograph_search_builder.rb
- app/models/solr_document.rb
- app/presenters/curation_concerns/file_set_presenter.rb
- app/presenters/curation_concerns/monograph_presenter.rb
- app/views/file_sets/_file_set.html.erb
- app/views/monograph_catalog/_index_header_list_file_set.html.erb
- app/views/monograph_catalog/index.html.erb
- config/routes.rb
- spec/features/create_file_set_spec.rb
- spec/features/create_monograph_spec.rb
- spec/features/create_section_spec.rb
- spec/features/show_monograph_spec.rb
- spec/features/show_section_spec.rb
- spec/indexers/file_set_indexer_spec.rb
- spec/models/monograph_search_builder_spec.rb
search results thumbnails and show route
monograph detail and add section assets to search results
section facets
monograph search builder test
add keyword facet
update tests
add section to file_set search results
Resolves #14
> monograph 'catalog' page, #14

- app/controllers/monograph_catalog_controller.rb
> fix for facet limit bug #278

- app/models/minter_state.rb
> placeholder for #292

- app/controllers/curation_concerns/file_sets_controller.rb
- spec/controllers/curation_concerns/file_sets_controller_spec.rb
> permission/visibility fixes for file_sets #272, #280

- app/indexers/section_indexer.rb
- app/models/monograph_search_builder.rb
- app/models/section.rb
- spec/indexers/section_indexer_spec.rb
> replace AF queries with solr in the monograph_search_builder, #290

- app/views/curation_concerns/file_sets/_show_actions.html.erb
> don't show asset download button if there asset can't be downloaded

- Gemfile
- Gemfile.lock
- app/controllers/robots_controller.rb
- config/robots/robots.development.txt
- config/robots/robots.production.txt
- config/robots/robots.staging.txt
- config/robots/robots.test.txt
- config/routes.rb
- public/robots.txt
- spec/routing/route_spec.rb
> different robots.txt files based on environment

- Gemfile
- Gemfile.lock
- app/helpers/markdown_helper.rb
- app/renderers/curation_concerns/renderers/markdown_attribute_renderer.rb
- app/renderers/renderers.rb
- app/services/markdown_service.rb
- app/views/catalog/_index_header_list_monograph.html.erb
- app/views/catalog/_index_monograph.html.erb
- app/views/curation_concerns/file_sets/_attribute_rows.html.erb
- app/views/curation_concerns/file_sets/_attribute_rows_info.html.erb
- app/views/curation_concerns/file_sets/_attribute_rows_permissions.html.erb
- app/views/curation_concerns/file_sets/_media.html.erb
- app/views/curation_concerns/file_sets/show.html.erb
- app/views/curation_concerns/monographs/_attribute_rows.html.erb
- app/views/curation_concerns/sections/_attribute_rows.html.erb
- app/views/curation_concerns/sections/show.html.erb
- app/views/monograph_catalog/_index_file_set.html.erb
- app/views/monograph_catalog/index.html.erb
- spec/renderers/curation_concerns/renderers/markdown_renderer_spec.rb
- spec/services/markdown_service_spec.rb
> add markdown support for some metadata fields

- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- config/routes.rb
- spec/routing/route_spec.rb
> disable user account creation in production, #266

- .rubocop_todo.yml
- app/indexers/file_set_indexer.rb
- app/presenters/curation_concerns/file_set_presenter.rb
- app/views/curation_concerns/file_sets/_attribute_rows_technical.html.erb
- app/views/curation_concerns/file_sets/_attributes.html.erb
- spec/indexers/file_set_indexer_spec.rb
> add technical metadata for the asset show page

- app/presenters/curation_concerns/file_set_presenter.rb
- app/views/curation_concerns/file_sets/_attribute_rows_info.html.erb
> section title is accessible from an asset show view

- .rubocop_todo.yml
- app/indexers/file_set_indexer.rb
- app/presenters/curation_concerns/file_set_presenter.rb
- app/views/curation_concerns/file_sets/_attribute_rows_info.html.erb
- app/views/curation_concerns/file_sets/_attribute_rows_permissions.html.erb
- app/views/curation_concerns/file_sets/show.html.erb
- spec/indexers/file_set_indexer_spec.rb
- spec/presenters/curation_concerns/file_set_presenter_spec.rb
> monograph metadata is accessible from within an asset presenter

- app/services/markdown_service.rb
- spec/services/markdown_service_spec.rb
> added strikethrough markdown support, #326

- app/controllers/monograph_catalog_controller.rb
- app/models/monograph_search_builder.rb
- config/routes.rb
> fixed 'more' link on keyword facets

- app/controllers/catalog_controller.rb
- app/controllers/monograph_catalog_controller.rb
> add resource_type facet

- app/controllers/monograph_catalog_controller.rb
- app/helpers/facet_helper.rb
- app/models/file_set.rb
> facets for assets/file_sets

- app/controllers/catalog_controller.rb
- app/forms/curation_concerns/monograph_form.rb
- app/models/monograph.rb
- app/models/solr_document.rb
- app/presenters/curation_concerns/monograph_presenter.rb
- app/views/curation_concerns/monographs/_attribute_rows.html.erb
- app/views/curation_concerns/monographs/_form_additional_information.html.erb
- app/views/monograph_catalog/index.html.erb
- config/locales/blacklight.en.yml
- config/locales/en.yml
- spec/forms/curation_concerns/monograph_form_spec.rb
change labels and field name for isbn_softcover, update ISBN display for monograph edit/show page, ensure all ISBNs display on monograph catalog page
> Change ISBN labels and enable ISBN display

- app/controllers/robots_controller.rb
> fix for robots, #170

- app/views/curation_concerns/monographs/_attribute_rows.html.erb
- lib/import.rb
- lib/import/csv_parser.rb
- lib/import/importer.rb
- lib/import/row_data.rb
- spec/lib/import/csv_parser_blanks_in_metadata_spec.rb
- spec/lib/import/csv_parser_spec.rb
- spec/lib/import/monograph_builder_spec.rb
> Import monograph metadata 321

- app/views/monograph_catalog/index.html.erb
> add buy URL button to monograph catalog view

- app/views/curation_concerns/file_sets/_attribute_rows_permissions.html.erb
> remove permissions badge from asset show page

- app/controllers/monograph_catalog_controller.rb
- app/controllers/press_catalog_controller.rb
- app/helpers/facet_helper.rb
- app/views/monograph_catalog/_facet_limit.html.erb
- config/routes.rb
> facet result more bug

- app/controllers/monograph_catalog_controller.rb
> change section sort order, #276

- app/views/shared/_site_search.html.erb
- spec/features/file_set_search_spec.rb
> search on the asset page should search its monographs's assets, #371

- app/models/monograph_search_builder.rb
- config/routes.rb
- spec/features/monograph_catalog_facets_spec.rb
> fixes a bug where facets where not showing up in the facet 'more' modal

- app/assets/javascripts/application.js
- app/assets/javascripts/disable_audio_download.js
- app/views/curation_concerns/file_sets/media_display/_audio.html.erb
> disable audio download by turning off right click on audio player

- config/initializers/resque_config.rb
- config/settings/development.yml
- config/settings/test.yml
> change resque_namespace per environment

- app/helpers/facet_helper.rb
- spec/helpers/facet_helper_spec.rb
> 341: Fixed bug in exclusivity_facet helper.

- app/controllers/curation_concerns/file_sets_controller.rb
- app/models/file_set.rb
- app/views/curation_concerns/file_sets/_form.html.erb
- lib/import.rb
> change cardinality/semi-colon splitting of some metadata

- app/views/curation_concerns/file_sets/_media.html.erb
> do not show quotes or brackets in alt text for media

- app/controllers/monograph_catalog_controller.rb
- spec/features/file_set_search_spec.rb
> modify monograph catalog controller to display captions, not descriptions

- app/models/riiif/file.rb
> close IO object after reading bugfix #416

- app/models/riiif/file.rb
- spec/models/riiif/file_spec.rb
> io error bugfix #416

- app/assets/javascripts/application.js
- app/assets/javascripts/disable_image_download.js
> disable right click over image object on asset page

- Gemfile
- Gemfile.lock
- app/presenters/curation_concerns/file_set_presenter.rb
- app/views/curation_concerns/file_sets/show.html.erb
- spec/presenters/curation_concerns/file_set_presenter_spec.rb
- spec/rails_helper.rb
- spec/views/curation_concerns/file_sets/show.html.erb_spec.rb
> 333 Page title for asset page

- db/seeds.rb
> modify nup press description to emphasize fulcrum is not nup's main website

- .fcrepo_wrapper
- app/controllers/monograph_catalog_controller.rb
- app/helpers/facet_helper.rb
- app/views/monograph_catalog/_custom_section_facet.html.erb
- spec/features/monograph_catalog_facets_spec.rb
> section facet should match section order in monograph's ordered_members

- app/helpers/press_helper.rb
- app/views/layouts/boilerplate.html.erb
- app/views/shared/_brand_press_footer.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_ga.html.erb
- app/views/shared/_header.html.erb
- db/migrate/20160822171245_add_google_analytics_to_press.rb
- db/schema.rb
- spec/helpers/press_helper_spec.rb
- spec/views/shared/_ga.html.erb_spec.rb
> add google analytics for fulcrum and per press

- db/seeds.rb
Resolves #443
Don't forget to run `rake db:seed` in deployment if it is important to see this change in staging and preview.
> adjust nup description per nup request

- app/services/markdown_service.rb
- spec/features/create_file_set_spec.rb
> allow non-breaking spaces, disallow code block formatting

- app/assets/javascripts/short_monograph_description.js
> 387 Markdown in monograph description

- config/fedora.yml
- config/solr.yml
To support multi-machine vagrant virtualbox development.
> Added environment variables SOLR_URL and FEDORA_URL to yml config files.

- app/views/curation_concerns/file_sets/_form.html.erb
> allow entry of multiple display dates

- config/initializers/riiif_initializer.rb
- lib/tasks/clean_cache.rake
> rake task to clean up IIIF files and tmp/uploads

- solr/config/schema.xml
Resolves #469 
After this PR is merged we need to contact A&E to reload the solr cores for staging, preview and production.
> Solr Suggester with build on commit causes stack overflows in Solr, #469

- lib/tasks/file_set_urls.rake
This relates to how we're going to temporarily approach #13
> rake task to get file_set paths and filenames for a given monograph

- app/controllers/downloads_controller.rb
Tiny change to match the Apache config for x-sendfile enabled downloads
> change to match apache configs

- lib/tasks/file_set_urls.rake
> add sections to the output of the file_set_urls rake task

- app/controllers/application_controller.rb
- app/controllers/curation_concerns/sections_controller.rb
- app/controllers/monograph_catalog_controller.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/monograph_catalog_controller_spec.rb
> Request for a non-existent monograph or section returns unauthorized response.

- app/helpers/markdown_helper.rb
- app/services/markdown_service.rb
- app/views/layouts/boilerplate.html.erb
- spec/services/markdown_service_spec.rb
> 497 Ampersand displayed in page title.

- app/views/curation_concerns/file_sets/show.html.erb
- spec/features/create_file_set_spec.rb
- spec/features/create_monograph_spec.rb
- spec/features/press_catalog_spec.rb
> Monograph contribs fileset view

- lib/import.rb
- lib/import/csv_parser.rb
- lib/import/importer.rb
- lib/import/row_data.rb
> tidy metadata warnings, don't warn on cover image

- app/assets/stylesheets/themes.scss
Closes #530 
add pseudo class selectors for aligning holding contact output with table row headings
> add pseudo class selectors for aligning holding contact

- app/presenters/curation_concerns/section_presenter.rb
- spec/presenters/curation_concerns/section_presenter_spec.rb
> no recursive representative presenter search for sections, see #537

- app/assets/stylesheets/themes.scss
> show entire minnesota logo in footer

- app/assets/stylesheets/heliotrope.scss
And added style to separate keywords by commas.
> Resolves #487: Changed display: inline to display: inline-flex.

- app/assets/stylesheets/themes.scss
bug fix to make the fulcrum links in the minnesota footer visible.
> fix fulcrum footer link colors

- .gitignore
- app/assets/stylesheets/heliotrope.scss
- app/renderers/curation_concerns/renderers/attribute_renderer.rb
- app/renderers/curation_concerns/renderers/markdown_attribute_renderer.rb
When label is empty span 2 columns.
> Resolves #524: Fixed indentation on description copy field.

- app/assets/stylesheets/themes.scss
> modify colors and font for pagination buttons and menu

- db/seeds.rb
so we can update on staging and preview
> add pennstate to production group 

- app/assets/javascripts/short_monograph_description.js
- app/views/monograph_catalog/index.html.erb
Created .short_description scss class for more/less behavior.
> Resolves #584: Remove More/Less from Asset Description.

- app/assets/stylesheets/heliotrope.scss
- app/assets/stylesheets/themes.scss
- app/views/curation_concerns/file_sets/show.html.erb
> style asset prev/next buttons; apply override styles for press themes;

- app/assets/stylesheets/heliotrope.scss
- app/assets/stylesheets/themes.scss
- app/views/curation_concerns/file_sets/show.html.erb
- app/views/layouts/boilerplate.html.erb
- app/views/monograph_catalog/index.html.erb
- app/views/press_catalog/_press_search.html.erb
- app/views/press_catalog/index.html.erb
- app/views/shared/_brand_fulcrum_footer_block.html.erb
- app/views/shared/_site_search.html.erb
Resolves #614 
Resolves #615 
Resolves #616 
Resolves #617 
Resolves #618 
Resolves #619
> resolves various accessibility issues with heliotrope

- spec/actors/curation_concerns/section_actor_spec.rb
- spec/features/catalog_search_spec.rb
- spec/features/create_file_set_spec.rb
- spec/features/create_section_spec.rb
- spec/features/edit_section_spec.rb
- spec/features/monograph_catalog_facets_spec.rb
- spec/features/press_catalog_spec.rb
- spec/lib/import/importer_spec.rb
- spec/lib/import/monograph_builder_spec.rb
- spec/models/file_set_spec.rb
- spec/models/monograph_spec.rb
- spec/spec_helper.rb
Reverts mlibrary/heliotrope#631
> Revert "clean repo between each spec"

- app/controllers/monograph_catalog_controller.rb
- app/helpers/facet_helper.rb
- app/renderers/curation_concerns/renderers/monograph_facet_attribute_renderer.rb
- app/views/curation_concerns/file_sets/_attribute_rows_info.html.erb
- spec/features/create_file_set_spec.rb
- spec/features/monograph_catalog_facets_spec.rb
> handle section titles w/markdown

- app/controllers/catalog_controller.rb
- app/controllers/monograph_catalog_controller.rb
- app/indexers/file_set_indexer.rb
- app/models/file_set.rb
- spec/factories/file_sets.rb
- spec/features/monograph_catalog_sort_spec.rb
> Sort monograph catalog by chapter/format/year

- app/views/curation_concerns/file_sets/_form.html.erb
- spec/fixtures/csv/import_sections/tempest_sections.csv
- spec/lib/import/csv_parser_spec.rb
> ensure language is multi-valued

- app/presenters/curation_concerns/monograph_presenter.rb
- spec/features/show_file_set_spec.rb
- spec/presenters/curation_concerns/monograph_presenter_spec.rb
> Prev/Next links for Monograph FileSets

- fulcrum/_posts/2016-12-22-year-end-update.markdown
- fulcrum/index.html
Add animal acts to the fulcrum home page and add blog post with year end update on project.
> Add Animal Acts to homepage and new blog post

- app/views/layouts/boilerplate.html.erb
- app/views/shared/_metadata.html.erb
- spec/views/shared/_metadata.html.erb_spec.rb
> Resolves #674 Add citation metadata for google scholar

- spec/features/create_file_set_spec.rb
I was able to slightly speed up this spec by making 2 changes:
1. Create the Monograph and Section records in let blocks
instead of creating them by interacting with the UI in the
body of the spec.  (Avoid extra routing and rendering work)
2. Instead of using Monograph.first.id (which reloads the
record), just use the monograph that we already have
in memory to find the ID.
> Refactored a feature spec to speed it up. Story #673

- app/assets/stylesheets/blacklight_facets.scss
- app/helpers/facet_helper.rb
- spec/controllers/monograph_catalog_controller_spec.rb
- spec/features/monograph_catalog_facets_spec.rb
- spec/helpers/facet_helper_spec.rb
> Resolves #693: Blacklight Helper Rspecs

- app/views/shared/_brand_press_footer_block_c.html.erb
- fulcrum/_includes/footer.html
Update copyright year in footer to 2017
> change copyright year to 2017

- .gitignore
- lib/import.rb
- spec/fixtures/csv/import_sections/tempest_sections.csv
- spec/lib/import/csv_parser_spec.rb
- spec/lib/import/monograph_builder_spec.rb
The importer splits monograph.subject on the semi-colon into an array
> Resolves #682 mongraph.subject should be multi-value

- app/assets/stylesheets/heliotrope.scss
- app/assets/stylesheets/themes.scss
- app/views/curation_concerns/file_sets/_media.html.erb
- app/views/curation_concerns/file_sets/media_display/_audio.html.erb
- app/views/curation_concerns/file_sets/media_display/_video.html.erb
- spec/features/create_file_set_spec.rb
> remove Able Player's interactive transcript

- app/controllers/catalog_controller.rb
- app/controllers/monograph_catalog_controller.rb
- app/indexers/file_set_indexer.rb
- app/indexers/monograph_indexer.rb
- spec/features/monograph_catalog_sort_spec.rb
- spec/indexers/file_set_indexer_spec.rb
> Blacklight sort by ordered members

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- spec/spec_helper.rb
> coveralls for test coverage

- Gemfile
- Gemfile.lock
- app/controllers/embed_controller.rb
- app/presenters/curation_concerns/file_set_presenter.rb
- app/services/handle_service.rb
- app/views/curation_concerns/file_sets/_show_actions.html.erb
- app/views/embed/show.html.erb
- config/application.rb
- config/routes.rb
- config/settings/development.yml
- config/settings/test.yml
- spec/controllers/embed_controller_spec.rb
- spec/features/press_catalog_spec.rb
- spec/presenters/curation_concerns/file_set_presenter_spec.rb
- spec/services/handle_service_spec.rb
- spec/views/curation_concerns/file_sets/show.html.erb_spec.rb
- spec/views/embed/show.html.erb_spec.rb
bare bones <html /> using asset handles
> Resolves#730: Embed code for video

- lib/import/importer.rb
> check that files are not zero-size

- app/presenters/curation_concerns/file_set_presenter.rb
- app/views/curation_concerns/file_sets/_show_actions.html.erb
- db/seeds.rb
- spec/controllers/embed_controller_spec.rb
- spec/presenters/curation_concerns/file_set_presenter_spec.rb
- spec/views/curation_concerns/file_sets/show.html.erb_spec.rb
Added 'heliotrope' press which is only available on development, staging, and preview.
> Resolves #786: Test Embed Code

- app/views/curation_concerns/file_sets/_show_actions.html.erb
Having the link open a new tab solved the problem.
> Resolves #810: Download doesn't work.

- spec/presenters/curation_concerns/file_set_presenter_spec.rb
This relates to how a specific test works for #786
> fixup for heliotrope press presenter test

- db/seeds.rb
Put things in alphabetical order and excluded presses not in production.
> db seeds refactoring

- fulcrum/_includes/footer.html
- fulcrum/_includes/header.html
> add login link to footer and responsive menu on fulcrum static pages

- lib/import/importer.rb
- lib/import/row_data.rb
> cover: squash row errors, find by id

- app/controllers/downloads_controller.rb
- app/views/curation_concerns/file_sets/_show_actions.html.erb
> don't play repo asset on download

- app/renderers/curation_concerns/renderers/multiline_attribute_renderer.rb
- app/views/curation_concerns/file_sets/_media.html.erb
- spec/renderers/curation_concerns/renderers/multiline_attribute_renderer_spec.rb
> new renderer to persist newlines

- fulcrum/index.html
> add pedelty/indiana project to the fulcrum homepage

- app/views/curation_concerns/file_sets/_media_embedded.erb
- app/views/embed/show.html.erb
- app/views/layouts/embedded.html.erb
- spec/views/embed/show.html.erb_spec.rb
> embed controller serves full-page assets for iframes

- app/assets/stylesheets/heliotrope.scss
- app/views/monograph_catalog/_index_gallery_file_set_wrapper.html.erb
- app/views/monograph_catalog/_thumbnail_file_set.html.erb
- spec/features/create_external_resource_spec.rb
> direct external resource links from monograph gallery

- app/assets/stylesheets/heliotrope.scss
- app/helpers/application_helper.rb
- app/presenters/curation_concerns/file_set_presenter.rb
- app/views/curation_concerns/file_sets/_attributes.html.erb
- app/views/curation_concerns/file_sets/_media.html.erb
- app/views/monograph_catalog/_index_gallery_file_set_wrapper.html.erb
- app/views/monograph_catalog/_thumbnail_file_set.html.erb
- spec/features/create_external_resource_spec.rb
> no image for external resources, tidy a little

- app/views/curation_concerns/file_sets/show.html.erb
- app/views/monograph_catalog/index.html.erb
- app/views/press_catalog/_index_header_list_monograph.html.erb
We'll need to do much more to get this right, the is just a temporary stop gap.
> first pass at editors, connected to #879

- app/assets/stylesheets/heliotrope.scss
- app/helpers/external_resource_helper.rb
- app/models/concerns/solr_document_extensions/file_set.rb
- app/views/monograph_catalog/_index_gallery_file_set_wrapper.html.erb
- app/views/monograph_catalog/_thumbnail_file_set.html.erb
- spec/features/external_resource_icons_spec.rb
> resource-type-based icons for external resources

- app/controllers/downloads_controller.rb
- app/controllers/e_pub_controller.rb
- app/indexers/monograph_indexer.rb
- app/models/monograph_search_builder.rb
- app/presenters/repository_presenter.rb
- config/initializers/riiif_initializer.rb
- spec/models/monograph_search_builder_spec.rb
> Fixes #869, ActiveFedora::SolrService deprecation warnings

- app/presenters/curation_concerns/monograph_presenter.rb
- app/views/monograph_catalog/index.html.erb
- app/views/press_catalog/_index_header_list_monograph.html.erb
- spec/features/monograph_catalog_search_spec.rb
- spec/presenters/curation_concerns/monograph_presenter_spec.rb
Branch was pushed to staging: https://heliotrope-staging.hydra.lib.umich.edu/heliotrope
> Resolves #890: Has EPub

- README.md
Does not necessarily close the ticket. Just a test that my git setup is sane.
> Fix small README.md typo.

- app/indexers/monograph_indexer.rb
- app/models/concerns/solr_document_extensions/monograph.rb
- app/models/monograph_search_builder.rb
- app/presenters/curation_concerns/monograph_presenter.rb
- spec/indexers/monograph_indexer_spec.rb
- spec/models/monograph_search_builder_spec.rb
- spec/models/solr_document_spec.rb
- spec/presenters/curation_concerns/monograph_presenter_spec.rb
Not truly sure when to append '.first' and when not to append '.first' but it passes the test.
> Resolves #889: Remove EPub from asset list

- app/views/dashboard/_books.html.erb
- app/views/dashboard/_home.html.erb
- app/views/dashboard/_items.html.erb
- app/views/dashboard/_sidebar.html.erb
D'oh! I created the branch and forgot to do an explicit Friday.
> Resolves #911 Platform Admin Dashboard.

- .rubocop_todo.yml
- app/models/riiif/file.rb
Tested in staging, everything looks fine.
> Resolves #938 frozen_string_literal riiif bug

- app/assets/javascripts/short_monograph_description.js
Slight tweak for nodeType 3, text node
> Resolves #954: Monograph description teaser tweak

- .rubocop_todo.yml
- app/controllers/presses_controller.rb
- app/models/ability.rb
- app/views/layouts/curation_concerns.html.erb
- app/views/presses/_form.html.erb
- app/views/presses/edit.html.erb
- app/views/presses/new.html.erb
- app/views/shared/_add_content.html.erb
- app/views/shared/_brand_press_jumbotron.html.erb
- app/views/shared/_my_actions.html.erb
- config/locales/simple_form.en.yml
- config/routes.rb
- spec/controllers/presses_controller_spec.rb
- spec/models/ability_spec.rb
> edit form for press

- Gemfile
- Gemfile.lock
- app/helpers/press_helper.rb
- app/models/press.rb
- app/presenters/curation_concerns/file_set_presenter.rb
- app/presenters/curation_concerns/monograph_presenter.rb
- app/uploaders/logo_path_uploader.rb
- app/views/presses/_form.html.erb
- app/views/shared/_brand_press_footer_block_a.html.erb
- app/views/shared/_brand_press_jumbotron.html.erb
- config/initializers/carrierwave.rb
- config/locales/en.yml
- spec/factories/presses.rb
- spec/features/create_press_spec.rb
- spec/helpers/press_helper_spec.rb
- spec/lib/import/importer_spec.rb
- spec/models/press_spec.rb
- spec/spec_helper.rb
- spec/views/shared/_ga.html.erb_spec.rb
> add/edit Publisher - CarrierWave logo upload, validations

- app/views/press_catalog/_press_search.html.erb
- config/locales/blacklight.en.yml
- config/routes.rb
- spec/features/create_collection_spec.rb
> various hyrax cleanups

- config/locales/en.yml
- spec/features/monograph_catalog_facets_spec.rb
Locales trumps labels!!!!
./config/locales/en.yml
> Resolves #975: Facet Resource Type Label

- app/views/hyrax/file_sets/media_display/_audio.html.erb
- app/views/hyrax/file_sets/media_display/_video.html.erb
partial media_display's local variable for presenter is 'file_set'
> Resolves #1014 Edit FileSet Page Video

- app/assets/stylesheets/heliotrope.scss
> Fix for #999 removing unwanted header whitespace.

- app/models/monograph.rb
class Monograph < ActiveFedora::Base
include ActiveFedora::Noid::Model
> Resolves #1021: Import Monograph Use NOID

- app/controllers/catalog_controller.rb
Manually added some code that normally would have been created by a hyrax generator.
> Fixes #1025, /dashboard/works error

- app/models/monograph.rb
- lib/import/importer.rb
- spec/lib/import/importer_spec.rb
- spec/lib/import/monograph_builder_spec.rb
Move ::Hyrax::Noid out of Monograph and into Importer.
> Resolves #1021 Import Monograph Should Use NOID

- README.md
- app/assets/stylesheets/application.css
- app/assets/stylesheets/heliotrope.scss
- app/assets/stylesheets/themes.scss
Resolves #967 
Resolves #1001 
fix font size of facets; 
fix h2 spacing on publisher page; 
adjust order of stylesheets in manifest; 
remove hydra mention in README;
fix icon size for external resources:
add spacing between applied facets box and drop down menus on monograph page:
> UI fixes for hyrax

- app/controllers/application_controller.rb
- bin/setup
- spec/features/login_logout_spec.rb
Travis now builds /public via Jekyll on bin/setup.
> Resolves #894, Resolves #909, User login/logout routing

- fulcrum/about.html
- fulcrum/index.html
Addresses #974 for static pages.
> Rebrand Hydra to Samvera in static HTML pages.

- config/initializers/file_set_actor_create_content.rb
- lib/import/importer.rb
- lib/import/monograph_builder.rb
- spec/lib/import/importer_spec.rb
> refactored importer

- spec/features/create_asset_spec.rb
- spec/features/create_monograph_spec.rb
Sleep 2 sigh, there has to be a better way.
> capybara create monograph and asset feature specs

- app/views/fulcrum/_publishers.html.erb
- config/routes.rb
- script/import
- spec/services/analytics_service_spec.rb
... and a little bit of refactoring.
> Resolves #1020: Fix to publisher edit, subdomain, and monograph links

- app/assets/javascripts/application.js
> disable CSB temporarily for IE11

- app/controllers/catalog_controller.rb
- app/controllers/monograph_catalog_controller.rb
- app/controllers/press_catalog_controller.rb
- spec/features/press_catalog_spec.rb
> order monographs by date_uploaded desc

- app/views/presses/_form.html.erb
- app/views/shared/_brand_press_footer_block_c.html.erb
- spec/features/create_press_spec.rb
> default (blank) footer_block_c behavior

- db/publishers.yml
- db/seeds.rb
Created a publishers.yml file inside of the db directory.
> Resolves #986: Investigate db:seed rake task

- app/presenters/hyrax/file_set_presenter.rb
- app/views/hyrax/file_sets/_media_embedded.erb
- app/views/layouts/embedded.html.erb
- spec/presenters/hyrax/file_set_presenter_spec.rb
- spec/views/embed/show.html.erb_spec.rb
> embed: -caption +video poster

- app/controllers/e_pub_controller.rb
- app/jobs/e_pub_service_job.rb
- app/services/e_pub_service.rb
- app/services/e_pub_service_error.rb
- spec/jobs/e_pub_service_job_spec.rb
- spec/services/e_pub_service_spec.rb
For this first pass at caching just unzip the epubs.
> Resolves #1012: Cache EPubs

- .gitignore
- .rubocop.yml
- Gemfile
- Gemfile.lock
- lib/tasks/ci.rake
- ruumba/.ruumba.yml
Embedded Ruby Preprocessor for Rubocop 
Currently all cops that detected an error are disabled in the ./ruumba/.rummba.yml file
to be continued...
> ruumba configured but disabled

- app/assets/javascripts/application.js
- app/assets/javascripts/application/ableplayer_transcript.js
- app/assets/javascripts/common.js
- app/views/hyrax/file_sets/media_display/_audio.html.erb
- app/views/hyrax/file_sets/media_display/_video.html.erb
- app/views/layouts/boilerplate.html.erb
- vendor/assets/javascripts/ableplayer_turbolinks.js
> JS order; Able Player anchors browser back

- app/forms/heliotrope/file_set_edit_form.rb
- app/models/concerns/solr_document_extensions/file_set.rb
- app/models/file_set.rb
- app/presenters/hyrax/file_set_presenter.rb
- app/views/hyrax/file_sets/_attribute_rows_info.html.erb
- app/views/hyrax/file_sets/_form.html.erb
- config/locales/en.yml
- lib/metadata_fields.rb
- spec/features/edit_file_set_spec.rb
- spec/models/solr_document_spec.rb
> Resolves #1108 'Add a redirection control field to FileSets'.

- app/controllers/hyrax/downloads_controller.rb
- app/views/hyrax/file_sets/_media_embedded.erb
- app/views/hyrax/file_sets/media_display/_video.html.erb
- config/settings/test.yml
- spec/controllers/hyrax/downloads_controller_spec.rb
> video poster attribute derivative

- app/assets/stylesheets/application/heliotrope.scss
Resolves #1122 Pagination Next Arrow Bug.
> Resolves 1122 pagination next arrow bug.

- app/views/hyrax/file_sets/_media.html.erb
> turn off Turbolinks caching for Leaflet page

- Gemfile
- Gemfile.lock
- app/controllers/e_pubs_controller.rb
- app/jobs/e_pubs_index_job.rb
- app/jobs/e_pubs_service_job.rb
- app/services/e_pubs_index_service/chapter.rb
- app/services/e_pubs_index_service/chapters.rb
- app/services/e_pubs_index_service/e_pub.rb
- app/services/e_pubs_index_service/sql_lite.rb
- app/services/e_pubs_search_service.rb
- app/views/e_pubs/show.html.erb
- config/routes.rb
- spec/controllers/e_pubs_controller_spec.rb
- spec/jobs/e_pubs_service_job_spec.rb
- spec/services/e_pubs_index_service/chapters_spec.rb
- spec/services/e_pubs_index_service/epub_spec.rb
- spec/services/e_pubs_index_service/sql_lite_spec.rb
Resolves #1131
Resolves #1132
Resolves #1078
> epub search api and epub reader integration

- .rubocop.yml
- app/presenters/concerns/isbn_presenter.rb
- app/presenters/concerns/title_presenter.rb
- app/presenters/hyrax/monograph_presenter.rb
- app/views/monograph_catalog/index.html.erb
- config/locales/en.yml
- spec/factories/ability.rb
- spec/factories/hyrax/monograph_presenter.rb
- spec/factories/solr_document.rb
- spec/presenters/concerns/isbn_presenter_spec.rb
- spec/presenters/concerns/title_presenter_spec.rb
- spec/presenters/hyrax/monograph_presenter_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
I deploy this branch to staging so you can compare staging with preview.
> Refactor of views/monograph_catalog/index to use i18n.t.

- Gemfile
- Gemfile.lock
> updating cozy-sun-bear to HEAD

- lib/tasks/ga_cache.rake
The should fix the inaccurate GA counts once it goes into production.
> Resolves #1106, The GA cache can have more than 10,000 results

- app/assets/stylesheets/application/themes.scss
- app/views/e_pubs/show.html.erb
Resolves #1182 
Resolves #1118 
Add styles for NYU's EPUB Reader; display logo in EPUB Reader for NYUP
> add branding for NYU Press EPUBs in EPUB Reader

- app/controllers/hyrax/downloads_controller.rb
- app/helpers/press_helper.rb
- app/models/monograph_search_builder.rb
- app/presenters/repository_presenter.rb
- spec/controllers/hyrax/downloads_controller_spec.rb
> safe navigation operator avoids errors

- app/views/hyrax/file_sets/_media_embedded.erb
> fix best-fit Leaflet in embed view

- app/presenters/hyrax/file_set_presenter.rb
- spec/presenters/hyrax/file_set_presenter_spec.rb
- spec/views/hyrax/file_sets/show.html.erb_spec.rb
module Hyrax
class FileSetPresenter
def allow_embed?
current_ability.platform_admin?
end
> Enable allow_embed? for platform_admin

- app/controllers/hyrax/file_sets_controller.rb
- spec/controllers/hyrax/file_sets_controller_spec.rb
- spec/features/edit_file_set_spec.rb
> simple redirection for FileSets

- README.md
- app/controllers/e_pubs_controller.rb
- spec/controllers/e_pubs_controller_spec.rb
render plain: EPubsService.factory(params[:id]).read(params[:file] + '.' + params[:format]), content_type: Mime::Type.lookup_by_extension(params[:format]), layout: false
adding the content_type solved the issue
> Resolves #1194 Styles in CSB

- lib/import/csv_parser.rb
- lib/import/importer.rb
- lib/import/row_data.rb
> make errors easier to consume/format

- app/services/e_pubs_service.rb
- lib/e_pub.rb
- lib/spec/lib_helper.rb
Deployed to staging...
https://heliotrope-staging.hydra.lib.umich.edu/concern/monographs/kp78gg43w?locale=en
> lib e_pub require dependency

- app/assets/javascripts/application.js
- app/assets/javascripts/common.js
- app/assets/javascripts/embed.js
- app/assets/stylesheets/embed/embed_styles.scss
- app/presenters/hyrax/file_set_presenter.rb
- spec/fixtures/csv/import_sections/.~lock.tempest_sections.csv#
- spec/presenters/hyrax/file_set_presenter_spec.rb
- vendor/assets/javascripts/ableplayer_embed.js
> embed: overlay/hide Able Player's controls

- app/controllers/hyrax/monographs_controller.rb
- app/jobs/curation_concern_update_index_job.rb
- app/views/monograph_catalog/_index_epub.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/hyrax/monographs_controller_spec.rb
- spec/jobs/curation_concern_update_index_job_spec.rb
Yea! Quick and easy reindexing for a monograph.
> Resolves #1229: Monograph Reindex Button

- README.md
- app/controllers/e_pubs_controller.rb
- app/presenters/hyrax/file_set_presenter.rb
- app/services/e_pubs_service.rb
- app/services/factory_service.rb
- config/initializers/mcsv.rb
- lib/e_pub/cache.rb
- lib/e_pub/publication.rb
- lib/e_pub/publication_null_object.rb
- lib/mcsv.rb
- lib/mcsv/manifest.rb
- lib/mcsv/manifest_null_object.rb
- lib/spec/e_pub/publication_null_object_spec.rb
- lib/spec/e_pub/publication_spec.rb
- lib/spec/mcsv/manifest_null_object_spec.rb
- lib/spec/mcsv/manifest_spec.rb
- lib/spec/mcsv_spec.rb
- lib/spec/valid_spec.rb
- lib/valid.rb
- spec/presenters/hyrax/file_set_presenter_spec.rb
- spec/services/e_pubs_service_spec.rb
- spec/services/factory_service_spec.rb
I moved some stuff around so it looks bigger than it is actually.  
The meat is here: app/services/factory_service.rb
> Resolves #1238 Factory for lib objects

- .fcrepo_wrapper
- .wrap_conf/fcrepo_dev
- .wrap_conf/fcrepo_test
- app/indexers/monograph_indexer.rb
- app/jobs/characterize_job.rb
- app/models/concerns/solr_document_extensions/monograph.rb
- app/models/monograph_search_builder.rb
- app/presenters/hyrax/monograph_presenter.rb
- spec/indexers/monograph_indexer_spec.rb
- spec/jobs/characterize_job_spec.rb
- spec/models/monograph_search_builder_spec.rb
- spec/models/solr_document_spec.rb
Select the first FileSet that is a Comma Separated Values file as the manifest.
> Resolves #1235 Monograph Representative Manifest CSV

- app/views/hyrax/file_sets/_media_embedded.html.erb
- app/views/hyrax/file_sets/media_display/_video.html.erb
reload Leaflet map on page load
don't preload videos, only their metadata
turn off Leaflet scrollWheelZoom
> embed loading changes; rename template

- app/controllers/hyrax/downloads_controller.rb
- spec/controllers/hyrax/downloads_controller_spec.rb
> platform admins can always download files

- app/views/e_pubs/show.html.erb
> No Turbolinks cache for EPUB reader

- fulcrum/index.html
> add NYUP to homepage

- app/assets/stylesheets/embed/embed_styles.scss
- app/presenters/hyrax/file_set_presenter.rb
- app/views/hyrax/file_sets/_media_embedded.html.erb
- spec/views/embed/show.html.erb_spec.rb
> embed view links back to Fulcrum asset

- .floo
- .flooignore
- README.md
> Greg's Floobits for RubyMine configuration

- .floo
- .flooignore
Removal of .floo and .flooignore then added to Greg's global .ignore file.
> floobits cleanup

- ruumba/.ruumba.yml
This is just a tiny PR that will hopefully make #1212 easier to work on.
> Adding a comment to .ruumba.yml about unapplicable cops

- app/presenters/hyrax/monograph_presenter.rb
- app/views/monograph_catalog/_index_epub.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
- config/locales/en.yml
- spec/presenters/hyrax/monograph_presenter_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
> Resolves #1287 Remove Media Tab On Catalog Page If No Assets

- app/presenters/hyrax/monograph_presenter.rb
- app/views/monograph_catalog/_index_epub.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
- config/locales/en.yml
- spec/presenters/hyrax/monograph_presenter_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
Thanks you all!  Conor, Jon, Seth, and everyone else today at Friday's bug hunt.
> 1253 monograph catalog media link problem

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application/themes.scss
- app/views/e_pubs/show.html.erb
Update CSB; add fullscreen icon; small fixes to heb and nyu csb themes
> CSB update

- app/presenters/hyrax/file_set_presenter.rb
Will require reindex for content imported pre-Hyrax
> post-Hyrax Solr file_size field

- app/assets/stylesheets/application/themes.scss
> modify navbar to match acls new website design

- app/assets/stylesheets/application/heliotrope.scss
- app/controllers/hyrax/downloads_controller.rb
- app/presenters/hyrax/file_set_presenter.rb
- app/views/hyrax/file_sets/_media.html.erb
- app/views/hyrax/file_sets/_show_actions.html.erb
- spec/controllers/hyrax/downloads_controller_spec.rb
- spec/presenters/hyrax/file_set_presenter_spec.rb
- spec/views/hyrax/file_sets/_media.html.erb_spec.rb
- spec/views/hyrax/file_sets/show.html.erb_spec.rb
> 1309 move download button

- app/assets/stylesheets/embed/embed_styles.scss
See comments on ticket. Branch is running on preview.
> change styles to reenable k/b preferences

- app/assets/javascripts/application/cookie_alert.js
- app/assets/stylesheets/application/heliotrope.scss
- app/views/layouts/boilerplate.html.erb
- app/views/shared/_cookie_alert.html.erb
> Resolves #811, add 'Site Requires Cookies Enabled' message for users

- Gemfile
- Gemfile.lock
- Rakefile
- config/sitemap.rb
- fulcrum/robots.txt
Note to self: will need an update to the crontab via `sudo -u heliotrope-XYZ crontab -e` if and when site mapper is deployed.
> Add sitemap for SEO (#1107).

- app/views/hyrax/file_sets/_media_embedded.html.erb
- app/views/hyrax/file_sets/media_display/_video.html.erb
> mark transcript as subtitles

- fulcrum/404.html
- fulcrum/422.html
- fulcrum/500.html
I've tested this on staging and it's working fine.
> Fixes #1324, move error pages to where rails expects them to be

- Gemfile.lock
- app/actors/create_with_import_files_actor.rb
- app/actors/heliotrope_actor.rb
- config/initializers/hyrax_actor_factory.rb
- config/initializers/hyrax_callbacks.rb
- lib/import/importer.rb
- spec/actors/create_with_import_files_actor_spec.rb
Request to pull onto hyrax2.rc1
> Resolves #1311: Add Import And Heliotrope Actors To Stack

- app/views/hyrax/file_sets/_attribute_rows_orphan_fileset.erb
- app/views/hyrax/file_sets/_form.html.erb
- app/views/hyrax/file_sets/_orphan_fileset.erb
- app/views/hyrax/file_sets/show.html.erb
- app/views/shared/_site_search.html.erb
> orphan FileSet edit/show pages

- app/controllers/monograph_catalog_controller.rb
- spec/controllers/monograph_catalog_controller_spec.rb
> monograph catalog access control

- README.md
Resolves #1325 
Please read, review and provide feedback on what is missing or could be taken out. FWIW, it is much easier to read at https://github.com/mlibrary/heliotrope/tree/docs/readme
Wiki pages that have been updated in relation to the README:
https://github.com/mlibrary/heliotrope/wiki/EPUB-Reader
https://github.com/mlibrary/heliotrope/wiki/How-to-Contribute
> Updates to the README to be more community friendly

- Gemfile
- Gemfile.lock
- app/views/e_pubs/show.html.erb
Resolves #1361 
Adds `aria-label`s and `labels` where needed to meet WCAG2.0A guidelines.
> various accessibility fixes for cozy-sun-bear

- spec/spec_helper.rb
filter out spec, lib/spec, and config folders
> coveralls wear add filter

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application/heliotrope.scss
- app/views/e_pubs/show.html.erb
> add updated navigation slider to e-reader footer

- app/assets/stylesheets/application/heliotrope.scss
> add in margin-top on breadcrumb bar after losing it in hyrax 2

- Gemfile
- Gemfile.lock
fix for paging out of chapters with many iframes
> CSB remove ratio hack

- app/views/e_pubs/show.html.erb
> add ga tracking code to CSB epub view

- app/assets/javascripts/application/ga_event_tracking.js
- app/views/hyrax/file_sets/media_display/_leaflet_image.html.erb
> Leaflet usability and tracking changes

- app/assets/stylesheets/embed/embed_styles.scss
> fix Safari (webkit) play button

- app/views/hyrax/file_sets/media_display/_video.html.erb
- app/views/hyrax/file_sets/media_display_embedded/_video.html.erb
> trying no preload attribute

- app/helpers/press_helper.rb
- app/views/layouts/boilerplate.html.erb
- spec/helpers/press_helper_spec.rb
> Resolves 1383, Allow child publisher to inherit parent publisher theme

- app/assets/stylesheets/embed/embed_styles.scss
- vendor/assets/javascripts/ableplayer_embed.js
> simplify Able Player tweaks

- app/helpers/breadcrumbs_helper.rb
- app/views/hyrax/file_sets/show.html.erb
- app/views/monograph_catalog/index.html.erb
- app/views/shared/_breadcrumbs.html.erb
- spec/helpers/breadcrumbs_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
Did some refactoring. Breadcrumbs are more complicated now :disappointed: but are tested.
> Resolves #1384, modify breadcrumbs for child publisher's views

- Gemfile
- Gemfile.lock
> Fixes #1450 Large file uploads are very slow

- app/assets/stylesheets/application/heliotrope.scss
- app/presenters/hyrax/file_set_presenter.rb
- app/services/file_sets_controller_behavior.rb
- app/views/hyrax/file_sets/_thumbnail.html.erb
- app/views/hyrax/file_sets/edit.html.erb
- spec/controllers/hyrax/file_sets_controller_spec.rb
> FileSet thumbnail upload

- app/views/e_pubs/show.html.erb
- app/views/layouts/boilerplate.html.erb
> Legacy support (for cozy-sun-bear)

- .rubocop_todo.yml
- app/models/concerns/solr_document_extensions/monograph.rb
- app/presenters/hyrax/monograph_presenter.rb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/webgls/_tab.html.erb
> Resolves #1465, and adds a webgl tab to monograph catalog page

- Gemfile
- Gemfile.lock
> Update cozy-sun-bear with legacy browser support and fixed layout fixes

- app/presenters/hyrax/file_set_presenter.rb
- app/renderers/hyrax/renderers/file_size_attribute_renderer.rb
- app/views/hyrax/file_sets/_attribute_rows_technical.html.erb
- config/locales/en.yml
- spec/renderers/hyrax/renderers/file_size_attribute_renderer_spec.rb
> human-readable file size on tech info tab

- Gemfile
- Gemfile.lock
- app/views/e_pubs/show.html.erb
CSB changed the way citations are done, see:
https://github.com/mlibrary/cozy-sun-bear/wiki/Metadata-and-Citations
> Resolves #1523, new CSB ref and no citation for now

- app/assets/javascripts/application/heliotrope_flot_stats.js
- app/presenters/concerns/cc_analytics_presenter.rb
- app/presenters/hyrax/file_set_presenter.rb
- app/presenters/hyrax/monograph_presenter.rb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/monograph_catalog/_stats.html.erb
- config/locales/en.yml
- spec/factories/monographs.rb
- spec/presenters/concerns/cc_analytics_presenter_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
> line graph of monograph pageviews over time

- app/assets/javascripts/application/heliotrope_flot_stats.js
- app/assets/stylesheets/application/heliotrope.scss
- app/presenters/concerns/cc_analytics_presenter.rb
- app/presenters/hyrax/file_set_presenter.rb
- app/views/hyrax/file_sets/_attribute_rows_stats.html.erb
- app/views/hyrax/file_sets/_attributes.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/monograph_catalog/_stats.html.erb
- config/locales/en.yml
- spec/presenters/concerns/cc_analytics_presenter_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
> stats graphs for FileSet page

- Gemfile
- Gemfile.lock
> update csb to latest version that uses CFI for location tracking

- app/assets/stylesheets/application/heliotrope.scss
- app/views/e_pubs/show.html.erb
Following Jon's advice on locating by search widget, and adding Roger's suggested border.
> Resolves 1367 Remove E-book Reader's Footer.

- app/views/monograph_catalog/_facet_limit.html.erb
Looking for 'monograph_id' in params first then 'id' seems to fix the issue.
> Resolves #1548: Network Error

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- lib/devise/strategies/http_header_authenticatable.rb
- spec/features/sign_in_out_spec.rb
- spec/lib/devise/http_header_authenticatable_spec.rb
Only allow login for users listed in the Users table.
> Resolves #1576: User whitelist for cosign

- app/views/monograph_catalog/_index_monograph.html.erb
Taking Conor's suggested fix after chasing my tail for a while.
> Addresses #1560 character encoding problem in Aboutware.

- app/models/press_search_builder.rb
- spec/features/press_catalog_spec.rb
> show child presses' monographs on parent's catalog

- Gemfile
- Gemfile.lock
Update CSB to latest ref; updates include search UX improvements, jquery cleanup, and CSB now emits a resized event when the browser is resized.
> update cozy sun bear

- app/assets/javascripts/application/heliotrope_flot_stats.js
> check #usage-stats exists before drawing

- app/views/e_pubs/show.html.erb
Resolves #1587 
Resolves #1588 
Also updates the 3D model description text.
> dynamic resizing of webgl canvas; modify 3D model description text

- app/views/e_pubs/show.html.erb
- app/views/webgls/_tab.html.erb
- app/views/webgls/show.html.erb
> NOP error handlers for UnityLoader

- app/assets/javascripts/unity_progress_heliotrope.js
- app/views/e_pubs/show.html.erb
- app/views/webgls/_tab.html.erb
- app/views/webgls/show.html.erb
- config/initializers/assets.rb
> 'fix' default progress bar

- app/views/e_pubs/show.html.erb
- app/views/webgls/_tab.html.erb
- app/views/webgls/show.html.erb
Various bug fixes with resizing; reverts mobile detection; adds needed functions to monograph 3d model tab to break keyboard trapping; 
Also, resolves #1622
> Webgl/bug fixes and loading WebGL on e-reader init

- app/views/webgls/_tab.html.erb
shouldn't link to the epub paragraph (for now) but to a handle
> Resolves #1641 3D Model links to text in 'standalone' mode

- app/controllers/application_controller.rb
- app/controllers/e_pubs_controller.rb
- app/helpers/application_helper.rb
- app/models/entity.rb
- app/models/user.rb
- app/presenters/concerns/featured_representatives/file_set_presenter.rb
- app/views/e_pubs/_form.html.erb
- app/views/e_pubs/lock.html.erb
- app/views/featured_representatives/_form.html.erb
- app/views/hyrax/base/_items.html.erb
- app/views/hyrax/base/_member.html.erb
- app/views/products/_lessees.html.erb
- app/views/shared/_brand_bar.html.erb
- app/views/shared/_brand_press_bar.html.erb
- app/views/shared/_institutions.html.erb
- app/views/shared/_my_actions.html.erb
- config/locales/en.yml
- config/routes.rb
- lib/devise/strategies/http_header_authenticatable.rb
- spec/controllers/e_pubs_controller_spec.rb
- spec/features/monograph_catalog_sort_spec.rb
- spec/models/authentication_spec.rb
- spec/models/entity_spec.rb
- spec/presenters/concerns/featured_representatives/file_set_presenter_spec.rb
- spec/views/shared/_add_content.html.erb_spec.rb
- spec/views/shared/_my_actions.html.erb_spec.rb
This branch has been deployed to staging for your testing convenience.
The EPUB under this monograph: https://heliotrope-staging.hydra.lib.umich.edu/concern/monographs/dv13zt26k is a component of the "Gabii Instituion" product and is being leased by institution "1" which is the ann arbor campus.  Hence you should be able to view the EPUB without logging into Fulcrum on staging.
The EPUB under this monograph: https://heliotrope-staging.hydra.lib.umich.edu/concern/monographs/rj4304596 is a component of the "Gabii Friends" product and is being leased by "gkostin@umich.edu" which is me!  Hence you should not be able to view the EPUB even after logging into Fulcrum on staging.  In fact, when you try to view the EPUB you should be redirected to the CoSign login.  After logging in you'll be …
> Resolves #1541: Restrict the Gabii EPUB

- app/assets/javascripts/common/heliotrope_mobile_user.js
- app/views/e_pubs/show.html.erb
- app/views/layouts/boilerplate.html.erb
- app/views/webgls/_tab.html.erb
- app/views/webgls/show.html.erb
> don't load WebGL for mobile users

- app/controllers/webgls_controller.rb
- spec/controllers/webgls_controller_spec.rb
> .unityweb files are already gzipped

- Gemfile
- Gemfile.lock
- config/initializers/services.rb
Pick up released version of Keycard with read-only mode. We defer to the
configuration loaded from settings for whether Keycard should be
read-only.
> Fix #1653 - Update Keycard and rails-html-sanitizer

- app/views/shared/_institutions.html.erb
- app/views/shared/_my_actions.html.erb
Leaving code, but commented out.
> Addresses #1665 Remove Switch Language Dropdown.

- app/assets/stylesheets/application/heliotrope.scss
- app/controllers/e_pubs_controller.rb
- app/views/e_pubs/access.html.erb
Resolves #728 
NOTE: There are some hardcoded things in here that are not good, but I figure once we have a new restricted resource we can revisit that. I left a set of TODO's for work after Gabii, but this should cover what we need for March 29.
> create a basic login options page to be used for gabii

- app/models/institution.rb
- app/views/fulcrum/_institutions.html.erb
Was trying to link to a nil lessee in fulcrum institution partial.
> Resolves #1670: [BUG] Errors when creating Institutions

- lib/tasks/monograph_urls.rake
> add EPUB representative epub_path URL

- app/forms/hyrax/monograph_form.rb
- app/models/monograph.rb
- app/presenters/hyrax/monograph_presenter.rb
- app/views/hyrax/monographs/_csb_hyrax_citations.html.erb
- app/views/hyrax/monographs/show.html.erb
- app/views/monographs/edit_fields/_publisher.html.erb
- config/initializers/hyrax.rb
- config/locales/en.yml
- spec/forms/hyrax/monograph_form_spec.rb
- spec/models/monograph_spec.rb
- spec/presenters/hyrax/monograph_presenter_spec.rb
> use Hyrax CitationsBehavior

- app/models/press_search_builder.rb
- spec/features/press_catalog_spec.rb
> downcase subdomain param

- .gitignore
- .yardopts
- Gemfile
- Gemfile.lock
- lib/.yardopts
$ bundle exec yardoc
./doc
$ cd lib; bundle exec yardoc; cd ..
./lib/doc
> yard for doc

- app/assets/stylesheets/application/heliotrope.scss
- app/views/e_pubs/show.html.erb
Resolves #1759 
remove backticks in epub show page for IE11 compatibility; modify share widget style to fix button height display in IE11
> Fix CSB in IE11

- app/jobs/unpack_job.rb
- lib/e_pub/publication.rb
- lib/e_pub/sql_lite.rb
- lib/e_pub/sql_lite_null_object.rb
- lib/e_pub/validator.rb
- spec/jobs/unpack_job_spec.rb
See #1692, this is the first part of that epic.
We're creating alternate paths to caching/unpacking epub and webgl content.
> Created an UnpackJob for unpacking epubs.

- app/views/shared/_skip_links.html.erb
NO TURBOLINKS!!! and class="skip" move to anchor so CSS works now.
> Fixes screen reader and keyboard cues for skip link

- app/jobs/unpack_job.rb
- spec/jobs/unpack_job_spec.rb
> Added webgl support for the unpack job

- app/jobs/unpack_job.rb
- app/services/unpack_service.rb
- lib/e_pub/bridge_to_webgl.rb
- lib/e_pub/publication.rb
- lib/e_pub/sql_lite.rb
- lib/e_pub/validator.rb
- lib/spec/e_pub/bridge_to_webgl_spec.rb
- lib/spec/e_pub/publication_spec.rb
- spec/jobs/unpack_job_spec.rb
- spec/services/unpack_service_spec.rb
- spec/spec_helper.rb
> The UnpackJob should create the epub-webgl mapping when it needs to.

- app/assets/stylesheets/application/heliotrope.scss
- app/views/shared/_skip_links.html.erb
The css wasn't working.  Now it sort of works.
> This works a bit better but not yet right.

- lib/tasks/unpack_assets.rake
> Created a rake task that will unpack all existing epub/webgls

- app/models/concerns/solr_document_extensions/monograph.rb
- app/presenters/hyrax/monograph_presenter.rb
- app/views/e_pubs/show.html.erb
> EPUB reader citation control

- app/helpers/breadcrumbs_helper.rb
- app/views/hyrax/monographs/show.html.erb
- spec/helpers/breadcrumbs_spec.rb
> add breadcrumbs to monograph show page

- app/views/e_pubs/show.html.erb
> link CSB press logo to press catalog

- app/presenters/hyrax/file_set_presenter.rb
- app/views/embed/show.html.erb
- app/views/layouts/embedded.html.erb
- spec/presenters/hyrax/file_set_presenter_spec.rb
> a11y: iframe titles

- app/assets/javascripts/application/ga_event_tracking.js
- app/views/e_pubs/access.html.erb
- app/views/hyrax/file_sets/_media.html.erb
- app/views/hyrax/file_sets/_show_actions.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/press_catalog/_index_header_list_monograph.html.erb
- app/views/shared/_locale_picker.html.erb
- app/views/shared/_survey.html.erb
- spec/features/edit_file_set_spec.rb
- spec/views/hyrax/file_sets/_media.html.erb_spec.rb
<form action="https://www.gkostin.com">
<button type="submit" formtarget="_blank" class="btn btn-default">Open New Window</button>
</form>
> Resolves #1752: Code button as html button

- app/controllers/monograph_manifests_controller.rb
- app/jobs/update_monograph_job.rb
- config/locales/en.yml
- spec/jobs/update_monograph_job_spec.rb
- spec/models/manifest_spec.rb
First iteration of updating an existing monograph's metadata via the importer.
> Resolves HELIO-1812: Metadata Download/Upload/Update Cycle

- lib/e_pub/publication.rb
- lib/e_pub/search.rb
- lib/e_pub/validator.rb
- lib/spec/e_pub/publication_spec.rb
- lib/spec/e_pub/search_spec.rb
- lib/spec/e_pub/validator_spec.rb
(Search for "america")
This isn't totally perfect yet, but I'd like to get this work into the next release so heb ingested epubs will be indexed correctly in sqlite. (if it doesn't make it this release it's not the end of the world).
> HELIO-1511 epub search for "fixed width"/"page image" epubs

- app/controllers/e_pubs_controller.rb
- app/models/concerns/solr_document_extensions/universal.rb
- app/models/counter_report.rb
- app/presenters/hyrax/file_set_presenter.rb
- app/presenters/hyrax/monograph_presenter.rb
- app/services/counter_reporter_service.rb
- app/services/counter_service.rb
- app/services/downloads_controller_behavior.rb
- app/services/file_sets_controller_behavior.rb
- db/migrate/20180605172532_create_counter_reports.rb
- db/schema.rb
- spec/controllers/e_pubs_controller_spec.rb
- spec/factories/counter_reports.rb
- spec/models/counter_report_spec.rb
- spec/models/solr_document_spec.rb
- spec/services/counter_service_spec.rb
I believe this will gather the stats we need for HELIO-1800, https://tools.lib.umich.edu/jira/browse/HELIO-1376?focusedCommentId=898167&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-898167
> HELIO-1376 COUNTER report stats gathering

- app/indexers/monograph_indexer.rb
- app/models/concerns/solr_document_extensions/monograph.rb
- app/models/monograph_search_builder.rb
- app/presenters/hyrax/file_set_presenter.rb
- app/presenters/hyrax/monograph_presenter.rb
- spec/indexers/monograph_indexer_spec.rb
- spec/models/monograph_search_builder_spec.rb
- spec/models/solr_document_spec.rb
- spec/presenters/hyrax/file_set_presenter_spec.rb
There are no representative manifest in production so nothing needs to be purged from Fedora.
> Resolves HELIO-1885 Purge Representative Manifest

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/views/sessions/new.html.erb
- config/application.rb
- config/routes.rb
- config/settings/development.yml
- config/settings/test.yml
- fulcrum/_includes/footer.html
- spec/controllers/sessions_controller_spec.rb
- spec/features/sign_in_out_spec.rb
Removed cosign logout redirect.
> Resolves HELIO-1845 Unable to logout in production

- spec/controllers/e_pubs_controller_spec.rb
rspec double for presenter needed to respond to :id message
> fix to master build

- app/views/monograph_catalog/_index_epub_toc.html.erb
This is already in production as 2.12.1
> Only fixed width/page image epub chapters should be downloadable

- lib/e_pub/chapter.rb
- lib/tasks/remove_chapter_cache.rake
HELIO-1916 page images are scaled to fit Letter (minus a 50px margin)
> HELIO-1915 chapter download page size is now Letter (8.5x11)

- .rubocop_todo.yml
- app/assets/stylesheets/application/heliotrope.scss
- app/assets/stylesheets/application/themes.scss
- app/controllers/presses_controller.rb
- app/helpers/press_helper.rb
- app/views/presses/_form.html.erb
- app/views/shared/_brand_press_footer_block_b.html.erb
- app/views/shared/_brand_press_jumbotron.html.erb
- db/migrate/20180625100512_add_footer_block_to_presses.rb
- db/migrate/20180625100532_add_location_to_presses.rb
- db/migrate/20180625100542_add_twitter_to_presses.rb
- db/publishers.yml
- db/schema.rb
- spec/helpers/press_helper_spec.rb
Adds new fields to the presses database;
Modify views to incorporate display of new fields; 
Add spec check for footer links and set exceptions for press helper and html_safe
Resolves [HELIO-1924](https://tools.lib.umich.edu/jira/browse/HELIO-1924) and [HELIO-1925](https://tools.lib.umich.edu/jira/browse/HELIO-1925)
> Capture new information about a publisher to display on publisher catalog page

- Gemfile
- Gemfile.lock
- app/views/monograph_catalog/_index_epub_toc.html.erb
- spec/rails_helper.rb
- spec/spec_helper.rb
- spec/system/toc_epub_chapter_spec.rb
Includes a spec that clicks on a ToC chapter link from the monograph
catalog page and opens that chapter in CozySunBear.
> HELIO-1914 chrome-headless Rails 5.1 system specs

- app/controllers/shibboleths_controller.rb
- config/routes.rb
Fixes login routing error in non-production env a.k.a. development env.
Note: ShibbolethsController is only used in development to provide mock Shibboleth routes.
> Shibboleth Login Bug Fix

- app/controllers/api/application_controller.rb
- app/controllers/api/v1/lessees_controller.rb
- app/controllers/api/v1/products_controller.rb
- app/controllers/api_requests_controller.rb
- app/controllers/fulcrum_controller.rb
- app/models/api_request.rb
- app/views/api_requests/index.html.erb
- app/views/api_requests/show.html.erb
- app/views/fulcrum/_logs.html.erb
- app/views/fulcrum/_sidebar.html.erb
- config/routes.rb
- db/migrate/20180706182443_create_api_requests.rb
- db/schema.rb
- script/api/lackey.rb
- script/request
- script/spec/api/lackey_spec.rb
- spec/controllers/api_requests_controller_spec.rb
- spec/factories/api_requests.rb
- spec/models/api_request_spec.rb
- spec/requests/api_requests_spec.rb
The branch has been deployed to heliotrope-testing.  
Below is an example of calling ./script/request which makes a call to the api to list the lessees.
[gkostin@nectar ~]$ cd /hydra-dev/heliotrope-testing/current
[gkostin@nectar current]$ bundle exec ./script/request -l -b heliotrope-testing.hydra.lib.umich.edu/api eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imdrb3N0aW5AdW1pY2guZWR1IiwicGluIjoiZmt3N2hfblZ4cGxYZXRSTCJ9.eSAeVrllTOtM5Vuq0M0fwhL0_uyATzk7tQvSD7MrH70
{:parser=>HTTParty::Parser, :format=>:json, :base_uri=>"http://heliotrope-testing.hydra.lib.umich.edu/api", :headers=>{:authorization=>"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imdrb3N0aW5AdW1pY2guZWR1IiwicGluIjoiZmt3N2hfblZ4cGxYZXRSTCJ9.eSAeVrllTOtM5Vuq0M0fwhL0_uyATzk7tQvSD7MrH70", :accept=>"application/json, …
> Resolves HELIO-1732: API Audit Log

- Gemfile
- Gemfile.lock
- app/controllers/api_requests_controller.rb
- app/models/api_request.rb
- app/views/api_requests/index.html.erb
> will_paginate

- app/assets/stylesheets/application/heliotrope.scss
Resolves HELIO-1949; adding media queries for sort and filter display in smaller screen sizes.
> styles for mobile views of gallery

- lib/tasks/purge_metadata.rake
- script/request
Rake task to purge unused metadata from fulcrum.org's fedora instance.
> Purge Metadata Rack Task

- app/controllers/authentications_controller.rb
- app/controllers/e_pubs_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/shibboleths_controller.rb
- app/views/e_pubs/access.html.erb
- config/application.rb
- config/routes.rb
- config/settings.yml
- lib/devise/strategies/keycard_authenticatable.rb
- spec/lib/devise/keycard_authenticatable_spec.rb
There are detailed comments in each of these commits about these fixes to the login/logout process. This is now functional for development as well as in production with a proxy and real SP in place.
> Fix up Shibboleth login

- app/controllers/application_controller.rb
- app/models/user.rb
- spec/rails_helper.rb
Revert back to CoSign for release 2.15
> CoSign Login

- app/controllers/application_controller.rb
- app/models/user.rb
- spec/rails_helper.rb
> Shibboleth Login

- lib/devise/strategies/keycard_authenticatable.rb
Cosign Login with user_key hack
> cosign user_key hack

- app/assets/stylesheets/application/heliotrope.scss
- app/views/e_pubs/access.html.erb
> customize for ACLS login options

- app/assets/javascripts/idpselect/idpselect.js
- app/assets/javascripts/idpselect/idpselect_config.js
./app/assets/javascripts/idpselect/idpselect.js
};
idpEntryDiv.appendChild(a);
-        buildHelpText(idpEntryDiv);
+        // buildHelpText(idpEntryDiv);
parentDiv.appendChild(idpEntryDiv);
};
> Resolves HELIO-2010: Remove Help link from Shib Login Options

- app/controllers/e_pubs_controller.rb
- app/controllers/webgls_controller.rb
- app/presenters/concerns/featured_representatives/monograph_presenter.rb
- app/views/e_pubs/show.html.erb
- app/views/monograph_catalog/_index_epub_toc.html.erb
- app/views/webgls/_tab.html.erb
- lib/e_pub/toc.rb
- lib/e_pub/validator.rb
- ruumba/.ruumba.yml
Minor refactor, Minor fix to cfi link, and Minor fix to toc
> Resolves HELIO-1966: Display complete TOC

- app/controllers/sessions_controller.rb
- app/views/e_pubs/access.html.erb
- app/views/shared/_brand_fulcrum_footer_block.html.erb
- app/views/shared/_footer.html.erb
- spec/controllers/sessions_controller_spec.rb
- spec/features/sign_in_out_spec.rb
Uugh!!! TurboLinks!!!!  ... Deployed to preview for your reviewing convenience.
> Resolves Resolves HELIO-2019: Login_Redirect_Bug_Fix_Fix

- app/controllers/e_pubs_controller.rb
- lib/e_pub/publication.rb
- lib/spec/e_pub/publication_spec.rb
- spec/controllers/e_pubs_controller_spec.rb
This is on staging and seems to be working fine.
> HELIO-1692 x-sendfile for epub files

- app/indexers/monograph_indexer.rb
- spec/features/press_catalog_sort_spec.rb
> more sort normalization

- app/views/layouts/boilerplate.html.erb
> mobile Safari offers to call ISBNs

- app/controllers/hyrax/batch_uploads_controller.rb
- app/forms/hyrax/forms/batch_upload_form.rb
> get batch create Monographs to work

- app/controllers/catalog_controller.rb
- spec/features/press_catalog_search_spec.rb
> allow all creators to be searched

- app/views/press_catalog/index.html.erb
<div></div> doesn't scale but <div>&nbsp;</div> does!
> Resolves HELIO-2006: Book Count Overlap Bug

- app/helpers/hyrax/citations_behaviors/title_behavior.rb
- spec/helpers/hyrax/citations_behaviors/title_behavior_spec.rb
> non-word hyphens: no errors or removal

- app/presenters/e_pub_presenter.rb
- app/views/monograph_catalog/_index_epub_toc.html.erb
- lib/e_pub/rendition.rb
- lib/e_pub/section.rb
- lib/e_pub/unmarshaller/chapter.rb
- lib/spec/e_pub/rendition_spec.rb
- lib/spec/e_pub/section_spec.rb
- lib/spec/e_pub/unmarshaller/chapter_spec.rb
- spec/presenters/e_pub_presenter_spec.rb
> HELIO-1882 Restrict chapter downloads to DIV TYPE="chapter"

- app/controllers/catalog_controller.rb
- app/controllers/monograph_catalog_controller.rb
- app/controllers/press_catalog_controller.rb
- app/indexers/file_set_indexer.rb
- app/indexers/monograph_indexer.rb
- spec/controllers/monograph_catalog_controller_spec.rb
- spec/features/monograph_catalog_facets_spec.rb
- spec/features/press_catalog_spec.rb
- spec/indexers/file_set_indexer_spec.rb
- spec/indexers/monograph_indexer_spec.rb
Resolves HELIO-2082; Requires reindex
> all creators should be facetable

- app/presenters/hyrax/file_set_presenter.rb
- app/views/hyrax/file_sets/media_display/_leaflet_image.html.erb
- app/views/hyrax/file_sets/media_display_embedded/_leaflet_image.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/press_catalog/_index_gallery_monograph_wrapper.html.erb
- app/views/press_catalog/_thumbnail_list_monograph.html.erb
- vendor/assets/javascripts/leaflet-iiif_1.2.1_best_fit.js
> image-service: break browser caching

- app/assets/stylesheets/application/heliotrope.scss
- app/views/monograph_catalog/_index_epub_toc.html.erb
> Add markup and style new outline for monograph catalog TOC

- app/models/counter_report.rb
- app/services/counter_service.rb
- db/migrate/20180910133110_add_press_to_counter_reports.rb
- db/schema.rb
- lib/tasks/add_press_to_counter_record.rake
- spec/services/counter_service_spec.rb
Code is on staging, tested the rake task, all looks good.
> HELIO-2133 Add press to counter report table

- app/models/featured_representative.rb
- app/presenters/concerns/featured_representatives/monograph_presenter.rb
- spec/models/featured_representative_spec.rb
- spec/presenters/concerns/featured_representatives/monograph_presenter_spec.rb
> add peer_review featured representative

- app/models/concerns/heliotrope_hyrax_user_behavior.rb
- config/application.rb
- config/initializers/hyrax.rb
- spec/system/batch_create_monographs_spec.rb
> overwrite find_or_create_system_user

- app/forms/hyrax/monograph_form.rb
- config/authorities/licenses.yml
- spec/features/create_monograph_spec.rb
- spec/forms/hyrax/monograph_form_spec.rb
> add license to monograph form

- app/presenters/hyrax/monograph_presenter.rb
- app/views/monograph_catalog/_index_monograph.html.erb
- spec/features/create_monograph_spec.rb
- spec/presenters/hyrax/monograph_presenter_spec.rb
> CC icons for monographs

- lib/import/csv_parser.rb
> add unexpected column warning

- app/assets/stylesheets/application/themes.scss
Resolves HELIO-2130, adds needed styles for Lever Press on Fulcrum
> HELIO-2130 - add styles, colors, fonts for Lever Press

- fulcrum/index.html
modifies homepage link to lever press to point to fulcrum instance of lever press.
> HELIO-2175 - change lever press link

- app/views/e_pubs/show.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
Resolves HELIO-2179, HELIO-2180
> remove Gabii payment messages

- app/models/concerns/solr_document_extensions/file_set.rb
- app/models/file_set.rb
- app/presenters/hyrax/file_set_presenter.rb
- spec/models/solr_document_spec.rb
> rights_granted_creative_commons final clean up

- app/assets/javascripts/idpselect/typeahead.js
- app/views/e_pubs/access.html.erb
Comment out set focus on typeahead control.
> Possible solution to screen reader issue

- app/controllers/counter_reports_controller.rb
- app/services/counter_reporter_service.rb
- app/views/counter_reports/without_customer_id/index.html.erb
- app/views/counter_reports/without_customer_id/show.html.erb
- spec/services/counter_reporter_service_spec.rb
The code is still green and procedural but that will change as more counter reports are added.
> HELIO-2170 Create Book Requests (TR_B1) COUNTER Report

- Gemfile
- Gemfile.lock
Update CSB to use current version that includes event tracking and scaling abilities
> HELIO-2203 - update CSB

- app/assets/stylesheets/application/themes.scss
- app/views/e_pubs/show.html.erb
add styles to brand lever press titles in the ereader; enable display of lever press logo in ereader
> HELIO-2202 - brand lever press ereader

- app/controllers/counter_reports_controller.rb
Temporarily exclude the tr_t1 report.
> COUNTER tr_t1 unacceptably slow in production

- lib/export/exporter.rb
- lib/tasks/edit_monographs_output_csv.rake
- lib/tasks/edit_monographs_via_csv.rake
> tasks to edit multiple monographs

- app/views/hyrax/base/_guts4form.html.erb
Copied _guts4form.html.erb from Hyrax and commented out "Share" tab code.
> Resolves HELIO-1826: Remove Monograph Form Share Tab

- app/controllers/counter_reports_controller.rb
- app/services/counter_reporter_service.rb
- spec/services/counter_reporter_service_spec.rb
Still procedural and "green" but no longer really, really slow.
> HELIO-2217 fixes performance issues with COUNTER report tr_b1

- app/presenters/concerns/citable_link_presenter.rb
- app/services/handle_service.rb
- config/locales/en.yml
- spec/features/create_monograph_spec.rb
- spec/presenters/concerns/citable_link_presenter_spec.rb
- spec/presenters/hyrax/file_set_presenter_spec.rb
- spec/presenters/hyrax/monograph_presenter_spec.rb
- spec/services/handle_service_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
- spec/views/shared/_metadata.html.erb_spec.rb
Changed http to https for handles and doi urls.
> https handle service

- app/assets/stylesheets/application/heliotrope.scss
- app/presenters/hyrax/monograph_presenter.rb
- app/views/e_pubs/show.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/shared/_altmetric_dimensions.html.erb
- app/views/shared/_metadata.html.erb
Resolves HELIO-2105
Adds Altmetric and Dimensions badges to monograph catalog page and e-reader. Required addition to monograph presenter to strip formats from ISBNs.
> Resolves HELIO-2105 - add altmetric and dimensions badges

- Gemfile
- Gemfile.lock
Resolves HELIO-2235 and incorporates fixes for CSB-188 CSB-190 and CSB-191
> HELIO-2235 - update csb

- app/controllers/monograph_manifests_controller.rb
> HELIO-1482: batch creation workflow

- app/services/permission_service.rb
- spec/services/permission_service_spec.rb
Interface to manipulate checkpoint's permit table.
> Resolves HELIO-2228: Permission Service

- app/views/monograph_catalog/index.html.erb
Resolves HELIO-2236
Updates HEB's DLXS message to reflect new shutdown date of December 2018.
> HELIO-2236 - change HEB message on monograph catalog

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application/heliotrope.scss
- app/views/e_pubs/show.html.erb
- config/settings/development.yml
Resolves HELIO-2237
add heliotrope mobile queries for csb; mobile close button in e-reader; modify checkpoint dev default config to false
> HELIO-2237 - update csb gem

- app/views/hyrax/file_sets/_media.html.erb
> Resolves HELIO-1985: Scroll Transcript via Keyboard

- app/controllers/fulcrum_controller.rb
- app/controllers/users_controller.rb
- app/models/component.rb
- app/models/user.rb
- app/views/fulcrum/_component.html.erb
- app/views/fulcrum/_components.html.erb
- app/views/fulcrum/_individual.html.erb
- app/views/fulcrum/_individuals.html.erb
- app/views/fulcrum/_institution.html.erb
- app/views/fulcrum/_institutions.html.erb
- app/views/fulcrum/_lessees.html.erb
- app/views/fulcrum/_policies.html.erb
- app/views/fulcrum/_product.html.erb
- app/views/fulcrum/_products.html.erb
- app/views/fulcrum/_publisher.html.erb
- app/views/fulcrum/_publishers.html.erb
- app/views/fulcrum/_sidebar.html.erb
- app/views/fulcrum/_user.html.erb
- app/views/fulcrum/_users.html.erb
- app/views/fulcrum/index.html.erb
- app/views/fulcrum/show.html.erb
- app/views/users/_form.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
- config/routes.rb
- spec/controllers/fulcrum_controller_spec.rb
- spec/requests/users_spec.rb
> Resolves HELIO-2254: Fulcrum Partials Show Views

- app/services/permission_service.rb
- app/views/fulcrum/_components.html.erb
- lib/tasks/migrate_permissions.rake
- spec/services/permission_service_spec.rb
> Resolves HELIO-2256: Refactor Migrate Permissions Task

- app/controllers/components_controller.rb
- app/controllers/users_controller.rb
- app/models/component.rb
- app/models/user.rb
- app/services/noid_service.rb
- app/views/fulcrum/_component.html.erb
- app/views/fulcrum/_components.html.erb
- app/views/fulcrum/_individuals.html.erb
- app/views/fulcrum/_users.html.erb
- db/migrate/20181024194504_add_fields_to_components_table.rb
- db/schema.rb
- lib/tasks/migrate_permissions.rake
- spec/services/noid_service_spec.rb
Now Products, Components, Individuals, and Institutions all have identifier and name attributes.
> Resolves HELIO-2262: Add identifier, name, and noid to components table

- app/views/hyrax/base/_guts4form.html.erb
> HELIO-2263 - 'fix' divs

- config/locales/heliotrope.en.yml
- lib/metadata_fields.rb
> 'Representative Kind' column description

- db/migrate/20181026193044_add_indexes_to_counter_reports.rb
- db/schema.rb
> HELIO-2265 add indexes to the counter_reports table

- app/assets/stylesheets/embed/embed_styles.scss
> HELIO-1984 k/b nav video controls

- lib/devise/strategies/keycard_authenticatable.rb
Hot fix which assumes that 'users' are affliated with UofM by unique id or friends account.
> Resolves HELIO-2274: Fix HEB Admin access to dashboard

- app/indexers/monograph_indexer.rb
- lib/tasks/edit_monographs_output_csv_isbn.rake
- lib/tasks/edit_monographs_output_csv_noid.rake
- lib/tasks/edit_monographs_via_csv_isbn.rake
- lib/tasks/edit_monographs_via_csv_noid.rake
- spec/indexers/monograph_indexer_spec.rb
> edit Monographs by ISBN

- Gemfile
- Gemfile.lock
Notes on this are in HELIO-2318.
> HELIO-2318 Update Rack

- lib/metadata_fields.rb
- spec/fixtures/csv/import_sections/tempest_sections.csv
- spec/lib/import/csv_parser_spec.rb
- spec/lib/import/importer_spec.rb
> yes_split section_title on semi-colon

- Gemfile
- Gemfile.lock
- app/services/html_to_markdown_service.rb
- lib/tasks/edit_monographs_via_csv_isbn.rake
- spec/services/html_to_markdown_service_spec.rb
> HELIO-2316: HTML to markdown

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/models/sighrax.rb
- app/models/sighrax/entity.rb
- app/models/user.rb
- config/application.rb
- config/settings/development.yml
- config/settings/test.yml
- lib/devise/fake_auth_header.rb
- lib/devise/strategies/keycard_authenticatable.rb
- spec/models/sighrax_spec.rb
Added more debug logging in preparation for bug hunting.
> Preparation for HELIO-2150: Shibboleth returns to um login bug

- app/controllers/grants_controller.rb
- app/models/sighrax.rb
- app/services/permission_service.rb
- app/services/validation_service.rb
- spec/controllers/grants_controller_spec.rb
- spec/requests/grants_spec.rb
Creating/deleting a grant for an Individual or an Institution to read a Product also a adds/removes the Individual's lessee or Institution's lessee to/from the Product's lessees.
> Resolves HELIO-2333: Refactor Fulcrum dashboard to mirror API behavior

- app/controllers/sessions_controller.rb
- app/models/user.rb
- app/views/fulcrum/_institutions.html.erb
- app/views/institutions/index.html.erb
- lib/devise/strategies/keycard_authenticatable.rb
- spec/lib/devise/keycard_authenticatable_spec.rb
This should resolve the RIAM issue of being redirect to UM Login after Shibboleth authentication.
> Remove :rememberable and add authentication by identity provider

- app/controllers/embed_controller.rb
- app/services/counter_service.rb
- spec/controllers/embed_controller_spec.rb
- spec/services/counter_service_spec.rb
> HELIO-2351 COUNTER request counts from embed (multimedia) show views

- Gemfile.lock
- app/models/individual.rb
- lib/tasks/migrate_permissions.rake
- spec/models/individual_spec.rb
- spec/requests/api/v1/individuals_spec.rb
- spec/requests/individuals_spec.rb
Rake task to create 'individuals' from 'lessees' that are not 'institutions'.
> Resolves HELIO-2371 Checkpoint Upgrade

- config/settings/development.yml
Yes, use checkpoint in development.
> e_pub_checkpoint_authorization: true

- app/helpers/press_helper.rb
- app/models/sighrax/asset.rb
- app/models/sighrax/model.rb
- app/models/sighrax/monograph.rb
- app/policies/e_pub_policy.rb
- app/services/sighrax.rb
- spec/helpers/press_helper_spec.rb
- spec/models/sighrax/asset_spec.rb
- spec/models/sighrax/model_spec.rb
- spec/models/sighrax/monograph_spec.rb
- spec/policies/e_pub_policy_spec.rb
- spec/services/sighrax_spec.rb
Allow access to EPUB components when their parent monograph has open access.
> Resolves HELIO-2388: Allow open access EPUB components

- app/controllers/api_requests_controller.rb
- app/controllers/fulcrum_controller.rb
- app/policies/e_pub_policy.rb
- app/services/incognito.rb
- app/views/fulcrum/_dashboard.html.erb
- spec/policies/e_pub_policy_spec.rb
- spec/requests/api_requests_spec.rb
- spec/services/incognito_spec.rb
Allow platform administrators to select any individual and/or any institution from the fulcrum dashboard to verify checkpoint access to products.
> Resolves HELIO-2252: Incognito Sudo Actor

- app/presenters/hyrax/monograph_presenter.rb
- app/views/monograph_catalog/_index_monograph.html.erb
- config/authorities/licenses.yml
- spec/presenters/hyrax/monograph_presenter_spec.rb
> add 'All Rights Reserved' license

- lib/import/row_data.rb
- spec/fixtures/csv/import_sections/tempest_sections.csv
- spec/lib/import/csv_parser_spec.rb
> downcase ISBN formats and creator/contributor roles

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
- spec/controllers/monograph_catalog_controller_spec.rb
- spec/controllers/press_catalog_controller_spec.rb
added isbn_tesim and isbn_ssim to search
added specs for catalog controllers
> Resolves HELIO-29: search by ISBN

- app/controllers/counter_reports_controller.rb
- app/models/counter_report.rb
- app/services/counter_reporter/item_report.rb
- app/services/counter_reporter/platform_report.rb
- app/services/counter_reporter/report_params.rb
- app/services/counter_reporter/title_report.rb
- spec/services/counter_reporter/platform_report_spec.rb
Some of the reports for all institutions can be a little slow, 2 minutes or so. Should be ok in the near term, but eventually we'll need to try something else.
> HELIO-2294 Multi-institutional COUNTER reports for platform/press admin

- app/models/guest.rb
- app/models/user.rb
- app/views/shared/_my_actions.html.erb
- spec/models/guest_spec.rb
- spec/models/user_spec.rb
Added logic to User and Guest 'name' method to handle 'guest@fulcrum.org' identifier.
> Resolves HELIO-2343: member@instiution

- app/actors/heliotrope_actor.rb
- spec/actors/heliotrope_actor_spec.rb
- spec/config/initializers/hyrax_actor_factory_spec.rb
Added specs to verify actor stack order and test the HeliotropeActor.
> Resolves HELIO-1518: actor stack specs

- lib/tasks/publish_via_doi_csv.rake
> publish Monographs using DOIs in CSV file

- lib/tasks/replace_covers_via_isbn.rake
> task to replace covers via ISBN

- lib/tasks/components_epubs_csv.rake
> csv to help create components

- lib/tasks/replace_pdf_ebooks_via_isbn.rake
> task to replace pdf_ebook reps

- lib/tasks/edit_monographs_via_csv_isbn.rake
- lib/tasks/edit_monographs_via_csv_noid.rake
> HELIO-2314/bulk update Monograph metadata (focused on EBC/michigan)

- app/views/e_pubs/access.html.erb
- app/views/e_pubs/access/_heb.html.erb
- app/views/e_pubs/access/_michigan.html.erb
- ruumba/.ruumba.yml
Added case on presenter.subdomain { 'heb', 'michigan' } to render appropriate partial (rendering nothing on default).
> Resolves HELIO-2429: Refactor Login Options Page

- app/assets/javascripts/application/ga_event_tracking.js
- config/locales/en.yml
Second try -- no clobbering the hotfix.
> Addresses HELIO-2408 Add event tracking to EBC banner link.

- fulcrum/_includes/footer.html
- fulcrum/preservation.html
Please review for formatting, since I don't have a working local copy of heliotrope to test in.
> Resolves HELIO-1809: Write Preservation Policy

- app/assets/stylesheets/application/heliotrope.scss
- app/assets/stylesheets/embed/embed_styles.scss
- app/presenters/hyrax/file_set_presenter.rb
- app/views/hyrax/file_sets/_media.html.erb
- app/views/hyrax/file_sets/media_display_embedded/_audio.html.erb
- spec/presenters/hyrax/file_set_presenter_spec.rb
> Resolves HELIO-2445: Embed code for audio

- app/views/catalog/_document.html.erb
- app/views/catalog/_view_type_group.html.erb
- app/views/counter_reports/without_customer_id/show.html.erb
- app/views/e_pubs/show.html.erb
- app/views/monograph_catalog/_document_list.html.erb
- app/views/monograph_catalog/_facet_layout.html.erb
- app/views/monograph_catalog/_index_gallery_file_set_wrapper.html.erb
- app/views/monograph_catalog/_thumbnail_file_set.html.erb
- app/views/monograph_catalog/_thumbnail_list_file_set.html.erb
- app/views/press_catalog/_document_list.html.erb
- app/views/press_catalog/_index_gallery_monograph_wrapper.html.erb
- app/views/press_catalog/_thumbnail_list_monograph.html.erb
- app/views/press_catalog/_thumbnail_monograph.html.erb
- app/views/shared/_ga.html.erb
- app/views/shared/_header.html.erb
- ruumba/.ruumba.yml
> Resolves HELIO-1212: Ruumba Cops

- app/views/e_pubs/show.html.erb
Resolves HELIO-2449
and pass parameters about the book to the qualtrics reports.
> add new qualtrics form link 

- app/controllers/application_controller.rb
- app/policies/e_pub_policy.rb
- lib/devise/strategies/keycard_authenticatable.rb
- spec/jobs/reindex_epub_job_spec.rb
- spec/lib/devise/keycard_authenticatable_spec.rb
- spec/policies/e_pub_policy_spec.rb
Set request attributes for logged in users.
> Resolves HELIO-2486: EPUB access page.

- app/views/shared/_brand_fulcrum_footer_block.html.erb
- fulcrum/_includes/header.html
Resolves HELIO-2500
Adds preservation statement link to fulcrum mobile menu; adds preservation statement link to the fulcrum footer
> HELIO-2500

- app/models/file_set.rb
- app/presenters/hyrax/file_set_presenter.rb
- app/views/hyrax/file_sets/media_display/_image_service.html.erb
- app/views/monograph_catalog/_index_gallery_file_set_wrapper.html.erb
- app/views/monograph_catalog/_thumbnail_list_file_set.html.erb
- spec/presenters/hyrax/file_set_presenter_spec.rb
https://tools.lib.umich.edu/jira/browse/HELIO-88
> support for EPS files

- app/presenters/hyrax/monograph_presenter.rb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/press_catalog/_index_gallery_monograph_wrapper.html.erb
- app/views/press_catalog/_thumbnail_list_monograph.html.erb
- app/views/press_catalog/_thumbnail_monograph.html.erb
- spec/presenters/hyrax/monograph_presenter_spec.rb
> use Hyrax work icon when no representative

- lib/import/importer.rb
- script/import
- spec/lib/import/importer_spec.rb
> import as batch/audit user (fulcrum-system)

- Gemfile
- Gemfile.lock
- config/settings/development.yml
- config/settings/production.yml.sample
- config/settings/test.yml
- lib/export/exporter.rb
- lib/tasks/bag_given_press.rake
- spec/lib/export/exporter_spec.rb
Changes to exporter to add bagit functions.
> HELIO-2528 APTrust code to generate bags

- app/jobs/delete_active_fedora_objects_job.rb
- app/overrides/hyrax/cleanup_file_sets_actor_overrides.rb
- spec/actors/hyrax/actors/cleanup_file_sets_actor_spec.rb
> clean up Monograph's ListSource

- app/presenters/hyrax/monograph_presenter.rb
- config/authorities/licenses.yml
- spec/presenters/hyrax/monograph_presenter_spec.rb
> Helio 2539/cc by 20

- Gemfile
- Gemfile.lock
- bin/travis
- config/aptrust.yml.sample
- config/settings/development.yml
- config/settings/test.yml
- lib/export/exporter.rb
- lib/tasks/bag_given_press.rake
- spec/lib/export/exporter_spec.rb
HELIO-2534 improve aptrust bag given press
HELIO-2535 add s3 plus fixes in exporter.rb
> add db calls to rake task; bug fixes

- app/assets/stylesheets/embed/embed_styles.scss
- app/presenters/concerns/embed_code_presenter.rb
- app/views/hyrax/file_sets/_media_embedded.html.erb
- app/views/hyrax/file_sets/media_display_embedded/_audio.html.erb
- spec/presenters/concerns/embed_code_presenter_spec.rb
> make room for volume slider

- lib/tasks/tmm_csv_monograph_create_update.rake
> improvments before creating nightly cron

- lib/export/exporter.rb
- spec/lib/export/exporter_spec.rb
Just adds "fulcrum" at the start of the bag name.
> 2535_add_fulcrum_to_bag_name

- app/assets/stylesheets/application/themes.scss
> HELIO-2241 - add styles for rekihaku

- lib/tasks/tmm_upload_monograph_representatives.rake
> task to upload missing covers/FeaturedRepresentatives

- config/authorities/licenses.yml
> add cc_by_sa_2.1_jp; hide 2.x licenses from drop-down

- app/presenters/e_book_download_presenter.rb
- app/presenters/hyrax/file_set_presenter.rb
Not a fix, just adding some more debugging information.
> Adds debugging to diagnose HELIO-2562.

- lib/export/exporter.rb
Rubocop insisted that I can some blank lines after guard clauses! Let me know if that's wrong for Fulcrum.
Otherwise this PR is minor updates.
> 2535_update_s3_bag_export

- lib/export/exporter.rb
Add rescue for minitar in lib/export/exporter.rb
Add temporary debug statements too.
> 2535_rescue_minitar and more debugging

- lib/export/exporter.rb
Added lots of debugging to lib/export/exporter.rb to track down crash when exporting bags.
> 2535_debug_extract

- app/controllers/api/v1/components_controller.rb
- app/controllers/components_controller.rb
- app/models/component.rb
- app/views/api/v1/components/_component.json.jbuilder
- app/views/components/_form.html.erb
- app/views/components/index.html.erb
- app/views/components/show.html.erb
- app/views/fulcrum/_components.html.erb
- db/migrate/20190318182925_remove_handle_from_components.rb
- db/schema.rb
- spec/controllers/e_pubs_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
- spec/factories/components.rb
- spec/models/component_spec.rb
- spec/models/product_spec.rb
- spec/requests/api/v1/components_spec.rb
- spec/requests/components_spec.rb
- spec/system/epub_share_links_spec.rb
Best to do this before HELIO-2529: Restricting Monograph Featured Representatives.
> Resolves HELIO-2574: Remove 'handle' field from components table.

- app/assets/stylesheets/application/themes.scss
- app/views/e_pubs/show.html.erb
> HELIO-2556 - hotfix CSS changes for rekihaku

- app/controllers/e_pubs_controller.rb
- app/controllers/products_controller.rb
- app/helpers/press_helper.rb
- app/models/sighrax/entity.rb
- app/policies/e_pub_policy.rb
- app/views/components/index.html.erb
- app/views/components/show.html.erb
- app/views/fulcrum/_components.html.erb
- app/views/fulcrum/_individuals.html.erb
- app/views/fulcrum/_institutions.html.erb
- app/views/individuals/index.html.erb
- app/views/individuals/show.html.erb
- app/views/institutions/_products.html.erb
- app/views/institutions/index.html.erb
- app/views/institutions/show.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- config/routes.rb
- lib/tasks/checkpoint_component_converter.rake
- spec/controllers/e_pubs_controller_spec.rb
- spec/helpers/press_helper_spec.rb
- spec/policies/e_pub_policy_spec.rb
- spec/presenters/e_book_download_presenter_spec.rb
- spec/system/epub_share_links_spec.rb
EPubsController, EPubPolicy, and checkpoint_component_converter.rake are the meat.
> Resolves HELIO-2529: Restricting Monograph Featured Representatives

- app/models/sighrax/asset.rb
- app/models/sighrax/electronic_publication.rb
- app/models/sighrax/entity.rb
- app/models/sighrax/mobipocket.rb
- app/models/sighrax/model.rb
- app/models/sighrax/monograph.rb
- app/models/sighrax/portable_document_format.rb
- app/services/sighrax.rb
- spec/models/sighrax/asset_spec.rb
- spec/models/sighrax/electronic_publication_spec.rb
- spec/models/sighrax/entity_spec.rb
- spec/models/sighrax/mobipocket_spec.rb
- spec/models/sighrax/model_spec.rb
- spec/models/sighrax/monograph_spec.rb
- spec/models/sighrax/portable_document_format_spec.rb
- spec/services/sighrax_spec.rb
Rename Sighrax::Entity.entity attribute to Sighrax::Entity.data.
> Rename Entity attribute 'entity' to 'data'.

- lib/export/exporter.rb
- spec/lib/export/exporter_spec.rb
Catching NoMemoryError in extract method.
Also fixed error handling when upload fails.
> 2535_debug_extract_again

- app/actors/create_with_import_files_actor.rb
- app/jobs/attach_import_files_to_work_job.rb
- lib/export/exporter.rb
- lib/import/importer.rb
- spec/actors/create_with_import_files_actor_spec.rb
- spec/fixtures/csv/import_sections/tempest_sections.csv
- spec/lib/import/csv_parser_spec.rb
- spec/lib/import/importer_spec.rb
> no file for external resources

- app/overrides/hyrax/downloads_controller_overrides.rb
- app/policies/entity_policy.rb
- app/services/sighrax.rb
- spec/controllers/hyrax/downloads_controller_spec.rb
- spec/policies/entity_policy_spec.rb
- spec/services/sighrax_spec.rb
EntityPolicy: method download?
> Resolves HELIO-2505: DownloadsController should use Checkpoint

- app/controllers/monograph_catalog_controller.rb
- app/models/press.rb
- app/policies/press_policy.rb
- app/policies/resource_policy.rb
- app/views/monograph_catalog/_index_epub_toc.html.erb
- spec/models/press_spec.rb
- spec/policies/press_policy_spec.rb
heb book
https://heliotrope-staging.hydra.lib.umich.edu/concern/monographs/xg94hp96x?locale=en
heliotrope book
https://heliotrope-staging.hydra.lib.umich.edu/concern/monographs/7w62f8676?locale=en
Open the above links in incognito windows do see the difference between the TOC on different presses.
> Resolves HELIO-2579: Download page-image epub chapters only for 'heb'.

- app/assets/stylesheets/application/themes.scss
- app/views/presses/_form.html.erb
Resolves HELIO-1854 - adds custom styles for maize books
Resolves HELIO-2614 - adds blank entry as an option in the press edit page
> HELIO-1854 and HELIO-2614

- lib/export/exporter.rb
Per Jeremy's request in: JIRA (HELIO-2603) aptrust-info.txt: Description should say more about the bag
> 2603_update_aptrust_info_desc

- lib/export/exporter.rb
- spec/lib/export/exporter_spec.rb
> Helio 2598 and 2599

- app/models/sighrax/model.rb
- spec/models/sighrax/asset_spec.rb
- spec/models/sighrax/electronic_publication_spec.rb
- spec/models/sighrax/entity_spec.rb
- spec/models/sighrax/mobipocket_spec.rb
- spec/models/sighrax/model_spec.rb
- spec/models/sighrax/monograph_spec.rb
- spec/models/sighrax/portable_document_format_spec.rb
> Sighrax refactor

- app/controllers/sessions_controller.rb
- app/services/authority.rb
- config/initializers/services.rb
- lib/tasks/checkpoint_component_converter.rake
- spec/controllers/sessions_controller_spec.rb
- spec/services/authority_spec.rb
Hotfix releases 2.35.1 and 2.35.2 ready to be merged.
> Checkpoint fix

- app/controllers/aptrust_logs_controller.rb
- app/models/aptrust_log.rb
- db/migrate/20190401161317_create_aptrust_logs.rb
- db/schema.rb
- spec/factories/aptrust_logs.rb
- spec/models/aptrust_log_spec.rb
> 2623_create_aptrust_log2

- app/controllers/products_controller.rb
- app/models/component.rb
- app/models/product.rb
- app/views/components/_products.html.erb
- app/views/components/index.html.erb
- app/views/fulcrum/_components.html.erb
- app/views/fulcrum/_individuals.html.erb
- app/views/fulcrum/_institutions.html.erb
- app/views/fulcrum/_products.html.erb
- app/views/fulcrum/_tokens.html.erb
- app/views/fulcrum/_users.html.erb
- app/views/individuals/index.html.erb
- app/views/institutions/index.html.erb
- app/views/products/index.html.erb
Cleaned up the component show page and added/modified filtering to the index pages of products, components, individuals, institutions, users and tokens.
> Resolves HELIO-2423: Fulcrum Components Show Page Changes

- app/models/sighrax/asset.rb
- app/models/sighrax/entity.rb
- app/models/sighrax/model.rb
- spec/models/sighrax/child_parent_spec.rb
- spec/models/sighrax/model_spec.rb
Spec to verify child parent relationship as well as presenter verification of metadata.
> Sighrax child parent spec

- app/views/e_pubs/_form.html.erb
- app/views/greensub/components/_component.json.jbuilder
- app/views/greensub/individuals/_individual.json.jbuilder
- app/views/greensub/institutions/_institution.json.jbuilder
- app/views/greensub/products/_product.json.jbuilder
Missed this one in the greensub namespace refactor.
> Missed this one.

- app/controllers/catalog_controller.rb
Explicit labels for config.add_facet_fields.
> Resolves HELIO-2507: Press catalog conditional logic removes labels.

- .rubocop_todo.yml
- app/indexers/file_set_indexer.rb
- app/indexers/monograph_indexer.rb
- app/jobs/output_monograph_files_job.rb
- app/models/sighrax/asset.rb
- app/models/sighrax/model.rb
- app/models/sighrax/monograph.rb
- app/presenters/hyrax/file_set_presenter.rb
- lib/export/exporter.rb
- spec/jobs/output_monograph_files_job_spec.rb
- spec/lib/export/exporter_spec.rb
- spec/models/sighrax/asset_spec.rb
- spec/models/sighrax/model_spec.rb
- spec/models/sighrax/monograph_spec.rb
- spec/spec_helper.rb
> export metadata from Solr

- lib/export/exporter.rb
- lib/tasks/bag_updated_monographs.rake
**Changes include:**
Modifications to authentication keys for the new fulcrum.org subdomain in the aptrust.yml files.
Changes to rake task and exporter for new subdomain and bag naming.
Improvements to rake method update_db_aptrust_status.
> update aptrust rake and exporter for new subdomain

- app/jobs/characterize_job.rb
- spec/jobs/characterize_job_spec.rb
> tidy up metadata on new file version

- lib/export/exporter.rb
- lib/tasks/bag_updated_monographs.rake
Also, other misc clean up. :-)
> Make Sighrax adjustments

- lib/tasks/bag_updated_monographs.rake
Small fixes and improvements only
> 2541_rake_add_apt_check5

- app/overrides/hyrax/file_sets_actor_overrides.rb
- spec/actors/hyrax/actors/file_set_actor_spec.rb
> override FileSet's depositor as creator

- lib/tasks/bag_updated_monographs.rake
Continued to simplify bag_update_monographs.rake task and improve error reporting.
> 2404_aptrust_clean_up2

- app/assets/javascripts/application/ga_event_tracking.js
- app/views/e_pubs/show.html.erb
> JQuery event delegation to move CSB GA events

- lib/export/exporter.rb
- lib/tasks/bag_updated_monographs.rake
Add validation of the bag before tarring and uploading.
> 2404 aptrust clean up3

- lib/export/exporter.rb
- lib/tasks/bag_updated_monographs.rake
**Changes:**
- No longer prepending 'fulcrum.org.' since all fulcrum SIPs are in the APTrust fulcrum domain.
- Create the Settings.aptrust_bags_path directory if it doesn't exist.
- Added 'Internal-Sender-Description' and 'Internal-Sender-Identifier' to the bagit-info.txt file since they are shown in the a Pharos interface.
- Fixed bug in display of the monograph title in the Pharos interface.
- Use solr only as opposed to solr and ruby select to get published solr docs.
> 2404_aptrust_clean_up4

- Gemfile
Fixes:  sudo -u heliotrope-preview RAILS_ENV=production bundle exec rails console
> Not sure why this is any different, but it works.

- app/services/restful_solr.rb
- app/services/restful_solr/service.rb
- spec/services/restful_solr/service_spec.rb
- spec/services/restful_solr_spec.rb
Direct access to Solr's REST API.
> Restful Solr

- config/initializers/hyrax.rb
> create Monograph w/o files in UI

- app/presenters/concerns/title_presenter.rb
- app/services/markdown_service.rb
- app/views/monograph_catalog/index.html.erb
- lib/tasks/tmm_csv_monograph_create_update.rake
- spec/features/create_monograph_spec.rb
- spec/presenters/concerns/title_presenter_spec.rb
- spec/services/markdown_service_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
> Markdown ignores hashtag; HTML in title

- spec/services/restful_fedora/service_spec.rb
- spec/services/restful_solr/service_spec.rb
> minor spec refactoring

- lib/export/exporter.rb
- spec/lib/export/exporter_spec.rb
> fix Exporter::monograph_row()

- app/jobs/attach_import_files_to_work_job.rb
- app/overrides/hyrax/file_set_actor_overrides.rb
- app/overrides/hyrax/ordered_members_actor_overrides.rb
> Helio 2696/adding representatives problem

- app/overrides/hyrax/file_set_actor_overrides.rb
- app/overrides/hyrax/file_set_ordered_members_actor_overrides.rb
- app/views/hyrax/monographs/_show_actions.html.erb
- lib/import/importer.rb
- spec/jobs/attach_import_files_to_work_job_spec.rb
> stop Hyrax setting Monograph cover

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/ebooks_controller.rb
- app/models/sighrax/asset.rb
- app/policies/press_policy.rb
- app/services/incognito.rb
- app/services/sighrax.rb
- app/views/monograph_catalog/_index_monograph.html.erb
- config/routes.rb
- spec/controllers/application_controller_spec.rb
- spec/fixtures/clippath.pdf
- spec/models/sighrax/asset_spec.rb
- spec/policies/press_policy_spec.rb
- spec/requests/ebooks_spec.rb
- spec/services/sighrax_spec.rb
It works, now all that is need is the final wording of the watermark.
> Partially :Resolves 2561: Implement PDF Watermarks for EBC

- app/controllers/ebooks_controller.rb
- app/controllers/presses_controller.rb
- app/policies/press_policy.rb
- app/views/presses/_form.html.erb
- db/migrate/20190506144028_add_watermark_to_presses.rb
- db/schema.rb
- spec/policies/press_policy_spec.rb
- spec/requests/ebooks_spec.rb
Added boolean 'watermark' field to presses table.
> Resolves HELIO-2703: Add toggle to Publisher's edit page for watermarks

- lib/export/exporter.rb
Fix up for mistake on the bag name.
> 2404_minor fixes

- app/indexers/file_set_indexer.rb
> don't repeatedly call in_works

- app/presenters/concerns/social_share_widget_presenter.rb
- app/views/hyrax/file_sets/_show_actions.html.erb
- spec/features/edit_file_set_spec.rb
- spec/presenters/concerns/social_share_widget_presenter_spec.rb
> remove G+ links; FileSet links open new tab

- Gemfile
- Gemfile.lock
> update csb to pull in resolution for CSB-219

- app/views/e_pubs/show.html.erb
fixes issue with gabii's ereader not loading.
> add back in accidental removal

- app/jobs/attach_import_files_to_work_job.rb
- lib/tasks/tmm_upload_monograph_representatives.rake
- spec/rails_helper.rb
> use publisher arg; lock before saving cover

- config/locales/en.yml
- spec/features/create_monograph_spec.rb
> monograph form label/hint fixes

- lib/tasks/bag_updated_monographs.rake
A small clean up of date handling in rake task.
> 2404_aptrust_clean_up8

- lib/tasks/bag_updated_monographs.rake
BUG FIX:
Now checks the parsed APTrust response for parsed['count'].zero? and, if true, sets the db record APT_STATUSES to 'not_found'.
> fix handling of APTrust API response

- app/assets/stylesheets/application/themes.scss
Resolves HELIO-2635 by adding overrides to default search button for resources on monograph catalog pages.
> HELIO-2635 - customize search resources buttons for each press

- app/services/crossref/file_set_metadata.rb
- spec/services/crossref/file_set_metadata_spec.rb
> HELIO-2743 Exclude "cover", "epub", "pdf_ebook" and "mobi" from

- app/assets/stylesheets/application/themes.scss
- app/views/e_pubs/show.html.erb
Adds branding elements for Sussex
> HELIO-2760 - branding for university of sussex library

- Gemfile
- Gemfile.lock
I've tested this in a variety of browsers and it seem fine. It's currently on preview.
> CSB-220, update CSB with tables within modals

- lib/tasks/tmm_non_representative_file_sets.rake
> task to import/replace resources

- app/controllers/monograph_catalog_controller.rb
- app/presenters/concerns/featured_representatives/file_set_presenter.rb
- app/services/counter_service.rb
- lib/tasks/counter_report_access_type_fixup.rake
- spec/presenters/concerns/featured_representatives/file_set_presenter_spec.rb
- spec/services/counter_service_spec.rb
This is on preview. The rake task was tested and seems good.
> HELIO-2779 COUNTER count adjustments

- lib/import/row_data.rb
> no missing metadata messages for representatives

- app/presenters/concerns/embed_code_presenter.rb
- app/presenters/concerns/title_presenter.rb
- spec/presenters/concerns/embed_code_presenter_spec.rb
- spec/presenters/concerns/title_presenter_spec.rb
> escape HTML in embed code titles

- config/sitemap.rb
I think this will do what we want...
> HELIO-2767 No sitemap entry for epubs behind checkpoint

- config/jekyll.yml
- config/sitemap.rb
> sitemaps in shared directory, handle tombstoned FileSets

- Gemfile
- Gemfile.lock
Update CSB to use current master which includes a patch for displaying tables in modal on safari
> HELIO-2796 - update csb 

- lib/tasks/replace_epubs_via_isbn.rake
> task to add/replace EPUB reps

- app/models/share_link_log.rb
- app/views/share_link_logs/index.html.erb
Original issue is pair of typos, then this exposed an issue with LIKE queries against DATETIME values.
> Addresses HELIO-2662 Filter by Created/Action for the share_link_logs

- app/views/shared/_brand_fulcrum_footer_block.html.erb
> no turbolinks on links to static site

- lib/import/row_data.rb
- spec/fixtures/csv/import_sections/tempest_sections.csv
> allow full Creative Commons license names

- app/views/catalog/_paginate_compact.html.erb
- app/views/catalog/_results_pagination.html.erb
- app/views/kaminari/blacklight/_first_page.html.erb
- app/views/kaminari/blacklight/_gap.html.erb
- app/views/kaminari/blacklight/_last_page.html.erb
- app/views/kaminari/blacklight/_next_page.html.erb
- app/views/kaminari/blacklight/_page.html.erb
- app/views/kaminari/blacklight/_paginator.html.erb
- app/views/kaminari/blacklight/_prev_page.html.erb
- app/views/kaminari/blacklight_compact/_next_page.html.erb
- app/views/kaminari/blacklight_compact/_paginator.html.erb
- app/views/kaminari/blacklight_compact/_prev_page.html.erb
- config/locales/en.yml
Additions derived from https://github.com/projectblacklight/blacklight/pull/1970/commits/abd69d10b468e18aba4c10965f71678e99834ab7 with modifications to pass RuboCop/Ruumba.
> Addresses HELIO-1989 Improve search and browse pagination link labels.

- config/initializers/lib_dir.rb
- lib/tasks/edit_objects_via_csv_noid.rake
> find-by-NOID and edit Monographs or FileSets

- app/controllers/aptrust_deposits_controller.rb
- app/controllers/fulcrum_controller.rb
- app/jobs/aptrust_deposit_job.rb
- app/jobs/aptrust_job.rb
- app/models/aptrust_deposit.rb
- app/views/aptrust_deposits/index.html.erb
- app/views/fulcrum/_jobs.html.erb
- app/views/fulcrum/_logs.html.erb
- app/views/greensub/institutions/index.html.erb
- config/routes.rb
- db/migrate/20190708122200_create_aptrust_deposits.rb
- db/schema.rb
- lib/tasks/aptrust.rake
- spec/factories/aptrust_deposits.rb
- spec/jobs/aptrust_deposit_job_spec.rb
- spec/jobs/aptrust_job_spec.rb
- spec/models/aptrust_deposit_spec.rb
- spec/requests/aptrust_deposits_spec.rb
Refactor of bag_updated_monographs.rake into jobs.
> Resolves HELIO-2723: Run initial deposit into production APTrust

- app/services/markdown_service.rb
- spec/presenters/concerns/title_presenter_spec.rb
- spec/services/markdown_service_spec.rb
> don't use HTML entities for special characters

- app/controllers/fulcrum_controller.rb
- app/jobs/aptrust_deposit_job.rb
- app/jobs/aptrust_job.rb
- app/jobs/aptrust_verify_job.rb
- app/services/aptrust/service.rb
- app/views/aptrust_deposits/index.html.erb
- app/views/fulcrum/_jobs.html.erb
- db/migrate/20190717185419_add_verified_to_aptrust_deposits.rb
- db/schema.rb
- spec/jobs/aptrust_deposit_job_spec.rb
- spec/jobs/aptrust_job_spec.rb
- spec/jobs/aptrust_verify_job_spec.rb
- spec/services/aptrust/service_spec.rb
> Resolves HELIO-2724: Set up cron for ongoing APTrust deposits

- app/assets/stylesheets/application/themes.scss
> Add branding for a2ru

- app/controllers/maps_controller.rb
- app/presenters/concerns/embed_code_presenter.rb
- app/views/hyrax/file_sets/media_display_embedded/_map.html.erb
- spec/presenters/concerns/embed_code_presenter_spec.rb
- spec/presenters/hyrax/file_set_presenter_spec.rb
First iteration on embed functionality for maps.
> Resolves HELIO-2798: Extend FileSet embeds to support a Leaflet map

- lib/pdf_ebook/publication.rb
- lib/spec/pdf_ebook/publication_spec.rb
> HELIO-2863/HELIO-2871/pdf_toc

- app/presenters/e_book_download_presenter.rb
- spec/presenters/e_book_download_presenter_spec.rb
> ebooks controller for watermarked downloads

- app/controllers/monograph_catalog_controller.rb
- app/helpers/breadcrumbs_helper.rb
- app/helpers/press_helper.rb
- app/views/catalog/_search_sidebar.html.erb
- app/views/layouts/curation_concerns.html.erb
- app/views/layouts/hyrax.html.erb
- app/views/monograph_catalog/_custom_section_facet.html.erb
- app/views/monograph_catalog/_index_epub_toc.html.erb
- app/views/monograph_catalog/_index_header_list_file_set.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/monograph_catalog/_stats.html.erb
- app/views/monograph_catalog/index.html.erb
- app/views/shared/_altmetric_dimensions.html.erb
- app/views/shared/_brand_press_bar.html.erb
- app/views/shared/_metadata.html.erb
- app/views/shared/_survey.html.erb
- spec/controllers/monograph_catalog_controller_spec.rb
- spec/features/create_external_resource_spec.rb
- spec/helpers/breadcrumbs_spec.rb
- spec/helpers/press_helper_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
- spec/views/shared/_metadata.html.erb_spec.rb
@monograph_presenter to be @presenter. This won't change anything, but is in preparation to maybe adding a new Work type.
> HELIO-2874 Refactor monograph_catalog_controller's

- lib/tasks/royalty_usage_report.rake
> remove Solr phrase query, optimize

- app/views/e_pubs/_cozy_controls_bottom.html.erb
> stop Mozilla reader click event on #download

- app/presenters/concerns/common_work_presenter.rb
- app/presenters/hyrax/monograph_presenter.rb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/press_catalog/_index_gallery_monograph_wrapper.html.erb
- app/views/press_catalog/_thumbnail_list_monograph.html.erb
- app/views/press_catalog/_thumbnail_monograph.html.erb
- spec/presenters/concerns/common_work_presenter_spec.rb
- spec/presenters/hyrax/monograph_presenter_spec.rb
and add them to a CommonWorkPresenter mixin
> HELIO-2874 Take generic Work methods out of the MonographPresenter

- app/views/monograph_catalog/_index_monograph.html.erb
> show ToC tab for all reader e-books

- app/controllers/e_pubs_controller.rb
- app/helpers/breadcrumbs_helper.rb
- app/helpers/press_helper.rb
- app/models/ability.rb
- app/presenters/hyrax/file_set_presenter.rb
- app/services/counter_service.rb
- app/views/hyrax/file_sets/_attribute_rows_info.html.erb
- app/views/hyrax/file_sets/show.html.erb
- app/views/layouts/curation_concerns.html.erb
- app/views/layouts/hyrax.html.erb
- app/views/shared/_brand_press_bar.html.erb
- app/views/shared/_survey.html.erb
- spec/controllers/e_pubs_controller_spec.rb
- spec/controllers/embed_controller_spec.rb
- spec/helpers/breadcrumbs_spec.rb
- spec/helpers/press_helper_spec.rb
- spec/models/ability_spec.rb
- spec/presenters/concerns/open_url_presenter_spec.rb
- spec/presenters/hyrax/file_set_presenter_spec.rb
- spec/services/counter_service_spec.rb
- spec/services/crossref/file_set_metadata_spec.rb
for different kinds of Work types
> HELIO-2874 FileSetPresenter.parent is now more generic to allow

- app/views/featured_representatives/_form.html.erb
> There's no longer a Hyrax::MonographPresenter.monograph method,

- app/assets/stylesheets/mozilla-pdf-viewer/cozy-honey-bear-reader.css
- app/views/e_pubs/show_pdf.html.erb
> restrict height of cozy controls

- app/views/hyrax/base/_form_metadata.html.erb
> remove 'form_media' partial

- app/views/e_pubs/show_pdf.html.erb
> use heliotrope metadata for title

- app/views/tombstones/index.html.erb
Resolves 500 error caused by orphaned FileSets.
> fix to tombstone index view

- app/policies/entity_policy.rb
- spec/policies/entity_policy_spec.rb
Inserted tombstone check between user can edit and allow download.
> Resolves HELIO-2910: EntityPolicy.download? needs to be tombstone-aware

- app/assets/stylesheets/application/heliotrope.scss
- app/views/hyrax/file_sets/_media.html.erb
- app/views/hyrax/file_sets/_media_embedded.html.erb
- app/views/hyrax/file_sets/_media_tombstone.html.erb
- spec/requests/file_sets_spec.rb
> Resolves HELIO-2909: Style FileSet Tombstone message

- app/views/e_pubs/show_pdf.html.erb
> Resolves HELIO-2907: PDF Viewer - Rename 'Document Outline'

- app/assets/stylesheets/application/themes.scss
Add a theme for BAR publishing
> HELIO-2803 - add branding for bar

- app/assets/stylesheets/application/heliotrope.scss
- app/views/monograph_catalog/_index_monograph.html.erb
removing fade from modal solved a lot of issues.
> Resolves HELIO-2820: Allow enlarging of cover thumbnails for Monographs

- Gemfile
- Gemfile.lock
> update devise, devise-guests

- app/presenters/concerns/common_work_presenter.rb
- spec/presenters/concerns/common_work_presenter_spec.rb
- spec/presenters/hyrax/monograph_presenter_spec.rb
- spec/views/hyrax/file_sets/show.html.erb_spec.rb
> check visibility of assets

- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/score_catalog/_index_score.html.erb
typos and HELIO-2853 follow-up
> Old typos n helio 2853

- app/assets/stylesheets/application/themes.scss
Adds theme for Amherst College Press. Screenshots attached.
> HELIO-2856 Style amherst

- vendor/assets/stylesheets/Control.FullScreen.css.scss
All the kool kids are using .scss
> vendor images

- app/views/hyrax/file_sets/media_display/_leaflet_image.html.erb
- app/views/hyrax/file_sets/media_display_embedded/_leaflet_image.html.erb
> change full-screen button title

- lib/tasks/ga_cache.rake
Tested on preview and run via cron and it works fine.
> HELIO-2972 fix failing ga_cache rake task

- .rubocop.yml
- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
- app/forms/hyrax/forms/batch_upload_form.rb
- app/models/monograph_search_builder.rb
- app/presenters/hyrax/monograph_presenter.rb
- app/presenters/hyrax/score_presenter.rb
- app/renderers/hyrax/renderers/monograph_facet_attribute_renderer.rb
- app/services/analytics_service.rb
- bin/spring
- config/initializers/mailboxer.rb
- ruumba/.ruumba.yml
- spec/controllers/application_controller_spec.rb
- spec/features/edit_file_set_spec.rb
- spec/features/press_catalog_sort_spec.rb
- spec/jobs/minimal_epub_job_spec.rb
- spec/lib/devise/keycard_authenticatable_spec.rb
- spec/models/counter_report_spec.rb
- spec/models/greensub/component_spec.rb
- spec/models/greensub/product_spec.rb
- spec/models/press_spec.rb
- spec/models/user_spec.rb
- spec/policies/actor_agent_resolver_spec.rb
- spec/policies/application_policy_spec.rb
- spec/policies/target_resource_resolver_spec.rb
- spec/requests/api/tokens_spec.rb
- spec/services/dlps_institution_spec.rb
- spec/services/sighrax_spec.rb
- spec/services/validation_service_spec.rb
> Resolves HELIO-2930: minor rubocop oddity

- app/controllers/application_controller.rb
- config/features.yml
- config/routes.rb
- spec/system/batch_create_monographs_spec.rb
- spec/system/create_score_spec.rb
> disable unneeded Hyrax features

- app/presenters/concerns/featured_representatives/monograph_presenter.rb
- app/views/e_pubs/show_pdf.html.erb
- spec/presenters/concerns/featured_representatives/monograph_presenter_spec.rb
> Resolves HELIO-2906: Make the Document Outline the default TOC

- Gemfile
- Gemfile.lock
- app/views/e_pubs/_cozy_controls_bottom.html.erb
Depends on https://github.com/mlibrary/cozy-sun-bear/pull/194
> Replace custom fullscreen widget with cozy.control.fullscreen

- app/assets/javascripts/application/ga_event_tracking.js
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/score_catalog/_index_score.html.erb
- spec/features/monograph_catalog_facets_spec.rb
- spec/system/monograph_catalog_toc_spec.rb
* Add ga event tracking to Work tabs
* Added dynamic ga event tracking for facets
> HELIO-2934, HELIO-2220

- app/assets/stylesheets/mozilla-pdf-viewer/cozy-honey-bear-reader.css
Use page shadow from cozy-sun-bear to be cross-platform and consistent.
> Tweak page shadow effect

- app/presenters/hyrax/monograph_presenter.rb
- spec/features/press_catalog_spec.rb
- spec/presenters/hyrax/monograph_presenter_spec.rb
> Helio 2990/remove heb reverse authorship

- app/views/e_pubs/show.html.erb
> Hypothesis.js panel closed by default

- app/presenters/concerns/common_work_presenter.rb
- app/presenters/hyrax/monograph_presenter.rb
- app/presenters/hyrax/score_presenter.rb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/score_catalog/_index_score.html.erb
- spec/presenters/concerns/common_work_presenter_spec.rb
- spec/presenters/hyrax/monograph_presenter_spec.rb
populate it with the value of the CC license displayed
> Resolves HELIO-2955 Remove aria-label attribute on CC license

- app/presenters/concerns/analytics_presenter.rb
- spec/presenters/concerns/analytics_presenter_spec.rb
This is in production as 2.47.1
> HELIO-3030 Fixes a bug in the GA stats graphs

- app/views/hyrax/base/_form.html.erb
> Helio 2279/bad batch link

- app/services/crossref/file_set_metadata.rb
- spec/services/crossref/file_set_metadata_spec.rb
> no FeaturedReps get auto-generated DOIs

- app/assets/javascripts/application/ga_event_tracking.js
- app/helpers/press_helper.rb
- app/views/hyrax/file_sets/media_display_embedded/_audio.html.erb
- app/views/hyrax/file_sets/media_display_embedded/_leaflet_image.html.erb
- app/views/hyrax/file_sets/media_display_embedded/_video.html.erb
- app/views/shared/_ga.html.erb
- spec/helpers/press_helper_spec.rb
Also fixes a copy-paste bug in the leaflet code causing pan-down events to be posted as pan-right.
> Addresses HELIO-3000 Include Parent Press GA ID on Sub Press pages

- app/models/riiif/file.rb
- app/presenters/concerns/common_work_presenter.rb
- app/views/hyrax/file_sets/media_display/_image_service.html.erb
- app/views/monograph_catalog/_index_gallery_file_set_wrapper.html.erb
- app/views/monograph_catalog/_thumbnail_list_file_set.html.erb
- app/views/score_catalog/_thumbnail_list_file_set.html.erb
- lib/tasks/sample_iiif_urls.rake
- spec/models/riiif/file_spec.rb
- spec/presenters/concerns/common_work_presenter_spec.rb
> Monograph covers use PNG thumbnails

- app/assets/stylesheets/application/themes.scss
> HELIO-3026 - add brands for ATG

- app/views/e_pubs/_cozy_controls_bottom.html.erb
> remove permalink widget

- app/controllers/press_statistics_controller.rb
- app/controllers/presses_controller.rb
- app/helpers/press_helper.rb
- app/views/hyrax/admin/stats/_analytics.html.erb
- app/views/press_statistics/index.html.erb
- app/views/presses/_form.html.erb
- app/views/shared/_brand_press_jumbotron.html.erb
- config/routes.rb
- db/migrate/20191025183154_add_readership_map_url_to_presses.rb
- db/schema.rb
- spec/controllers/press_statistics_controller_spec.rb
- spec/helpers/press_helper_spec.rb
- spec/views/shared/_brand_press_jumbotron.html.erb_spec.rb
Note: app/views/hyrax/admin/stats/_analytics.html.erb is a semi-related bug fix not included in the ticket.
> Addresses HELIO-2983 make analytics world visible

- app/presenters/hyrax/file_set_presenter.rb
- app/views/hyrax/file_sets/media_display/_leaflet_image.html.erb
- app/views/hyrax/file_sets/media_display_embedded/_leaflet_image.html.erb
- spec/presenters/hyrax/file_set_presenter_spec.rb
> metadata can disable full-screen Leaflet

- app/models/press.rb
- spec/factories/presses.rb
- spec/features/press_catalog_sort_spec.rb
- spec/features/press_catalog_spec.rb
- spec/helpers/press_helper_spec.rb
- spec/models/press_spec.rb
- spec/system/monograph_catalog_toc_spec.rb
- spec/views/monograph_catalog/index.html.erb_spec.rb
2 to 32 lowercase alphanumeric ascii characters
> Resolves HELIO-2852 Restrict Press Subdomain Entries

- app/views/e_pubs/show.html.erb
- app/views/e_pubs/show_pdf.html.erb
- app/views/hyrax/file_sets/show.html.erb
- app/views/hyrax/monographs/_show_actions.html.erb
- app/views/monograph_catalog/_index_monograph.html.erb
- app/views/score_catalog/_index_score.html.erb
They really are obnoxious when read to you.
> Hide COinS title from screen readers

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application/heliotrope.scss
- app/assets/stylesheets/application/themes.scss
- app/views/e_pubs/_cozy_controls_bottom.html.erb
> Resolves HELIO-2895 Visually indicate keyboard selection of preferences

- app/views/hyrax/file_sets/_media_tombstone.html.erb
> update tombstoned resource message

- Gemfile
- Gemfile.lock
- app/views/press_statistics/index.html.erb
While we decide what to do about https://github.com/eagleas/clamav/issues/11
> Temp remove clamav
